DELETE FROM countries;
INSERT INTO countries VALUES('af','افغانستان','{"en":"Afghanistan","es":"Afganistán", "ja":"アフガニスタン","fr": "Afghanistan"}',1);
INSERT INTO countries VALUES('al','Shqipëria','{"en":"Albania","es":"Albania", "ja":"アルバニア","fr": "Albanie"}',2);
INSERT INTO countries VALUES('dz','الجزائر','{"en":"Algeria","es":"Argelia", "ja":"アルジェリア
","fr": "Algérie"}',3);
INSERT INTO countries VALUES('as','American Samoa','{"en":"American Samoa","es":"Samoa Americana", "ja":"米領サモア","fr": "Samoa américaines"}',4);
INSERT INTO countries VALUES('ad','Andorra','{"en":"Andorra","es":"Andorra", "ja":"アンドラ", "fr": "Andorre"}',5);
INSERT INTO countries VALUES('ao','Angola','{"en":"Angola","es":"Angola", "ja":"アンゴラ","fr": "Angola"}',6);
INSERT INTO countries VALUES('ai','Anguilla','{"en":"Anguilla","es":"Anguila", "ja":"アンギラ","fr": "Anguilla"}',7);
INSERT INTO countries VALUES('aq','Antarctica','{"en":"Antarctica","es":"Antártida", "ja":"南極大陸","fr": "Antarctique"}',8);
INSERT INTO countries VALUES('ag','Antigua and Barbuda','{"en":"Antigua and Barbuda","es":"Antigua y Barbuda", "ja":"アンティグア・バーブーダ","fr": "Antigua-et-Barbuda"}',9);
INSERT INTO countries VALUES('ar','Argentina','{"en":"Argentina","es":"Argentina", "ja":"アルゼンチン","fr": "Argentine"}',10);
INSERT INTO countries VALUES('am','Հայաստան','{"en":"Armenia","es":"Armenia", "ja":"アルメニア","fr": "Arménie"}',11);
INSERT INTO countries VALUES('aw','Aruba','{"en":"Aruba","es":"Aruba", "ja":"アルバ","fr": "Aruba"}',12);
INSERT INTO countries VALUES('au','Australia','{"en":"Australia","es":"Australia", "ja":"オーストラリア","fr": "Australie"}',13);
INSERT INTO countries VALUES('at','Österreich','{"en":"Austria","es":"Austria", "ja":"オーストリア","fr": "Autriche"}',14);
INSERT INTO countries VALUES('az','Azərbaycan','{"en":"Azerbaijan","es":"Azerbaiyán", "ja":"アゼルバイジャン","fr": "Azerbaïdjan"}',15);
INSERT INTO countries VALUES('bs','Bahamas','{"en":"Bahamas","es":"Bahamas", "ja":"バハマ","fr": "Bahamas"}',16);
INSERT INTO countries VALUES('bh','البحرين','{"en":"Bahrain","es":"Bahréin", "ja":"バーレーン","fr": "Bahreïn"}',17);
INSERT INTO countries VALUES('bd','বাংলাদেশ','{"en":"Bangladesh","es":"Bangladesh", "ja":"バングラディッシュ","fr": "Bangladesh"}',18);
INSERT INTO countries VALUES('bb','Barbados','{"en":"Barbados","es":"Barbados", "ja":"バルバトス","fr": "Barbade"}',19);
INSERT INTO countries VALUES('by','Белару́сь','{"en":"Belarus","es":"Bielorrusia", "ja":"ベラルーシ","fr": "Biélorussie"}',20);
INSERT INTO countries VALUES('be','België','{"en":"Belgium","es":"Bélgica", "ja":"ベルギー","fr": "Belgique"}',21);
INSERT INTO countries VALUES('bz','Belize','{"en":"Belize","es":"Belice", "ja":"ベリーズ","fr": "Belize"}',22);
INSERT INTO countries VALUES('bj','Bénin','{"en":"Benin","es":"Benín", "ja":"ベニン","fr": "Bénin"}',23);
INSERT INTO countries VALUES('bm','Bermuda','{"en":"Bermuda","es":"Bermudas", "ja":"バミューダ","fr": "Bermudes"}',24);
INSERT INTO countries VALUES('bt','འབྲུག་ཡུལ','{"en":"Bhutan","es":"Bután", "ja":"ブータン","fr": "Bhoutan"}',25);
INSERT INTO countries VALUES('bo','Bolivia','{"en":"Bolivia","es":"Bolivia", "ja":"ボリビア","fr": "Bolivie"}',26);
INSERT INTO countries VALUES('ba','Bosna i Hercegovina','{"en":"Bosnia and Herzegovina","es":"Bosnia-Herzegovina", "ja":"ボスニア・ヘルツェゴビナ","fr": "Bosnie-Herzégovine"}',27);
INSERT INTO countries VALUES('bw','Botswana','{"en":"Botswana","es":"Botsuana", "ja":"ボツワナ","fr": "Botswana"}',28);
INSERT INTO countries VALUES('bv','Bouvet Island','{"en":"Bouvet Island","es":"Isla Bouvet", "ja":"ブーベ島","fr": "Île Bouvet"}',29);
INSERT INTO countries VALUES('br','Brasil','{"en":"Brazil","es":"Brasil", "ja":"ブラジル","fr": "Brésil"}',30);
INSERT INTO countries VALUES('io','British Indian Ocean Territory','{"en":"British Indian Ocean Territory","es":"Territorio Británico del Océano Índico", "ja":"英領インド洋地域","fr": "Territoire britannique de l''océan indien"}',31);
INSERT INTO countries VALUES('bn','Brunei Darussalam','{"en":"Brunei","es":"Brunéi", "ja":"ブルネイ","fr": "Brunei"}',32);
INSERT INTO countries VALUES('bg','България','{"en":"Bulgaria","es":"Bulgaria", "ja":"ブルガリア","fr": "Bulgarie"}',33);
INSERT INTO countries VALUES('bf','Burkina Faso','{"en":"Burkina Faso","es":"Burkina Faso", "ja":"ブルキナファソ","fr": "Burkina Faso"}',34);
INSERT INTO countries VALUES('bi','Uburundi','{"en":"Burundi","es":"Burundi", "ja":"ブルンジ","fr": "Burundi"}',35);
INSERT INTO countries VALUES('kh','Kampuchea','{"en":"Cambodia","es":"Camboya", "ja":"カンボジア","fr": "Cambodge"}',36);
INSERT INTO countries VALUES('cm','Cameroun','{"en":"Cameroon","es":"Camerún", "ja":"カメルーン","fr": "Cameroun"}',37);
INSERT INTO countries VALUES('ca','Canada','{"en":"Canada","es":"Canadá", "ja":"カナダ","fr": "Canada"}',38);
INSERT INTO countries VALUES('cv','Cabo Verde','{"en":"Cape Verde","es":"Cabo Verde", "ja":"カーボヴェルデ","fr": "Cap-Vert"}',39);
INSERT INTO countries VALUES('ky','Cayman Islands','{"en":"Cayman Islands","es":"Islas Caimán", "ja":"ケイマン諸島", "fr": "Îles Caïman"}',40);
INSERT INTO countries VALUES('cf','République Centrafricaine','{"en":"Central African Republic","es":"República Centroafricana", "ja":"中央アフリカ共和国","fr": "République Centrafricaine"}',41);
INSERT INTO countries VALUES('td','Tchad','{"en":"Chad","es":"Chad", "ja":"チャド","fr": "Le Tchad"}',42);
INSERT INTO countries VALUES('cl','Chile','{"en":"Chile","es":"Chile", "ja":"チリ","fr": "Chili"}',43);
INSERT INTO countries VALUES('cn','中国','{"en":"China","es":"China", "ja":"中国","fr": "Chine"}',44);
INSERT INTO countries VALUES('cx','Christmas Island','{"en":"Christmas Island","es":"Isla Christmas", "ja":"クリスマス島","fr": "Île Christmas"}',45);
INSERT INTO countries VALUES('cc','Cocos Islands','{"en":"Cocos Islands","es":"Islas Cocos", "ja":"ココス諸島","fr": "Îles Cocos"}',46);
INSERT INTO countries VALUES('co','Colombia','{"en":"Colombia","es":"Colombia", "ja":"コロンビア","fr": "Colombie"}',47);
INSERT INTO countries VALUES('km','Comores','{"en":"Comoros","es":"Comoras", "ja":"コモロ","fr": "Comores"}',48);
INSERT INTO countries VALUES('cg','Republic Of Congo','{"en":"Republic Of Congo","es":"Congo", "ja":"コンゴ共和国","fr": "République du Congo"}',49);
INSERT INTO countries VALUES('cd','The Democratic Republic Of The Congo','{"en":"The Democratic Republic Of The Congo","es":"República Democrática del Congo", "ja":"コンゴ民主共和国","fr": "La République Démocratique du Congo"}',50);
INSERT INTO countries VALUES('ck','Cook Islands','{"en":"Cook Islands","es":"Islas Cook", "ja":"クック諸島","fr": "Îles Cook"}',51);
INSERT INTO countries VALUES('cr','Costa Rica','{"en":"Costa Rica","es":"Costa Rica", "ja":"コスタリカ","fr": "Costa Rica"}',52);
INSERT INTO countries VALUES('ci','Côte d''Ivoire','{"en":"Côte d\u0027Ivoire","es":"Costa de Marfil", "ja":"コートジボワール","fr": "Côte d\u0027Ivoire"}',53);
INSERT INTO countries VALUES('hr','Hrvatska','{"en":"Croatia","es":"Croacia", "ja":"クロアチア","fr": "Croatie"}',54);
INSERT INTO countries VALUES('cu','Cuba','{"en":"Cuba","es":"Cuba", "ja":"キューバ","fr": "Cuba"}',55);
INSERT INTO countries VALUES('cy','Κυπρος','{"en":"Cyprus","es":"Chipre", "ja":"キプロス","fr": "Chypre"}',56);
INSERT INTO countries VALUES('cz','Česko','{"en":"Czech Republic","es":"República Checa", "ja":"チェコ","fr": "République tchèque"}',57);
INSERT INTO countries VALUES('dk','Danmark','{"en":"Denmark","es":"Dinamarca", "ja":"デンマーク","fr": "Danemark"}',58);
INSERT INTO countries VALUES('dj','Djibouti','{"en":"Djibouti","es":"Yibuti", "ja":"ジブチ","fr": "Djibouti"}',59);
INSERT INTO countries VALUES('dm','Dominica','{"en":"Dominica","es":"Dominica", "ja":"ドミニカ国","fr": "Dominique"}',60);
INSERT INTO countries VALUES('do','Dominican Republic','{"en":"Dominican Republic","es":"República Dominicana", "ja":"ドミニカ共和国","fr": "République Dominicaine"}',61);
INSERT INTO countries VALUES('ec','Ecuador','{"en":"Ecuador","es":"Ecuador", "ja":"エクアドル","fr": "Équateur"}',62);
INSERT INTO countries VALUES('eg','مصر','{"en":"Egypt","es":"Egipto", "ja":"エジプト","fr": "Égypte"}',63);
INSERT INTO countries VALUES('sv','El Salvador','{"en":"El Salvador","es":"El Salvador", "ja":"エルサルバドル","fr": "Le Salvador"}',64);
INSERT INTO countries VALUES('gq','Guinea Ecuatorial','{"en":"Equatorial Guinea","es":"Guinea Ecuatorial", "ja":"赤道ギニア","fr": "Guinée Équatoriale"}',65);
INSERT INTO countries VALUES('er','Ertra','{"en":"Eritrea","es":"Eritrea", "ja":"エリトリア","fr": "Érythrée"}',66);
INSERT INTO countries VALUES('ee','Eesti','{"en":"Estonia","es":"Estonia", "ja":"エストニア","fr": "Estonie"}',67);
INSERT INTO countries VALUES('et','Ityop''iya','{"en":"Ethiopia","es":"Etiopía", "ja":"エチオピア","fr": "Éthiopie"}',68);
INSERT INTO countries VALUES('fk','Falkland Islands','{"en":"Falkland Islands","es":"Islas Malvinas", "ja":"フォークランド諸島","fr": "Îles Malouines"}',69);
INSERT INTO countries VALUES('fo','Faroe Islands','{"en":"Faroe Islands","es":"Islas Feroe", "ja":"フェロー諸島","fr": "Îles Féroé"}',70);
INSERT INTO countries VALUES('fj','Fiji','{"en":"Fiji","es":"Fiyi", "ja":"フィジー","fr": "Fidji"}',71);
INSERT INTO countries VALUES('fi','Suomi','{"en":"Finland","es":"Finlandia", "ja":"フィンランド","fr": "Finlande"}',72);
INSERT INTO countries VALUES('fr','France','{"en":"France","es":"Francia", "ja":"フランス","fr": "France"}',73);
INSERT INTO countries VALUES('gf','French Guiana','{"en":"French Guiana","es":"Guayana Francesa", "ja":"仏領ギニア","fr": "Guyane française"}',74);
INSERT INTO countries VALUES('pf','French Polynesia','{"en":"French Polynesia","es":"Polinesia Francesa", "ja":"仏領ポリネシア","fr": "Polynésie française"}',75);
INSERT INTO countries VALUES('tf','French Southern Territories','{"en":"French Southern Territories","es":"Territorios Australes Franceses", "ja":"仏領南方地域","fr": "Le Territoire des Terres australes et antarctiques françaises"}',76);
INSERT INTO countries VALUES('ga','Gabon','{"en":"Gabon","es":"Gabón", "ja":"ガボン","fr": "Gabon"}',77);
INSERT INTO countries VALUES('gm','Gambia','{"en":"Gambia","es":"Gambia", "ja":"ガンビア", "fr": "Gambie"}',78);
INSERT INTO countries VALUES('ge','საქართველო','{"en":"Georgia","es":"Georgia", "ja":"グルジア","fr": "Géorgie"}',79);
INSERT INTO countries VALUES('de','Deutschland','{"en":"Germany","es":"Alemania", "ja":"ドイツ","fr": "Allemagne"}',80);
INSERT INTO countries VALUES('gh','Ghana','{"en":"Ghana","es":"Ghana", "ja":"ガーナ","fr": "Ghana"}',81);
INSERT INTO countries VALUES('gi','Gibraltar','{"en":"Gibraltar","es":"Gibraltar", "ja":"ジブラルタル","fr": "Gibraltar"}',82);
INSERT INTO countries VALUES('gr','Ελλάς','{"en":"Greece","es":"Grecia", "ja":"ギリシャ","fr": "Grèce"}',83);
INSERT INTO countries VALUES('gs','South Georgia And The South Sandwich Islands','{"en":"South Georgia And The South Sandwich Islands","es":"Islas Georgia del Sur y Sandwich del Sur", "ja":"サウスジョージア・サウスサンドウィッチ諸島","fr": "Géorgie du Sud et Îles Sandwich du Sud"}',84);
INSERT INTO countries VALUES('gl','Greenland','{"en":"Greenland","es":"Groenlandia", "ja":"グリーンランド","fr": "Groenland"}',85);
INSERT INTO countries VALUES('gd','Grenada','{"en":"Grenada","es":"Granada", "ja":"グラナダ","fr": "Grenade"}',86);
INSERT INTO countries VALUES('gp','Guadeloupe','{"en":"Guadeloupe","es":"Guadalupe", "ja":"グアドループ","fr": "Guadeloupe"}',87);
INSERT INTO countries VALUES('gu','Guam','{"en":"Guam","es":"Guam", "ja":"グアム","fr": "Guam"}',88);
INSERT INTO countries VALUES('gt','Guatemala','{"en":"Guatemala","es":"Guatemala", "ja":"グアテマラ","fr": "Guatemala"}',89);
INSERT INTO countries VALUES('gn','Guinée','{"en":"Guinea","es":"Guinea", "ja":"ギニア","fr": "Guinée"}',90);
INSERT INTO countries VALUES('gw','Guiné-Bissau','{"en":"Guinea-Bissau","es":"Guinea-Bissau", "ja":"ギニアビサウ","fr": "Guinée-Bissau"}',91);
INSERT INTO countries VALUES('gy','Guyana','{"en":"Guyana","es":"Guyana", "ja":"ガイアナ","fr": "Guyane"}',92);
INSERT INTO countries VALUES('ht','Haïti','{"en":"Haiti","es":"Haití", "ja":"ハイチ","fr": "Haïti"}',93);
INSERT INTO countries VALUES('hm','Heard Island and McDonald Islands','{"en":"Heard Island and McDonald Islands","es":"Islas Heard y McDonald", "ja":"ハード島とマクドナルド諸島","fr": "Îles Heard-et-MacDonald"}',94);
INSERT INTO countries VALUES('hn','Honduras','{"en":"Honduras","es":"Honduras", "ja":"ホンジュラス","fr": "Honduras"}',95);
INSERT INTO countries VALUES('hk','Hong Kong','{"en":"Hong Kong","es":"Hong Kong", "ja":"香港","fr": "Hong-Kong"}',96);
INSERT INTO countries VALUES('hu','Magyarország','{"en":"Hungary","es":"Hungría", "ja":"ハンガリー","fr": "Hongrie"}',97);
INSERT INTO countries VALUES('is','Ísland','{"en":"Iceland","es":"Islandia", "ja":"アイスランド","fr": "Islande"}',98);
INSERT INTO countries VALUES('in','India','{"en":"India","es":"India", "ja":"インド","fr": "Inde"}',99);
INSERT INTO countries VALUES('id','Indonesia','{"en":"Indonesia","es":"Indonesia", "ja":"インドネシア","fr": "Indonésie"}',100);
INSERT INTO countries VALUES('ir','ایران','{"en":"Iran","es":"Irán", "ja":"イラン","fr": "Iran"}',101);
INSERT INTO countries VALUES('iq','العراق','{"en":"Iraq","es":"Iraq", "ja":"イラク","fr": "Irak"}',102);
INSERT INTO countries VALUES('ie','Ireland','{"en":"Ireland","es":"Irlanda", "ja":"アイルランド","fr": "Irlande"}',103);
INSERT INTO countries VALUES('il','ישראל','{"en":"Israel","es":"Israel", "ja":"イスラエル","fr": "Israël"}',104);
INSERT INTO countries VALUES('it','Italia','{"en":"Italy","es":"Italia", "ja":"イタリア","fr": "Italie"}',105);
INSERT INTO countries VALUES('jm','Jamaica','{"en":"Jamaica","es":"Jamaica", "ja":"ジャマイカ","fr": "Jamaïque"}',106);
INSERT INTO countries VALUES('jp','日本','{"en":"Japan","es":"Japón", "ja":"日本","fr": "Japon"}',107);
INSERT INTO countries VALUES('jo','الاردن','{"en":"Jordan","es":"Jordania", "ja":"ヨルダン","fr": "Jordanie"}',108);
INSERT INTO countries VALUES('kz','Қазақстан','{"en":"Kazakhstan","es":"Kazajistán", "ja":"カザフスタン","fr": "Kazakhstan"}',109);
INSERT INTO countries VALUES('ke','Kenya','{"en":"Kenya","es":"Kenia", "ja":"ケニア", "fr": "Kenya"}',110);
INSERT INTO countries VALUES('ki','Kiribati','{"en":"Kiribati","es":"Kiribati", "ja":"キリバス","fr": "Kiribati"}',111);
INSERT INTO countries VALUES('kr','한국','{"en":"Korea","es":"Corea del Sur", "ja":"韓国","fr": "Corée"}',112);
INSERT INTO countries VALUES('kw','الكويت','{"en":"Kuwait","es":"Kuwait", "ja":"クウェート","fr": "Koweït"}',113);
INSERT INTO countries VALUES('kg','Кыргызстан','{"en":"Kyrgyzstan","es":"Kirguistán", "ja":"キルギスタン","fr": "Kirghizistan"}',114);
INSERT INTO countries VALUES('la','ນລາວ','{"en":"Laos","es":"Laos", "ja":"ラオス","fr": "Laos}',115);
INSERT INTO countries VALUES('lv','Latvija','{"en":"Latvia","es":"Letonia", "ja":"ラトビア","fr": "Lettonie"}',116);
INSERT INTO countries VALUES('lb','لبنان','{"en":"Lebanon","es":"Líbano", "ja":"レバノン","fr": "Liban"}',117);
INSERT INTO countries VALUES('ls','Lesotho','{"en":"Lesotho","es":"Lesoto", "ja":"レソト","fr": "Lesotho"}',118);
INSERT INTO countries VALUES('lr','Liberia','{"en":"Liberia","es":"Liberia", "ja":"リベリア","fr": "Liberia"}',119);
INSERT INTO countries VALUES('ly','ليبيا','{"en":"Libya","es":"Libia", "ja":"リビア","fr": "Libye"}',120);
INSERT INTO countries VALUES('li','Liechtenstein','{"en":"Liechtenstein","es":"Liechtenstein", "ja":"リヒテンシュタイン","fr": "Liechtenstein"}',121);
INSERT INTO countries VALUES('lt','Lietuva','{"en":"Lithuania","es":"Lituania", "ja":"リトアニア","fr": "Lituanie"}',122);
INSERT INTO countries VALUES('lu','Lëtzebuerg','{"en":"Luxembourg","es":"Luxemburgo", "ja":"ルクセンブルグ","fr": "Luxembourg"}',123);
INSERT INTO countries VALUES('mf','Saint Martin','{"en":"Saint Martin","es":"San Martín", "ja":"セントマーチン","fr": "Saint-Martin"}',124);
INSERT INTO countries VALUES('mo','Macau','{"en":"Macau","es":"Macao", "ja":"マカオ", "fr": "Macao"}',125);
INSERT INTO countries VALUES('mk','Македонија','{"en":"Macedonia","es":"Macedonia", "ja":"マケドニア","fr": "Macédoine"}',126);
INSERT INTO countries VALUES('mg','Madagasikara','{"en":"Madagascar","es":"Madagascar", "ja":"マダガスカル","fr": "Madagascar"}',127);
INSERT INTO countries VALUES('mw','Malawi','{"en":"Malawi","es":"Malaui", "ja":"マラウィ","fr": "Malawi"}',128);
INSERT INTO countries VALUES('my','Malaysia','{"en":"Malaysia","es":"Malasia", "ja":"マレーシア","fr": "Malaisie"}',129);
INSERT INTO countries VALUES('mv','Republic of the Maldives','{"en":"Maldives","es":"Maldivas", "ja":"モルディブ","fr": "Maldives"}',130);
INSERT INTO countries VALUES('ml','Mali','{"en":"Mali","es":"Mali", "ja":"マリ","fr": "Mali"}',131);
INSERT INTO countries VALUES('mt','Malta','{"en":"Malta","es":"Malta", "ja":"マルタ","fr": "Malte"}',132);
INSERT INTO countries VALUES('mh','Marshall Islands','{"en":"Marshall Islands","es":"Islas Marshall", "ja":"マーシャル諸島","fr": "Îles Marshall"}',133);
INSERT INTO countries VALUES('mq','Martinique','{"en":"Martinique","es":"Martinica", "ja":"マルティニーク","fr": "Martinique"}',134);
INSERT INTO countries VALUES('mr','موريتانيا','{"en":"Mauritania","es":"Mauritania", "ja":"モーリタニア","fr": "Mauritanie"}',135);
INSERT INTO countries VALUES('mu','Mauritius','{"en":"Mauritius","es":"Mauricio", "ja":"モーリシャス","fr": "Maurice"}',136);
INSERT INTO countries VALUES('yt','Mayotte','{"en":"Mayotte","es":"Mayotte", "ja":"マヨット","fr": "Mayotte"}',137);
INSERT INTO countries VALUES('mx','México','{"en":"Mexico","es":"México", "ja":"メキシコ","fr": "Mexique"}',138);
INSERT INTO countries VALUES('fm','Micronesia','{"en":"Micronesia","es":"Micronesia", "ja":"ミクロネシア","fr": "Micronésie"}',139);
INSERT INTO countries VALUES('md','Moldova','{"en":"Moldova","es":"Moldavia", "ja":"モルドバ","fr": "Moldavie"}',140);
INSERT INTO countries VALUES('mc','Monaco','{"en":"Monaco","es":"Mónaco", "ja":"モナコ","fr": "Monaco"}',141);
INSERT INTO countries VALUES('mn','Монгол Улс','{"en":"Mongolia","es":"Mongolia", "ja":"モンゴル","fr": "Mongolie"}',142);
INSERT INTO countries VALUES('ms','Montserrat','{"en":"Montserrat","es":"Montserrat", "ja":"モントセラト","fr": "Montserrat"}',143);
INSERT INTO countries VALUES('ma','المغرب','{"en":"Morocco","es":"Marruecos", "ja":"モロッコ","fr": "Maroc"}',144);
INSERT INTO countries VALUES('mz','Moçambique','{"en":"Mozambique","es":"Mozambique", "ja":"モザンビーク","fr": "Mozambique"}',145);
INSERT INTO countries VALUES('mm','Burma','{"en":"Myanmar","es":"Myanmar", "ja":"ミャンマー","fr": "Birmanie"}',146);
INSERT INTO countries VALUES('na','Namibia','{"en":"Namibia","es":"Namibia", "ja":"ナミビア","fr": "Namibie"}',147);
INSERT INTO countries VALUES('nr','Naoero','{"en":"Nauru","es":"Nauru", "ja":"ナウル","fr": "Nauru"}',148);
INSERT INTO countries VALUES('np','नेपाल','{"en":"Nepal","es":"Nepal", "ja":"ネパール","fr": "Népal"}',149);
INSERT INTO countries VALUES('nl','Nederland','{"en":"Netherlands","es":"Países Bajos", "ja":"オランダ","fr": "Pays-Bas"}',150);
INSERT INTO countries VALUES('an','Netherlands Antilles','{"en":"Netherlands Antilles","es":"Antillas Neerlandesas", "ja":"蘭領アンティル","fr": "Antilles néerlandaises"}',151);
INSERT INTO countries VALUES('nc','New Caledonia','{"en":"New Caledonia","es":"Nueva Caledonia", "ja":"ニューカレドニア", "fr": "Nouvelle-Calédonie"}',152);
INSERT INTO countries VALUES('nz','New Zealand','{"en":"New Zealand","es":"Nueva Zelanda", "ja":"ニュージーランド","fr": "Nouvelle-Zélande"}',153);
INSERT INTO countries VALUES('ni','Nicaragua','{"en":"Nicaragua","es":"Nicaragua", "ja":"ニカラグア","fr": "Nicaragua"}',154);
INSERT INTO countries VALUES('ne','Niger','{"en":"Niger","es":"Níger", "ja":"ニジェール","fr": "Niger"}',155);
INSERT INTO countries VALUES('ng','Nigeria','{"en":"Nigeria","es":"Nigeria", "ja":"ナイジェリア","fr": "Nigeria"}',156);
INSERT INTO countries VALUES('nu','Niue','{"en":"Niue","es":"Isla Niue", "ja":"ニウエ","fr": "Niue"}',157);
INSERT INTO countries VALUES('nf','Norfolk Island','{"en":"Norfolk Island","es":"Isla Norfolk", "ja":"ノーフォーク島","fr": "Île Norfolk"}',158);
INSERT INTO countries VALUES('kp','한국','{"en":"North Korea","es":"Corea del Norte", "ja":"北朝鮮","fr": "Corée du Nord"}',159);
INSERT INTO countries VALUES('mp','Northern Mariana Islands','{"en":"Northern Mariana Islands","es":"Islas Marianas del Norte", "ja":"北マリアナ諸島","fr": "Îles Marianne du Nord"}',160);
INSERT INTO countries VALUES('no','Norge','{"en":"Norway","es":"Noruega", "ja":"ノルウェー","fr": "Norvège"}',161);
INSERT INTO countries VALUES('om','عمان','{"en":"Oman","es":"Omán", "ja":"オマーン","fr": "Oman"}',162);
INSERT INTO countries VALUES('pk','پاکستان','{"en":"Pakistan","es":"Pakistán", "ja":"パキスタン","fr": "Pakistan"}',163);
INSERT INTO countries VALUES('pw','Belau','{"en":"Palau","es":"Palau", "ja":"パラオ","fr": "Palaos"}',164);
INSERT INTO countries VALUES('pa','Panamá','{"en":"Panama","es":"Panamá", "ja":"パナマ","fr": "Panama"}',165);
INSERT INTO countries VALUES('pg','Papua New Guinea','{"en":"Papua New Guinea","es":"Papúa Nueva Guinea", "ja":"パプアニューギニア","fr": "Papouasie-Nouvelle-Guinée"}',166);
INSERT INTO countries VALUES('py','Paraguay','{"en":"Paraguay","es":"Paraguay", "ja":"パラグアイ","fr": "Paraguay"}',167);
INSERT INTO countries VALUES('pe','Perú','{"en":"Peru","es":"Perú", "ja":"ペルー","fr": "Pérou"}',168);
INSERT INTO countries VALUES('ph','Pilipinas','{"en":"Philippines","es":"Filipinas", "ja":"フィリピン","fr": "Philippines"}',169);
INSERT INTO countries VALUES('pn','Pitcairn','{"en":"Pitcairn","es":"Pitcairn", "ja":"ピトケアン","fr": "Île Pitcairn"}',170);
INSERT INTO countries VALUES('pl','Polska','{"en":"Poland","es":"Polonia", "ja":"ポーランド","fr": "Pologne"}',171);
INSERT INTO countries VALUES('pt','Portugal','{"en":"Portugal","es":"Portugal", "ja":"ポルトガル","fr": "Portugal"}',172);
INSERT INTO countries VALUES('pr','Puerto Rico','{"en":"Puerto Rico","es":"Puerto Rico", "ja":"プエルトリコ","fr": "Porto Rico"}',173);
INSERT INTO countries VALUES('qa','قطر','{"en":"Qatar","es":"Qatar", "ja":"カタール","fr": "Qatar"}',174);
INSERT INTO countries VALUES('re','Reunion','{"en":"Reunion","es":"Reunión", "ja":"レユニオン","fr": "Réunion"}',175);
INSERT INTO countries VALUES('ro','România','{"en":"Romania","es":"Rumanía", "ja":"ルーマニア","fr": "Roumanie"}',176);
INSERT INTO countries VALUES('ru','Россия','{"en":"Russia","es":"Rusia", "ja":"ロシア","fr": "Russie"}',177);
INSERT INTO countries VALUES('rw','Rwanda','{"en":"Rwanda","es":"Ruanda", "ja":"ルワンダ","fr": "Rwanda"}',178);
INSERT INTO countries VALUES('sh','Saint Helena','{"en":"Saint Helena","es":"Santa Elena", "ja":"セントヘレナ","fr": "Sainte-Hélène"}',179);
INSERT INTO countries VALUES('kn','Saint Kitts and Nevis','{"en":"Saint Kitts and Nevis","es":"San Cristóbal y Nieves", "ja":"セントクリストファー・ネイビス","fr": "Saint-Christophe-et-Niévès"}',180);
INSERT INTO countries VALUES('lc','Saint Lucia','{"en":"Saint Lucia","es":"Santa Lucía", "ja":"セントルシア","fr": "Sainte-Lucie"}',181);
INSERT INTO countries VALUES('pm','Saint Pierre and Miquelon','{"en":"Saint Pierre and Miquelon","es":"San Pedro y Miquelón", "ja":"サンピエール島・ミクロン島","fr": "Saint-Pierre-et-Miquelon"}',182);
INSERT INTO countries VALUES('vc','Saint Vincent and the Grenadines','{"en":"Saint Vincent and the Grenadines","es":"San Vicente y las Granadinas", "ja":"セントビンセント・グレナディーン","fr": "Saint-Vincent-et-les-Grenadines"}',183);
INSERT INTO countries VALUES('ws','Samoa','{"en":"Samoa","es":"Samoa", "ja":"サモア","fr": "Les Samoa"}',184);
INSERT INTO countries VALUES('sm','San Marino','{"en":"San Marino","es":"San Marino", "ja":"サンマリノ","fr": "Saint-Marin"}',185);
INSERT INTO countries VALUES('st','São Tomé and Príncipe','{"en":"São Tomé and Príncipe","es":"Santo Tomé y Príncipe", "ja":"サントメ・プリンシペ","fr": "Sao Tomé-et-Principe"}',186);
INSERT INTO countries VALUES('sa','المملكة العربية السعودية','{"en":"Saudi Arabia","es":"Arabia Saudí", "ja":"サウジアラビア","fr": "Arabie saoudite"}',187);
INSERT INTO countries VALUES('rs','Србија','{"en":"Serbia","es":"Serbia", "ja":"セルビア","fr": "Serbie"}',188);
INSERT INTO countries VALUES('sn','Sénégal','{"en":"Senegal","es":"Senegal", "ja":"セネガル","fr": "Le Sénégal"}',189);
INSERT INTO countries VALUES('sc','Seychelles','{"en":"Seychelles","es":"Seychelles", "ja":"セイシェル","fr": "Seychelles"}',190);
INSERT INTO countries VALUES('sl','Sierra Leone','{"en":"Sierra Leone","es":"Sierra Leona", "ja":"シエラレオネ","fr": "La Sierra Leone"}',191);
INSERT INTO countries VALUES('sg','Singapura','{"en":"Singapore","es":"Singapur", "ja":"シンガポール","fr": "Singapour"}',192);
INSERT INTO countries VALUES('sk','Slovensko','{"en":"Slovakia","es":"Eslovaquia", "ja":"スロバキア","fr": "La Slovaquie"}',193);
INSERT INTO countries VALUES('si','Slovenija','{"en":"Slovenia","es":"Eslovenia", "ja":"スロベニア","fr": "La Slovénie"}',194);
INSERT INTO countries VALUES('sb','Solomon Islands','{"en":"Solomon Islands","es":"Islas Salomón", "ja":"ソロモン諸島", "fr": "îles Salomon"}',195);
INSERT INTO countries VALUES('so','Soomaaliya','{"en":"Somalia","es":"Somalia", "ja":"ソマリア","fr": "La Somalie"}',196);
INSERT INTO countries VALUES('za','South Africa','{"en":"South Africa","es":"Sudáfrica", "ja":"南アメリカ","fr": "L''Afrique du Sud"}',197);
INSERT INTO countries VALUES('es','España','{"en":"Spain","es":"España", "ja":"スペイン","fr": "Espagne"}',198);
INSERT INTO countries VALUES('lk','Sri Lanka','{"en":"Sri Lanka","es":"Sri Lanka", "ja":"スリランカ","fr": "Sri Lanka"}',199);
INSERT INTO countries VALUES('sd','السودان','{"en":"Sudan","es":"Sudán", "ja":"スーダン","fr": "Soudan"}',200);
INSERT INTO countries VALUES('sr','Suriname','{"en":"Suriname","es":"Surinam", "ja":"スリナム","fr": "Le Suriname"}',201);
INSERT INTO countries VALUES('sj','Svalbard and Jan Mayen','{"en":"Svalbard and Jan Mayen","es":"Svalbard y Jan Mayen", "ja":"スヴァールバル諸島およびヤンマイエン島","fr": "Svalbard et Jan Mayen"}',202);
INSERT INTO countries VALUES('sz','Swaziland','{"en":"Swaziland","es":"Suazilandia", "ja":"スワジランド","fr": "Le Swaziland"}',203);
INSERT INTO countries VALUES('se','Sverige','{"en":"Sweden","es":"Suecia", "ja":"スウェーデン","fr": "Suède"}',204);
INSERT INTO countries VALUES('ch','Schweiz','{"en":"Switzerland","es":"Suiza", "ja":"スイス","fr": "Suisse"}',205);
INSERT INTO countries VALUES('sy','سوريا','{"en":"Syria","es":"Siria", "ja":"シリア","fr": "La Syrie"}',206);
INSERT INTO countries VALUES('tw','台灣','{"en":"Taiwan","es":"Taiwán", "ja":"台湾","fr": "Taïwan"}',207);
INSERT INTO countries VALUES('tj','Тоҷикистон','{"en":"Tajikistan","es":"Tayikistán", "ja":"タジキスタン","fr": "Le Tadjikistan"}',208);
INSERT INTO countries VALUES('tz','Tanzania','{"en":"Tanzania","es":"Tanzania", "ja":"タンザニア","fr": "La Tanzanie"}',209);
INSERT INTO countries VALUES('th','ราชอาณาจักรไทย','{"en":"Thailand","es":"Tailandia", "ja":"タイ","fr": "La Thaïlande"}',210);
INSERT INTO countries VALUES('tg','Togo','{"en":"Togo","es":"Togo", "ja":"トーゴ","fr": "Le Togo"}',211);
INSERT INTO countries VALUES('tk','Tokelau','{"en":"Tokelau","es":"Tokelau", "ja":"トケラウ","fr": "Les Tokelau"}',212);
INSERT INTO countries VALUES('to','Tonga','{"en":"Tonga","es":"Tonga", "ja":"トンが","fr": "Les Tonga"}',213);
INSERT INTO countries VALUES('tt','Trinidad and Tobago','{"en":"Trinidad and Tobago","es":"Trinidad y Tobago", "ja":"トリニダード・トバゴ","fr": "La Trinité-et-Tobago"}',214);
INSERT INTO countries VALUES('tn','تونس','{"en":"Tunisia","es":"Túnez", "ja":"チュニジア","fr": "La Tunisie"}',215);
INSERT INTO countries VALUES('tr','Türkiye','{"en":"Turkey","es":"Turquía", "ja":"トルコ","fr": "La Turquie"}',216);
INSERT INTO countries VALUES('tm','Türkmenistan','{"en":"Turkmenistan","es":"Turkmenistán", "ja":"トルクメニスタン","fr": "Le Turkménistan"}',217);
INSERT INTO countries VALUES('tc','Turks and Caicos Islands','{"en":"Turks and Caicos Islands","es":"Islas Turcas y Caicos", "ja":"タークス・カイコス諸島","fr": "Les îles Turques-et-Caïques"}',218);
INSERT INTO countries VALUES('tv','Tuvalu','{"en":"Tuvalu","es":"Tuvalu", "ja":"ツバル","fr": "Les Tuvalu"}',219);
INSERT INTO countries VALUES('ug','Uganda','{"en":"Uganda","es":"Uganda", "ja":"ウガンダ","fr": "L''Ouganda"}',220);
INSERT INTO countries VALUES('ua','Україна','{"en":"Ukraine","es":"Ucrania", "ja":"ウクライナ","fr": "L''Ukraine"}',221);
INSERT INTO countries VALUES('ae','الإمارات العربيّة المتّحدة','{"en":"United Arab Emirates","es":"Emiratos Árabes Unidos", "ja":"アラブ首長国連邦","fr": "Émirats Arabes Unis"}',222);
INSERT INTO countries VALUES('gb','United Kingdom','{"en":"United Kingdom","es":"Reino Unido", "ja":"イギリス","fr": "Royaume-Uni"}',223);
INSERT INTO countries VALUES('us','United States','{"en":"United States","es":"Estados Unidos", "ja":"アメリカ","fr": "États-Unis"}',224);
INSERT INTO countries VALUES('um','United States minor outlying islands','{"en":"United States minor outlying islands","es":"Islas menores alejadas de los Estados Unidos", "ja":"合衆国領有小離島","fr": "Les îles mineures éloignées des États-Unis"}',225);
INSERT INTO countries VALUES('uy','Uruguay','{"en":"Uruguay","es":"Uruguay", "ja":"ウルグアイ","fr": "L''Uruguay"}',226);
INSERT INTO countries VALUES('uz','O''zbekiston','{"en":"Uzbekistan","es":"Uzbekistán", "ja":"ウズベキスタン","fr": "L''Ouzbékistan"}',227);
INSERT INTO countries VALUES('vu','Vanuatu','{"en":"Vanuatu","es":"Vanuatu", "ja":"バヌアツ","fr": "Le Vanuatu"}',228);
INSERT INTO countries VALUES('va','Città del Vaticano','{"en":"Vatican City","es":"Ciudad del Vaticano", "ja":"バチカン市国","fr": "Le Vatican"}',229);
INSERT INTO countries VALUES('ve','Venezuela','{"en":"Venezuela","es":"Venezuela", "ja":"ベネゼエラ","fr": "Le Venezuela"}',230);
INSERT INTO countries VALUES('vn','Việt Nam','{"en":"Vietnam","es":"Vietnam", "ja":"ベトナム","fr": "Le Vietnam"}',231);
INSERT INTO countries VALUES('vg','Virgin Islands, British','{"en":"Virgin Islands, British","es":"Islas Vírgenes Británicas", "ja":"英国領ヴァージン諸島","fr": "Les îles Vierges britanniques"}',232);
INSERT INTO countries VALUES('vi','Virgin Islands, U.S.','{"en":"Virgin Islands, U.S.","es":"Islas Vírgenes de los Estados Unidos", "ja":"米領ヴァージン諸島","fr": "Les îles Vierges des États-Unis"}',233);
INSERT INTO countries VALUES('wf','Wallis and Futuna','{"en":"Wallis and Futuna","es":"Wallis y Futuna", "ja":"ウォリス・フツナ","fr": "Wallis-et-Futuna"}',234);
INSERT INTO countries VALUES('eh','الصحراء الغربية','{"en":"Western Sahara","es":"Sáhara Occidental", "ja":"西サハラ","fr": "Sahara occidental"}',235);
INSERT INTO countries VALUES('ye','اليمن','{"en":"Yemen","es":"Yemen", "ja":"イエメン","fr": "Le Yémen"}',236);
INSERT INTO countries VALUES('zm','Zambia','{"en":"Zambia","es":"Zambia", "ja":"ザンビア","fr": "La Zambie"}',237);
INSERT INTO countries VALUES('zw','Zimbabwe','{"en":"Zimbabwe","es":"Zimbabue", "ja":"ジンバブエ","fr": "Le Zimbabwe"}',238);
INSERT INTO countries VALUES('me','Montenegro','{"en":"Montenegro","es":"Montenegro", "ja":"モンテネグロ","fr": "Monténégro"}',239);
INSERT INTO countries VALUES('xk','Kosovo','{"en":"Kosovo","es":"Kosovo", "ja":"コソボ","fr": "Le Kosovo"}',240);
INSERT INTO countries VALUES('zz','Various countries','{"en":"Various countries","es":"Varios países", "ja":"その他国","fr": "Pays divers"}',241);
INSERT INTO countries VALUES('ap','United States armed forces Pacific','{"en":"United States Armed Forces Pacific","es":"United States armed forces Pacific","fr":"États-Unis Forces armées du Pacifique","ja":"米国太平洋軍"}',242);
INSERT INTO countries VALUES('ax','Åland Islands','{"en":"Aland Islands","es":"Isla Aland","fr":"Åland","ja":"オーランド諸島"}',243);
INSERT INTO countries VALUES('bq','Bonaire, Sint Eustatius and Saba','{"en":"Bonaire Sint Eustatius and Saba","es":"Bonaire, San Eustaquio","fr":"Bonaire, Saint-Eustache et Saba","ja":"ボネール、シント・ユースタティウスおよびサバ"}',244);
INSERT INTO countries VALUES('cw','Curaçao','{"en":"Curacao","es":"Curazao","fr":"Curaçao","ja":"キュラソー　"}',245);
INSERT INTO countries VALUES('eu','European Union','{"en":"European Union","es":"Unión Europea","fr":"Union européenne","ja":"欧州連合"}',246);
INSERT INTO countries VALUES('gg','Bailiwick of Guernsey','{"en":"Guernsey","es":"Guernsey","fr":"Guernesey","ja":"ガーンジー島"}',247);
INSERT INTO countries VALUES('im','Ellan Vannin','{"en":"Isle of Man","es":"Isla de Man","fr":"Île de Man","ja":"マーン島"}',248);
INSERT INTO countries VALUES('je','Bailiwick of Jersey','{"en":"Jersey","es":"Jesery","fr":"Jersey","ja":"Jersey"}',249);
INSERT INTO countries VALUES('ps','فلسطين','{"en":"Palestinian Territory","es":"Territorios Palestinos","fr":"Territoires palestiniens","ja":"パレスチナ自治政府"}',250);
INSERT INTO countries VALUES('ss','South Sudan','{"en":"South Sudan","es":"Sudán del Sur","fr":"Le Soudan du Sud","ja":"南スーダン共和国"}',251);
INSERT INTO countries VALUES('sx','Sint Maarten','{"en":"Sint Maarten","es":"San Martín","fr":"Saint-Martin","ja":"セント・マーティン諸島"}',252);
INSERT INTO countries VALUES('tl','Timor-Leste','{"en":"Timor-Leste","es":"Timor Oriental","fr":"Le Timor oriental","ja":"東ティモール民主共和国"}',253);
