DELETE FROM countries;
INSERT INTO countries VALUES('af','افغانستان','{"en":"Afghanistan","es":"Afganistán","fr":"Afghanistan","ja":"アフガニスタン","zh":"阿富汗","zt":"阿富汗"}',1);
INSERT INTO countries VALUES('al','Shqipëria','{"en":"Albania","es":"Albania","fr":"Albanie","ja":"アルバニア","zh":"阿尔巴尼亚","zt":"阿爾巴尼亞"}',2);
INSERT INTO countries VALUES('dz','الجزائر','{"en":"Algeria","es":"Argelia","fr":"Algérie","ja":"アルジェリア","zh":"阿尔及利亚","zt":"阿爾及利亞"}',3);
INSERT INTO countries VALUES('as','American Samoa','{"en":"American Samoa","es":"Samoa Americana","fr":"Samoa américaines","ja":"米領サモア","zh":"美属萨摩亚","zt":"美屬薩摩亞"}',4);
INSERT INTO countries VALUES('ad','Andorra','{"en":"Andorra","es":"Andorra","fr":"Andorre","ja":"アンドラ","zh":"安道​​尔","zt":"安道​​爾"}',5);
INSERT INTO countries VALUES('ao','Angola','{"en":"Angola","es":"Angola","fr":"Angola","ja":"アンゴラ","zh":"安哥拉","zt":"安哥拉"}',6);
INSERT INTO countries VALUES('ai','Anguilla','{"en":"Anguilla","es":"Anguila","fr":"Anguilla","ja":"アンギラ","zh":"安圭拉","zt":"安圭拉"}',7);
INSERT INTO countries VALUES('aq','Antarctica','{"en":"Antarctica","es":"Antártida","fr":"Antarctique","ja":"南極大陸","zh":"南极洲","zt":"南極洲"}',8);
INSERT INTO countries VALUES('ag','Antigua and Barbuda','{"en":"Antigua and Barbuda","es":"Antigua y Barbuda","fr":"Antigua-et-Barbuda","ja":"アンティグア・バーブーダ","zh":"安提瓜和巴布达","zt":"安提瓜和巴布達"}',9);
INSERT INTO countries VALUES('ar','Argentina','{"en":"Argentina","es":"Argentina","fr":"Argentine","ja":"アルゼンチン","zh":"阿根廷","zt":"阿根廷"}',10);
INSERT INTO countries VALUES('am','Հայաստան','{"en":"Armenia","es":"Armenia","fr":"Arménie","ja":"アルメニア","zh":"亚美尼亚","zt":"亞美尼亞"}',11);
INSERT INTO countries VALUES('aw','Aruba','{"en":"Aruba","es":"Aruba","fr":"Aruba","ja":"アルバ","zh":"阿鲁巴岛","zt":"阿魯巴島"}',12);
INSERT INTO countries VALUES('au','Australia','{"en":"Australia","es":"Australia","fr":"Australie","ja":"オーストラリア","zh":"澳大利亚","zt":"澳大利亞"}',13);
INSERT INTO countries VALUES('at','Österreich','{"en":"Austria","es":"Austria","fr":"Autriche","ja":"オーストリア","zh":"奥地利","zt":"奧地利"}',14);
INSERT INTO countries VALUES('az','Azərbaycan','{"en":"Azerbaijan","es":"Azerbaiyán","fr":"Azerbaïdjan","ja":"アゼルバイジャン","zh":"阿塞拜疆","zt":"阿塞拜疆"}',15);
INSERT INTO countries VALUES('bs','Bahamas','{"en":"Bahamas","es":"Bahamas","fr":"Bahamas","ja":"バハマ","zh":"巴哈马","zt":"巴哈馬"}',16);
INSERT INTO countries VALUES('bh','البحرين','{"en":"Bahrain","es":"Bahréin","fr":"Bahreïn","ja":"バーレーン","zh":"巴林","zt":"巴林"}',17);
INSERT INTO countries VALUES('bd','বাংলাদেশ','{"en":"Bangladesh","es":"Bangladesh","fr":"Bangladesh","ja":"バングラディッシュ","zh":"孟加拉国","zt":"孟加拉國"}',18);
INSERT INTO countries VALUES('bb','Barbados','{"en":"Barbados","es":"Barbados","fr":"Barbade","ja":"バルバドス","zh":"巴巴多斯","zt":"巴巴多斯"}',19);
INSERT INTO countries VALUES('by','Белару́сь','{"en":"Belarus","es":"Bielorrusia","fr":"Biélorussie","ja":"ベラルーシ","zh":"白俄罗斯","zt":"白俄羅斯"}',20);
INSERT INTO countries VALUES('be','België','{"en":"Belgium","es":"Bélgica","fr":"Belgique","ja":"ベルギー","zh":"比利时","zt":"比利時"}',21);
INSERT INTO countries VALUES('bz','Belize','{"en":"Belize","es":"Belice","fr":"Belize","ja":"ベリーズ","zh":"伯利兹","zt":"伯利茲"}',22);
INSERT INTO countries VALUES('bj','Bénin','{"en":"Benin","es":"Benín","fr":"Bénin","ja":"ベナン","zh":"贝宁","zt":"貝寧"}',23);
INSERT INTO countries VALUES('bm','Bermuda','{"en":"Bermuda","es":"Bermudas","fr":"Bermudes","ja":"バミューダ諸島","zh":"百慕大","zt":"百慕大"}',24);
INSERT INTO countries VALUES('bt','འབྲུག་ཡུལ','{"en":"Bhutan","es":"Bután","fr":"Bhoutan","ja":"ブータン","zh":"不丹","zt":"不丹"}',25);
INSERT INTO countries VALUES('bo','Bolivia','{"en":"Bolivia","es":"Bolivia","fr":"Bolivie","ja":"ボリビア","zh":"玻利维亚","zt":"玻利維亞"}',26);
INSERT INTO countries VALUES('ba','Bosna i Hercegovina','{"en":"Bosnia and Herzegovina","es":"Bosnia-Herzegovina","fr":"Bosnie-Herzégovine","ja":"ボスニア・ヘルツェゴビナ","zh":"波斯尼亚和黑塞哥维那","zt":"波斯尼亞和黑塞哥維那"}',27);
INSERT INTO countries VALUES('bw','Botswana','{"en":"Botswana","es":"Botsuana","fr":"Botswana","ja":"ボツワナ","zh":"博茨瓦纳","zt":"博茨瓦納"}',28);
INSERT INTO countries VALUES('bv','Bouvet Island','{"en":"Bouvet Island","es":"Isla Bouvet","fr":"Île Bouvet","ja":"ブーベ島","zh":"布维岛","zt":"布維島"}',29);
INSERT INTO countries VALUES('br','Brasil','{"en":"Brazil","es":"Brasil","fr":"Brésil","ja":"ブラジル","zh":"巴西","zt":"巴西"}',30);
INSERT INTO countries VALUES('io','British Indian Ocean Territory','{"en":"British Indian Ocean Territory","es":"Territorio Británico del Océano Índico","fr":"Territoire britannique de l\u0027océan indien","ja":"イギリス領インド洋地域","zh":"英属印度洋领地","zt":"英屬印度洋領地"}',31);
INSERT INTO countries VALUES('bn','Brunei Darussalam','{"en":"Brunei","es":"Brunéi","fr":"Brunei","ja":"ブルネイ","zh":"文莱","zt":"文萊"}',32);
INSERT INTO countries VALUES('bg','България','{"en":"Bulgaria","es":"Bulgaria","fr":"Bulgarie","ja":"ブルガリア","zh":"保加利亚","zt":"保加利亞"}',33);
INSERT INTO countries VALUES('bf','Burkina Faso','{"en":"Burkina Faso","es":"Burkina Faso","fr":"Burkina Faso","ja":"ブルキナファソ","zh":"布基纳法索","zt":"布基納法索"}',34);
INSERT INTO countries VALUES('bi','Uburundi','{"en":"Burundi","es":"Burundi","fr":"Burundi","ja":"ブルンジ","zh":"布隆迪","zt":"布隆迪"}',35);
INSERT INTO countries VALUES('kh','Kampuchea','{"en":"Cambodia","es":"Camboya","fr":"Cambodge","ja":"カンボジア","zh":"柬埔寨","zt":"柬埔寨"}',36);
INSERT INTO countries VALUES('cm','Cameroun','{"en":"Cameroon","es":"Camerún","fr":"Cameroun","ja":"カメルーン","zh":"喀麦隆","zt":"喀麥隆"}',37);
INSERT INTO countries VALUES('ca','Canada','{"en":"Canada","es":"Canadá","fr":"Canada","ja":"カナダ","zh":"加拿大","zt":"加拿大"}',38);
INSERT INTO countries VALUES('cv','Cabo Verde','{"en":"Cape Verde","es":"Cabo Verde","fr":"Cap-Vert","ja":"カーボヴェルデ","zh":"佛得角","zt":"佛得角"}',39);
INSERT INTO countries VALUES('ky','Cayman Islands','{"en":"Cayman Islands","es":"Islas Caimán","fr":"Îles Caïman","ja":"ケイマン諸島","zh":"开曼群岛","zt":"開曼群島"}',40);
INSERT INTO countries VALUES('cf','République Centrafricaine','{"en":"Central African Republic","es":"República Centroafricana","fr":"République Centrafricaine","ja":"中央アフリカ共和国","zh":"中非共和国","zt":"中非共和國"}',41);
INSERT INTO countries VALUES('td','Tchad','{"en":"Chad","es":"Chad","fr":"Le Tchad","ja":"チャド","zh":"乍得","zt":"乍得"}',42);
INSERT INTO countries VALUES('cl','Chile','{"en":"Chile","es":"Chile","fr":"Chili","ja":"チリ","zh":"智利","zt":"智利"}',43);
INSERT INTO countries VALUES('cn','中国','{"en":"China","es":"China","fr":"Chine","ja":"中国","zh":"中国","zt":"中國"}',44);
INSERT INTO countries VALUES('cx','Christmas Island','{"en":"Christmas Island","es":"Isla Christmas","fr":"Île Christmas","ja":"クリスマス島","zh":"圣诞岛","zt":"聖誕島"}',45);
INSERT INTO countries VALUES('cc','Cocos Islands','{"en":"Cocos Islands","es":"Islas Cocos","fr":"Îles Cocos","ja":"ココス諸島","zh":"科科斯群岛","zt":"科科斯群島"}',46);
INSERT INTO countries VALUES('co','Colombia','{"en":"Colombia","es":"Colombia","fr":"Colombie","ja":"コロンビア","zh":"哥伦比亚","zt":"哥倫比亞"}',47);
INSERT INTO countries VALUES('km','Comores','{"en":"Comoros","es":"Comoras","fr":"Comores","ja":"コモロ","zh":"科摩罗","zt":"科摩羅"}',48);
INSERT INTO countries VALUES('cg','Republic Of Congo','{"en":"Republic Of Congo","es":"Congo","fr":"République du Congo","ja":"コンゴ共和国","zh":"刚果共和国","zt":"剛果共和國"}',49);
INSERT INTO countries VALUES('cd','The Democratic Republic Of The Congo','{"en":"The Democratic Republic Of The Congo","es":"República Democrática del Congo","fr":"La République Démocratique du Congo","ja":"コンゴ民主共和国","zh":"民主刚果共和国","zt":"民主剛果共和國"}',50);
INSERT INTO countries VALUES('ck','Cook Islands','{"en":"Cook Islands","es":"Islas Cook","fr":"Îles Cook","ja":"クック諸島","zh":"库克群岛","zt":"庫克群島"}',51);
INSERT INTO countries VALUES('cr','Costa Rica','{"en":"Costa Rica","es":"Costa Rica","fr":"Costa Rica","ja":"コスタリカ","zh":"哥斯达黎加","zt":"哥斯達黎加"}',52);
INSERT INTO countries VALUES('ci','Côte d''Ivoire','{"en":"Côte d\u0027Ivoire","es":"Costa de Marfil","fr":"Côte d\u0027Ivoire","ja":"コートジボワール","zh":"科特迪瓦","zt":"科特迪瓦"}',53);
INSERT INTO countries VALUES('hr','Hrvatska','{"en":"Croatia","es":"Croacia","fr":"Croatie","ja":"クロアチア","zh":"克罗地亚","zt":"克羅地亞"}',54);
INSERT INTO countries VALUES('cu','Cuba','{"en":"Cuba","es":"Cuba","fr":"Cuba","ja":"キューバ","zh":"古巴","zt":"古巴"}',55);
INSERT INTO countries VALUES('cy','Κυπρος','{"en":"Cyprus","es":"Chipre","fr":"Chypre","ja":"キプロス","zh":"塞浦路斯","zt":"塞浦路斯"}',56);
INSERT INTO countries VALUES('cz','Česko','{"en":"Czech Republic","es":"República Checa","fr":"République tchèque","ja":"チェコ","zh":"捷克共和国","zt":"捷克"}',57);
INSERT INTO countries VALUES('dk','Danmark','{"en":"Denmark","es":"Dinamarca","fr":"Danemark","ja":"デンマーク","zh":"丹麦","zt":"丹麥"}',58);
INSERT INTO countries VALUES('dj','Djibouti','{"en":"Djibouti","es":"Yibuti","fr":"Djibouti","ja":"ジブチ","zh":"吉布提","zt":"吉布提"}',59);
INSERT INTO countries VALUES('dm','Dominica','{"en":"Dominica","es":"Dominica","fr":"Dominique","ja":"ドミニカ国","zh":"多米尼加","zt":"多米尼加"}',60);
INSERT INTO countries VALUES('do','Dominican Republic','{"en":"Dominican Republic","es":"República Dominicana","fr":"République Dominicaine","ja":"ドミニカ共和国","zh":"多明尼加共和国","zt":"多明尼加共和國"}',61);
INSERT INTO countries VALUES('ec','Ecuador','{"en":"Ecuador","es":"Ecuador","fr":"Équateur","ja":"エクアドル","zh":"厄瓜多尔","zt":"厄瓜多爾"}',62);
INSERT INTO countries VALUES('eg','مصر','{"en":"Egypt","es":"Egipto","fr":"Égypte","ja":"エジプト","zh":"埃及","zt":"埃及"}',63);
INSERT INTO countries VALUES('sv','El Salvador','{"en":"El Salvador","es":"El Salvador","fr":"Le Salvador","ja":"エルサルバドル","zh":"萨尔瓦多","zt":"薩爾瓦多"}',64);
INSERT INTO countries VALUES('gq','Guinea Ecuatorial','{"en":"Equatorial Guinea","es":"Guinea Ecuatorial","fr":"Guinée Équatoriale","ja":"赤道ギニア","zh":"赤道几内亚","zt":"赤道幾內亞"}',65);
INSERT INTO countries VALUES('er','Ertra','{"en":"Eritrea","es":"Eritrea","fr":"Érythrée","ja":"エリトリア","zh":"厄立特里亚","zt":"厄立特里亞"}',66);
INSERT INTO countries VALUES('ee','Eesti','{"en":"Estonia","es":"Estonia","fr":"Estonie","ja":"エストニア","zh":"爱沙尼亚","zt":"愛沙尼亞"}',67);
INSERT INTO countries VALUES('et','Ityop''iya','{"en":"Ethiopia","es":"Etiopía","fr":"Éthiopie","ja":"エチオピア","zh":"埃塞俄比亚","zt":"埃塞俄比亞"}',68);
INSERT INTO countries VALUES('fk','Falkland Islands','{"en":"Falkland Islands","es":"Islas Malvinas","fr":"Îles Malouines","ja":"フォークランド諸島","zh":"福克兰群岛","zt":"福克蘭群島"}',69);
INSERT INTO countries VALUES('fo','Faroe Islands','{"en":"Faroe Islands","es":"Islas Feroe","fr":"Îles Féroé","ja":"フェロー諸島","zh":"法罗群岛","zt":"法羅群島"}',70);
INSERT INTO countries VALUES('fj','Fiji','{"en":"Fiji","es":"Fiyi","fr":"Fidji","ja":"フィジー","zh":"斐济","zt":"斐濟"}',71);
INSERT INTO countries VALUES('fi','Suomi','{"en":"Finland","es":"Finlandia","fr":"Finlande","ja":"フィンランド","zh":"芬兰","zt":"芬蘭"}',72);
INSERT INTO countries VALUES('fr','France','{"en":"France","es":"Francia","fr":"France","ja":"フランス","zh":"法国","zt":"法國"}',73);
INSERT INTO countries VALUES('gf','French Guiana','{"en":"French Guiana","es":"Guayana Francesa","fr":"Guyane française","ja":"フランス領ギアナ","zh":"法属圭亚那","zt":"法屬圭亞那"}',74);
INSERT INTO countries VALUES('pf','French Polynesia','{"en":"French Polynesia","es":"Polinesia Francesa","fr":"Polynésie française","ja":"フランス領ポリネシア","zh":"法属波利尼西亚","zt":"法屬波利尼西亞"}',75);
INSERT INTO countries VALUES('tf','French Southern Territories','{"en":"French Southern Territories","es":"Territorios Australes Franceses","fr":"Le Territoire des Terres australes et antarctiques françaises","ja":"フランス領南方・南極地域","zh":"法国南部领土","zt":"法國南部領土"}',76);
INSERT INTO countries VALUES('ga','Gabon','{"en":"Gabon","es":"Gabón","fr":"Gabon","ja":"ガボン","zh":"加蓬","zt":"加蓬"}',77);
INSERT INTO countries VALUES('gm','Gambia','{"en":"Gambia","es":"Gambia","fr":"Gambie","ja":"ガンビア","zh":"冈比亚","zt":"岡比亞"}',78);
INSERT INTO countries VALUES('ge','საქართველო','{"en":"Georgia","es":"Georgia","fr":"Géorgie","ja":"グルジア","zh":"格鲁吉亚","zt":"格魯吉亞"}',79);
INSERT INTO countries VALUES('de','Deutschland','{"en":"Germany","es":"Alemania","fr":"Allemagne","ja":"ドイツ","zh":"德国","zt":"德國"}',80);
INSERT INTO countries VALUES('gh','Ghana','{"en":"Ghana","es":"Ghana","fr":"Ghana","ja":"ガーナ","zh":"加纳","zt":"加納"}',81);
INSERT INTO countries VALUES('gi','Gibraltar','{"en":"Gibraltar","es":"Gibraltar","fr":"Gibraltar","ja":"ジブラルタル","zh":"直布罗陀","zt":"直布羅陀"}',82);
INSERT INTO countries VALUES('gr','Ελλάς','{"en":"Greece","es":"Grecia","fr":"Grèce","ja":"ギリシャ","zh":"希腊","zt":"希臘"}',83);
INSERT INTO countries VALUES('gs','South Georgia And The South Sandwich Islands','{"en":"South Georgia And The South Sandwich Islands","es":"Islas Georgia del Sur y Sandwich del Sur","fr":"Géorgie du Sud et Îles Sandwich du Sud","ja":"サウスジョージア・サウスサンドウィッチ諸島","zh":"南乔治亚岛和南桑威奇群岛","zt":"南喬治亞島和南桑威奇群島"}',84);
INSERT INTO countries VALUES('gl','Greenland','{"en":"Greenland","es":"Groenlandia","fr":"Groenland","ja":"グリーンランド","zh":"格陵兰","zt":"格陵蘭"}',85);
INSERT INTO countries VALUES('gd','Grenada','{"en":"Grenada","es":"Granada","fr":"Grenade","ja":"グレナダ","zh":"格林纳达","zt":"格林納達"}',86);
INSERT INTO countries VALUES('gp','Guadeloupe','{"en":"Guadeloupe","es":"Guadalupe","fr":"Guadeloupe","ja":"グアドループ","zh":"瓜德罗普岛","zt":"瓜德羅普島"}',87);
INSERT INTO countries VALUES('gu','Guam','{"en":"Guam","es":"Guam","fr":"Guam","ja":"グアム","zh":"关岛","zt":"關島"}',88);
INSERT INTO countries VALUES('gt','Guatemala','{"en":"Guatemala","es":"Guatemala","fr":"Guatemala","ja":"グアテマラ","zh":"危地马拉","zt":"危地馬拉"}',89);
INSERT INTO countries VALUES('gn','Guinée','{"en":"Guinea","es":"Guinea","fr":"Guinée","ja":"ギニア","zh":"几内亚","zt":"幾內亞"}',90);
INSERT INTO countries VALUES('gw','Guiné-Bissau','{"en":"Guinea-Bissau","es":"Guinea-Bissau","fr":"Guinée-Bissau","ja":"ギニアビサウ","zh":"几内亚比绍","zt":"幾內亞比紹"}',91);
INSERT INTO countries VALUES('gy','Guyana','{"en":"Guyana","es":"Guyana","fr":"Guyane","ja":"ガイアナ","zh":"圭亚那","zt":"圭亞那"}',92);
INSERT INTO countries VALUES('ht','Haïti','{"en":"Haiti","es":"Haití","fr":"Haïti","ja":"ハイチ","zh":"海地","zt":"海地"}',93);
INSERT INTO countries VALUES('hm','Heard Island and McDonald Islands','{"en":"Heard Island and McDonald Islands","es":"Islas Heard y McDonald","fr":"Îles Heard-et-MacDonald","ja":"ハード島とマクドナルド諸島","zh":"赫德岛和麦当劳群岛","zt":"赫德島和麥當勞群島"}',94);
INSERT INTO countries VALUES('hn','Honduras','{"en":"Honduras","es":"Honduras","fr":"Honduras","ja":"ホンジュラス","zh":"洪都拉斯","zt":"洪都拉斯"}',95);
INSERT INTO countries VALUES('hk','Hong Kong','{"en":"Hong Kong","es":"Hong Kong","fr":"Hong-Kong","ja":"香港","zh":"香港","zt":"香港"}',96);
INSERT INTO countries VALUES('hu','Magyarország','{"en":"Hungary","es":"Hungría","fr":"Hongrie","ja":"ハンガリー","zh":"匈牙利","zt":"匈牙利"}',97);
INSERT INTO countries VALUES('is','Ísland','{"en":"Iceland","es":"Islandia","fr":"Islande","ja":"アイスランド","zh":"冰岛","zt":"冰島"}',98);
INSERT INTO countries VALUES('in','India','{"en":"India","es":"India","fr":"Inde","ja":"インド","zh":"印度","zt":"印度"}',99);
INSERT INTO countries VALUES('id','Indonesia','{"en":"Indonesia","es":"Indonesia","fr":"Indonésie","ja":"インドネシア","zh":"印尼","zt":"印尼"}',100);
INSERT INTO countries VALUES('ir','ایران','{"en":"Iran","es":"Irán","fr":"Iran","ja":"イラン","zh":"伊朗","zt":"伊朗"}',101);
INSERT INTO countries VALUES('iq','العراق','{"en":"Iraq","es":"Iraq","fr":"Irak","ja":"イラク","zh":"伊拉克","zt":"伊拉克"}',102);
INSERT INTO countries VALUES('ie','Ireland','{"en":"Ireland","es":"Irlanda","fr":"Irlande","ja":"アイルランド","zh":"爱尔兰","zt":"愛爾蘭"}',103);
INSERT INTO countries VALUES('il','ישראל','{"en":"Israel","es":"Israel","fr":"Israël","ja":"イスラエル","zh":"以色列","zt":"以色列"}',104);
INSERT INTO countries VALUES('it','Italia','{"en":"Italy","es":"Italia","fr":"Italie","ja":"イタリア","zh":"意大利","zt":"意大利"}',105);
INSERT INTO countries VALUES('jm','Jamaica','{"en":"Jamaica","es":"Jamaica","fr":"Jamaïque","ja":"ジャマイカ","zh":"牙买加","zt":"牙買加"}',106);
INSERT INTO countries VALUES('jp','日本','{"en":"Japan","es":"Japón","fr":"Japon","ja":"日本","zh":"日本","zt":"日本"}',107);
INSERT INTO countries VALUES('jo','الاردن','{"en":"Jordan","es":"Jordania","fr":"Jordanie","ja":"ヨルダン","zh":"约旦","zt":"約旦"}',108);
INSERT INTO countries VALUES('kz','Қазақстан','{"en":"Kazakhstan","es":"Kazajistán","fr":"Kazakhstan","ja":"カザフスタン","zh":"哈萨克斯坦","zt":"哈薩克斯坦"}',109);
INSERT INTO countries VALUES('ke','Kenya','{"en":"Kenya","es":"Kenia","fr":"Kenya","ja":"ケニア","zh":"肯尼亚","zt":"肯尼亞"}',110);
INSERT INTO countries VALUES('ki','Kiribati','{"en":"Kiribati","es":"Kiribati","fr":"Kiribati","ja":"キリバス","zh":"基里巴斯","zt":"基里巴斯"}',111);
INSERT INTO countries VALUES('kr','한국','{"en":"Korea","es":"Corea del Sur","fr":"Corée","ja":"韓国","zh":"韩国","zt":"韓國"}',112);
INSERT INTO countries VALUES('kw','الكويت','{"en":"Kuwait","es":"Kuwait","fr":"Koweït","ja":"クウェート","zh":"科威特","zt":"科威特"}',113);
INSERT INTO countries VALUES('kg','Кыргызстан','{"en":"Kyrgyzstan","es":"Kirguistán","fr":"Kirghizistan","ja":"キルギスタン","zh":"吉尔吉斯斯坦","zt":"吉爾吉斯斯坦"}',114);
INSERT INTO countries VALUES('la','ນລາວ','{"en":"Laos","es":"Laos","fr":"Laos","ja":"ラオス","zh":"老挝","zt":"老撾"}',115);
INSERT INTO countries VALUES('lv','Latvija','{"en":"Latvia","es":"Letonia","fr":"Lettonie","ja":"ラトビア","zh":"拉脱维亚","zt":"拉脫維亞"}',116);
INSERT INTO countries VALUES('lb','لبنان','{"en":"Lebanon","es":"Líbano","fr":"Liban","ja":"レバノン","zh":"黎巴嫩","zt":"黎巴嫩"}',117);
INSERT INTO countries VALUES('ls','Lesotho','{"en":"Lesotho","es":"Lesoto","fr":"Lesotho","ja":"レソト","zh":"莱索托","zt":"萊索托"}',118);
INSERT INTO countries VALUES('lr','Liberia','{"en":"Liberia","es":"Liberia","fr":"Liberia","ja":"リベリア","zh":"利比里亚","zt":"利比里亞"}',119);
INSERT INTO countries VALUES('ly','ليبيا','{"en":"Libya","es":"Libia","fr":"Libye","ja":"リビア","zh":"利比亚","zt":"利比亞"}',120);
INSERT INTO countries VALUES('li','Liechtenstein','{"en":"Liechtenstein","es":"Liechtenstein","fr":"Liechtenstein","ja":"リヒテンシュタイン","zh":"列支敦士登","zt":"列支敦士登"}',121);
INSERT INTO countries VALUES('lt','Lietuva','{"en":"Lithuania","es":"Lituania","fr":"Lituanie","ja":"リトアニア","zh":"立陶宛","zt":"立陶宛"}',122);
INSERT INTO countries VALUES('lu','Lëtzebuerg','{"en":"Luxembourg","es":"Luxemburgo","fr":"Luxembourg","ja":"ルクセンブルグ","zh":"卢森堡","zt":"盧森堡"}',123);
INSERT INTO countries VALUES('mf','Saint Martin','{"en":"Saint Martin","es":"San Martín","fr":"Saint-Martin","ja":"セント・マーチン島","zh":"圣马丁","zt":"聖馬丁"}',124);
INSERT INTO countries VALUES('mo','Macau','{"en":"Macau","es":"Macao","fr":"Macao","ja":"マカオ","zh":"澳门","zt":"澳門"}',125);
INSERT INTO countries VALUES('mk','Македонија','{"en":"Macedonia","es":"Macedonia","fr":"Macédoine","ja":"マケドニア共和国","zh":"马其顿","zt":"馬其頓"}',126);
INSERT INTO countries VALUES('mg','Madagasikara','{"en":"Madagascar","es":"Madagascar","fr":"Madagascar","ja":"マダガスカル","zh":"马达加斯加","zt":"馬達加斯加"}',127);
INSERT INTO countries VALUES('mw','Malawi','{"en":"Malawi","es":"Malaui","fr":"Malawi","ja":"マラウイ","zh":"马拉维","zt":"馬拉維"}',128);
INSERT INTO countries VALUES('my','Malaysia','{"en":"Malaysia","es":"Malasia","fr":"Malaisie","ja":"マレーシア","zh":"马来西亚","zt":"馬來西亞"}',129);
INSERT INTO countries VALUES('mv','Republic of the Maldives','{"en":"Maldives","es":"Maldivas","fr":"Maldives","ja":"モルディブ","zh":"马尔代夫","zt":"馬爾代夫"}',130);
INSERT INTO countries VALUES('ml','Mali','{"en":"Mali","es":"Mali","fr":"Mali","ja":"マリ共和国","zh":"马里","zt":"馬里"}',131);
INSERT INTO countries VALUES('mt','Malta','{"en":"Malta","es":"Malta","fr":"Malte","ja":"マルタ","zh":"马耳他","zt":"馬耳他"}',132);
INSERT INTO countries VALUES('mh','Marshall Islands','{"en":"Marshall Islands","es":"Islas Marshall","fr":"Îles Marshall","ja":"マーシャル諸島","zh":"马绍尔群岛","zt":"馬紹爾群島"}',133);
INSERT INTO countries VALUES('mq','Martinique','{"en":"Martinique","es":"Martinica","fr":"Martinique","ja":"マルティニーク","zh":"马提尼克","zt":"馬提尼克"}',134);
INSERT INTO countries VALUES('mr','موريتانيا','{"en":"Mauritania","es":"Mauritania","fr":"Mauritanie","ja":"モーリタニア","zh":"毛里塔尼亚","zt":"毛里塔尼亞"}',135);
INSERT INTO countries VALUES('mu','Mauritius','{"en":"Mauritius","es":"Mauricio","fr":"Maurice","ja":"モーリシャス","zh":"毛里求斯","zt":"毛里求斯"}',136);
INSERT INTO countries VALUES('yt','Mayotte','{"en":"Mayotte","es":"Mayotte","fr":"Mayotte","ja":"マヨット","zh":"马约特","zt":"馬約特"}',137);
INSERT INTO countries VALUES('mx','México','{"en":"Mexico","es":"México","fr":"Mexique","ja":"メキシコ","zh":"墨西哥","zt":"墨西哥"}',138);
INSERT INTO countries VALUES('fm','Micronesia','{"en":"Micronesia","es":"Micronesia","fr":"Micronésie","ja":"ミクロネシア","zh":"密克罗尼西亚","zt":"密克羅尼西亞"}',139);
INSERT INTO countries VALUES('md','Moldova','{"en":"Moldova","es":"Moldavia","fr":"Moldavie","ja":"モルドバ","zh":"摩尔多瓦","zt":"摩爾多瓦"}',140);
INSERT INTO countries VALUES('mc','Monaco','{"en":"Monaco","es":"Mónaco","fr":"Monaco","ja":"モナコ","zh":"摩纳哥","zt":"摩納哥"}',141);
INSERT INTO countries VALUES('mn','Монгол Улс','{"en":"Mongolia","es":"Mongolia","fr":"Mongolie","ja":"モンゴル","zh":"蒙古","zt":"蒙古"}',142);
INSERT INTO countries VALUES('ms','Montserrat','{"en":"Montserrat","es":"Montserrat","fr":"Montserrat","ja":"モントセラト","zh":"蒙特塞拉特","zt":"蒙特塞拉特"}',143);
INSERT INTO countries VALUES('ma','المغرب','{"en":"Morocco","es":"Marruecos","fr":"Maroc","ja":"モロッコ","zh":"摩洛哥","zt":"摩洛哥"}',144);
INSERT INTO countries VALUES('mz','Moçambique','{"en":"Mozambique","es":"Mozambique","fr":"Mozambique","ja":"モザンビーク","zh":"莫桑比克","zt":"莫桑比克"}',145);
INSERT INTO countries VALUES('mm','Burma','{"en":"Myanmar","es":"Myanmar","fr":"Birmanie","ja":"ミャンマー","zh":"缅甸","zt":"緬甸"}',146);
INSERT INTO countries VALUES('na','Namibia','{"en":"Namibia","es":"Namibia","fr":"Namibie","ja":"ナミビア","zh":"纳米比亚","zt":"納米比亞"}',147);
INSERT INTO countries VALUES('nr','Naoero','{"en":"Nauru","es":"Nauru","fr":"Nauru","ja":"ナウル","zh":"瑙鲁","zt":"瑙魯"}',148);
INSERT INTO countries VALUES('np','नेपाल','{"en":"Nepal","es":"Nepal","fr":"Népal","ja":"ネパール","zh":"尼泊尔","zt":"尼泊爾"}',149);
INSERT INTO countries VALUES('nl','Nederland','{"en":"Netherlands","es":"Países Bajos","fr":"Pays-Bas","ja":"オランダ","zh":"荷兰","zt":"荷蘭"}',150);
INSERT INTO countries VALUES('an','Netherlands Antilles','{"en":"Netherlands Antilles","es":"Antillas Neerlandesas","fr":"Antilles néerlandaises","ja":"オランダ領アンティル","zh":"荷属安的列斯","zt":"荷屬安的列斯"}',151);
INSERT INTO countries VALUES('nc','New Caledonia','{"en":"New Caledonia","es":"Nueva Caledonia","fr":"Nouvelle-Calédonie","ja":"ニューカレドニア","zh":"新喀里多尼亚","zt":"新喀裡多尼亞"}',152);
INSERT INTO countries VALUES('nz','New Zealand','{"en":"New Zealand","es":"Nueva Zelanda","fr":"Nouvelle-Zélande","ja":"ニュージーランド","zh":"新西兰","zt":"新西蘭"}',153);
INSERT INTO countries VALUES('ni','Nicaragua','{"en":"Nicaragua","es":"Nicaragua","fr":"Nicaragua","ja":"ニカラグア","zh":"尼加拉瓜","zt":"尼加拉瓜"}',154);
INSERT INTO countries VALUES('ne','Niger','{"en":"Niger","es":"Níger","fr":"Niger","ja":"ニジェール","zh":"尼日尔","zt":"尼日爾"}',155);
INSERT INTO countries VALUES('ng','Nigeria','{"en":"Nigeria","es":"Nigeria","fr":"Nigeria","ja":"ナイジェリア","zh":"尼日利亚","zt":"尼日利亞"}',156);
INSERT INTO countries VALUES('nu','Niue','{"en":"Niue","es":"Isla Niue","fr":"Niue","ja":"ニウエ","zh":"纽埃","zt":"紐埃"}',157);
INSERT INTO countries VALUES('nf','Norfolk Island','{"en":"Norfolk Island","es":"Isla Norfolk","fr":"Île Norfolk","ja":"ノーフォーク島","zh":"诺福克岛","zt":"諾福克島"}',158);
INSERT INTO countries VALUES('kp','한국','{"en":"North Korea","es":"Corea del Norte","fr":"Corée du Nord","ja":"朝鮮民主主義人民共和国","zh":"北朝鲜","zt":"北韓"}',159);
INSERT INTO countries VALUES('mp','Northern Mariana Islands','{"en":"Northern Mariana Islands","es":"Islas Marianas del Norte","fr":"Îles Marianne du Nord","ja":"北マリアナ諸島","zh":"北马里亚纳群岛","zt":"北馬里亞納群島"}',160);
INSERT INTO countries VALUES('no','Norge','{"en":"Norway","es":"Noruega","fr":"Norvège","ja":"ノルウェー","zh":"挪威","zt":"挪威"}',161);
INSERT INTO countries VALUES('om','عمان','{"en":"Oman","es":"Omán","fr":"Oman","ja":"オマーン","zh":"阿曼","zt":"阿曼"}',162);
INSERT INTO countries VALUES('pk','پاکستان','{"en":"Pakistan","es":"Pakistán","fr":"Pakistan","ja":"パキスタン","zh":"巴基斯坦","zt":"巴基斯坦"}',163);
INSERT INTO countries VALUES('pw','Belau','{"en":"Palau","es":"Palau","fr":"Palaos","ja":"パラオ","zh":"帕劳","zt":"帕勞"}',164);
INSERT INTO countries VALUES('pa','Panamá','{"en":"Panama","es":"Panamá","fr":"Panama","ja":"パナマ","zh":"巴拿马","zt":"巴拿馬"}',165);
INSERT INTO countries VALUES('pg','Papua New Guinea','{"en":"Papua New Guinea","es":"Papúa Nueva Guinea","fr":"Papouasie-Nouvelle-Guinée","ja":"パプアニューギニア","zh":"巴布亚新几内亚","zt":"巴布亞新幾內亞"}',166);
INSERT INTO countries VALUES('py','Paraguay','{"en":"Paraguay","es":"Paraguay","fr":"Paraguay","ja":"パラグアイ","zh":"巴拉圭","zt":"巴拉圭"}',167);
INSERT INTO countries VALUES('pe','Perú','{"en":"Peru","es":"Perú","fr":"Pérou","ja":"ペルー","zh":"秘鲁","zt":"秘魯"}',168);
INSERT INTO countries VALUES('ph','Pilipinas','{"en":"Philippines","es":"Filipinas","fr":"Philippines","ja":"フィリピン","zh":"菲律宾","zt":"菲律賓"}',169);
INSERT INTO countries VALUES('pn','Pitcairn','{"en":"Pitcairn","es":"Pitcairn","fr":"Île Pitcairn","ja":"ピトケアン諸島","zh":"皮特凯恩","zt":"皮特凱恩"}',170);
INSERT INTO countries VALUES('pl','Polska','{"en":"Poland","es":"Polonia","fr":"Pologne","ja":"ポーランド","zh":"波兰","zt":"波蘭"}',171);
INSERT INTO countries VALUES('pt','Portugal','{"en":"Portugal","es":"Portugal","fr":"Portugal","ja":"ポルトガル","zh":"葡萄牙","zt":"葡萄牙"}',172);
INSERT INTO countries VALUES('pr','Puerto Rico','{"en":"Puerto Rico","es":"Puerto Rico","fr":"Porto Rico","ja":"プエルトリコ","zh":"波多黎各","zt":"波多黎各"}',173);
INSERT INTO countries VALUES('qa','قطر','{"en":"Qatar","es":"Qatar","fr":"Qatar","ja":"カタール","zh":"卡塔尔","zt":"卡塔爾"}',174);
INSERT INTO countries VALUES('re','Reunion','{"en":"Reunion","es":"Reunión","fr":"Réunion","ja":"レユニオン","zh":"留尼汪","zt":"留尼汪"}',175);
INSERT INTO countries VALUES('ro','România','{"en":"Romania","es":"Rumanía","fr":"Roumanie","ja":"ルーマニア","zh":"罗马尼亚","zt":"羅馬尼亞"}',176);
INSERT INTO countries VALUES('ru','Россия','{"en":"Russia","es":"Rusia","fr":"Russie","ja":"ロシア","zh":"俄罗斯","zt":"俄羅斯"}',177);
INSERT INTO countries VALUES('rw','Rwanda','{"en":"Rwanda","es":"Ruanda","fr":"Rwanda","ja":"ルワンダ","zh":"卢旺达","zt":"盧旺達"}',178);
INSERT INTO countries VALUES('sh','Saint Helena','{"en":"Saint Helena","es":"Santa Elena","fr":"Sainte-Hélène","ja":"セントヘレナ","zh":"圣赫勒拿","zt":"聖赫勒拿"}',179);
INSERT INTO countries VALUES('kn','Saint Kitts and Nevis','{"en":"Saint Kitts and Nevis","es":"San Cristóbal y Nieves","fr":"Saint-Christophe-et-Niévès","ja":"セントクリストファー・ネイビス","zh":"圣基茨和尼维斯","zt":"聖基茨和尼維斯"}',180);
INSERT INTO countries VALUES('lc','Saint Lucia','{"en":"Saint Lucia","es":"Santa Lucía","fr":"Sainte-Lucie","ja":"セントルシア","zh":"圣卢西亚","zt":"聖盧西亞"}',181);
INSERT INTO countries VALUES('pm','Saint Pierre and Miquelon','{"en":"Saint Pierre and Miquelon","es":"San Pedro y Miquelón","fr":"Saint-Pierre-et-Miquelon","ja":"サンピエール島・ミクロン島","zh":"圣皮埃尔和密克隆","zt":"聖皮埃爾和密克隆"}',182);
INSERT INTO countries VALUES('vc','Saint Vincent and the Grenadines','{"en":"Saint Vincent and the Grenadines","es":"San Vicente y las Granadinas","fr":"Saint-Vincent-et-les-Grenadines","ja":"セントビンセント・グレナディーン","zh":"圣文森特和格林纳丁斯","zt":"聖文森特和格林納丁斯"}',183);
INSERT INTO countries VALUES('ws','Samoa','{"en":"Samoa","es":"Samoa","fr":"Les Samoa","ja":"サモア","zh":"萨摩亚","zt":"薩摩亞"}',184);
INSERT INTO countries VALUES('sm','San Marino','{"en":"San Marino","es":"San Marino","fr":"Saint-Marin","ja":"サンマリノ","zh":"圣马力诺","zt":"聖馬力諾"}',185);
INSERT INTO countries VALUES('st','São Tomé and Príncipe','{"en":"São Tomé and Príncipe","es":"Santo Tomé y Príncipe","fr":"Sao Tomé-et-Principe","ja":"サントメ・プリンシペ","zh":"圣多美和普林西比","zt":"聖多美和普林西比"}',186);
INSERT INTO countries VALUES('sa','المملكة العربية السعودية','{"en":"Saudi Arabia","es":"Arabia Saudí","fr":"Arabie saoudite","ja":"サウジアラビア","zh":"沙特阿拉伯","zt":"沙特阿拉伯"}',187);
INSERT INTO countries VALUES('rs','Србија','{"en":"Serbia","es":"Serbia","fr":"Serbie","ja":"セルビア","zh":"塞尔维亚","zt":"塞爾維亞"}',188);
INSERT INTO countries VALUES('sn','Sénégal','{"en":"Senegal","es":"Senegal","fr":"Le Sénégal","ja":"セネガル","zh":"塞内加尔","zt":"塞內加爾"}',189);
INSERT INTO countries VALUES('sc','Seychelles','{"en":"Seychelles","es":"Seychelles","fr":"Seychelles","ja":"セーシェル","zh":"塞舌尔","zt":"塞舌爾"}',190);
INSERT INTO countries VALUES('sl','Sierra Leone','{"en":"Sierra Leone","es":"Sierra Leona","fr":"La Sierra Leone","ja":"シエラレオネ","zh":"塞拉利昂","zt":"塞拉利昂"}',191);
INSERT INTO countries VALUES('sg','Singapura','{"en":"Singapore","es":"Singapur","fr":"Singapour","ja":"シンガポール","zh":"新加坡","zt":"新加坡"}',192);
INSERT INTO countries VALUES('sk','Slovensko','{"en":"Slovakia","es":"Eslovaquia","fr":"La Slovaquie","ja":"スロバキア","zh":"斯洛伐克","zt":"斯洛伐克"}',193);
INSERT INTO countries VALUES('si','Slovenija','{"en":"Slovenia","es":"Eslovenia","fr":"La Slovénie","ja":"スロベニア","zh":"斯洛文尼亚","zt":"斯洛文尼亞"}',194);
INSERT INTO countries VALUES('sb','Solomon Islands','{"en":"Solomon Islands","es":"Islas Salomón","fr":"îles Salomon","ja":"ソロモン諸島","zh":"所罗门群岛","zt":"所羅門群島"}',195);
INSERT INTO countries VALUES('so','Soomaaliya','{"en":"Somalia","es":"Somalia","fr":"La Somalie","ja":"ソマリア","zh":"索马里","zt":"索馬里"}',196);
INSERT INTO countries VALUES('za','South Africa','{"en":"South Africa","es":"Sudáfrica","fr":"L\u0027Afrique du Sud","ja":"南アフリカ","zh":"南非","zt":"南非"}',197);
INSERT INTO countries VALUES('es','España','{"en":"Spain","es":"España","fr":"Espagne","ja":"スペイン","zh":"西班牙","zt":"西班牙"}',198);
INSERT INTO countries VALUES('lk','Sri Lanka','{"en":"Sri Lanka","es":"Sri Lanka","fr":"Sri Lanka","ja":"スリランカ","zh":"斯里兰卡","zt":"斯里蘭卡"}',199);
INSERT INTO countries VALUES('sd','السودان','{"en":"Sudan","es":"Sudán","fr":"Soudan","ja":"スーダン","zh":"苏丹","zt":"蘇丹"}',200);
INSERT INTO countries VALUES('sr','Suriname','{"en":"Suriname","es":"Surinam","fr":"Le Suriname","ja":"スリナム","zh":"苏里南","zt":"蘇里南"}',201);
INSERT INTO countries VALUES('sj','Svalbard and Jan Mayen','{"en":"Svalbard and Jan Mayen","es":"Svalbard y Jan Mayen","fr":"Svalbard et Jan Mayen","ja":"スヴァールバル諸島およびヤンマイエン島","zh":"斯瓦尔巴群岛和扬马延","zt":"斯瓦爾巴群島和揚馬​​延"}',202);
INSERT INTO countries VALUES('sz','Swaziland','{"en":"Swaziland","es":"Suazilandia","fr":"Le Swaziland","ja":"スワジランド","zh":"斯威士兰","zt":"斯威士蘭"}',203);
INSERT INTO countries VALUES('se','Sverige','{"en":"Sweden","es":"Suecia","fr":"Suède","ja":"スウェーデン","zh":"瑞典","zt":"瑞典"}',204);
INSERT INTO countries VALUES('ch','Schweiz','{"en":"Switzerland","es":"Suiza","fr":"Suisse","ja":"スイス","zh":"瑞士","zt":"瑞士"}',205);
INSERT INTO countries VALUES('sy','سوريا','{"en":"Syria","es":"Siria","fr":"La Syrie","ja":"シリア","zh":"叙利亚","zt":"敘利亞"}',206);
INSERT INTO countries VALUES('tw','台灣','{"en":"Taiwan","es":"Taiwán","fr":"Taïwan","ja":"台湾","zh":"台湾","zt":"台灣"}',207);
INSERT INTO countries VALUES('tj','Тоҷикистон','{"en":"Tajikistan","es":"Tayikistán","fr":"Le Tadjikistan","ja":"タジキスタン","zh":"塔吉克斯坦","zt":"塔吉克斯坦"}',208);
INSERT INTO countries VALUES('tz','Tanzania','{"en":"Tanzania","es":"Tanzania","fr":"La Tanzanie","ja":"タンザニア","zh":"坦桑尼亚","zt":"坦桑尼亞"}',209);
INSERT INTO countries VALUES('th','ราชอาณาจักรไทย','{"en":"Thailand","es":"Tailandia","fr":"La Thaïlande","ja":"タイ","zh":"泰国","zt":"泰國"}',210);
INSERT INTO countries VALUES('tg','Togo','{"en":"Togo","es":"Togo","fr":"Le Togo","ja":"トーゴ","zh":"多哥","zt":"多哥"}',211);
INSERT INTO countries VALUES('tk','Tokelau','{"en":"Tokelau","es":"Tokelau","fr":"Les Tokelau","ja":"トケラウ","zh":"托克劳","zt":"托克勞"}',212);
INSERT INTO countries VALUES('to','Tonga','{"en":"Tonga","es":"Tonga","fr":"Les Tonga","ja":"トンガ","zh":"汤加","zt":"湯加"}',213);
INSERT INTO countries VALUES('tt','Trinidad and Tobago','{"en":"Trinidad and Tobago","es":"Trinidad y Tobago","fr":"La Trinité-et-Tobago","ja":"トリニダード・トバゴ","zh":"特立尼达和多巴哥","zt":"特立尼達和多巴哥"}',214);
INSERT INTO countries VALUES('tn','تونس','{"en":"Tunisia","es":"Túnez","fr":"La Tunisie","ja":"チュニジア","zh":"突尼斯","zt":"突尼斯"}',215);
INSERT INTO countries VALUES('tr','Türkiye','{"en":"Turkey","es":"Turquía","fr":"La Turquie","ja":"トルコ","zh":"土耳其","zt":"土耳其"}',216);
INSERT INTO countries VALUES('tm','Türkmenistan','{"en":"Turkmenistan","es":"Turkmenistán","fr":"Le Turkménistan","ja":"トルクメニスタン","zh":"土库曼斯坦","zt":"土庫曼斯坦"}',217);
INSERT INTO countries VALUES('tc','Turks and Caicos Islands','{"en":"Turks and Caicos Islands","es":"Islas Turcas y Caicos","fr":"Les îles Turques-et-Caïques","ja":"タークス・カイコス諸島","zh":"特克斯和凯科斯群岛","zt":"特克斯和凱科斯群島"}',218);
INSERT INTO countries VALUES('tv','Tuvalu','{"en":"Tuvalu","es":"Tuvalu","fr":"Les Tuvalu","ja":"ツバル","zh":"图瓦卢","zt":"圖瓦盧"}',219);
INSERT INTO countries VALUES('ug','Uganda','{"en":"Uganda","es":"Uganda","fr":"L\u0027Ouganda","ja":"ウガンダ","zh":"乌干达","zt":"烏干達"}',220);
INSERT INTO countries VALUES('ua','Україна','{"en":"Ukraine","es":"Ucrania","fr":"L\u0027Ukraine","ja":"ウクライナ","zh":"乌克兰","zt":"烏克蘭"}',221);
INSERT INTO countries VALUES('ae','الإمارات العربيّة المتّحدة','{"en":"United Arab Emirates","es":"Emiratos Árabes Unidos","fr":"Émirats Arabes Unis","ja":"アラブ首長国連邦","zh":"阿拉伯联合酋长国","zt":"阿拉伯聯合酋長國"}',222);
INSERT INTO countries VALUES('gb','United Kingdom','{"en":"United Kingdom","es":"Reino Unido","fr":"Royaume-Uni","ja":"イギリス","zh":"英国","zt":"聯合王國"}',223);
INSERT INTO countries VALUES('us','United States','{"en":"United States","es":"Estados Unidos","fr":"États-Unis","ja":"アメリカ","zh":"美国","zt":"美國"}',224);
INSERT INTO countries VALUES('um','United States minor outlying islands','{"en":"United States minor outlying islands","es":"Islas menores alejadas de los Estados Unidos","fr":"Les îles mineures éloignées des États-Unis","ja":"合衆国領有小離島","zh":"美国本土外小岛屿","zt":"美國本土外小島嶼"}',225);
INSERT INTO countries VALUES('uy','Uruguay','{"en":"Uruguay","es":"Uruguay","fr":"L\u0027Uruguay","ja":"ウルグアイ","zh":"乌拉圭","zt":"烏拉圭"}',226);
INSERT INTO countries VALUES('uz','O''zbekiston','{"en":"Uzbekistan","es":"Uzbekistán","fr":"L\u0027Ouzbékistan","ja":"ウズベキスタン","zh":"乌兹别克斯坦","zt":"烏茲別克斯坦"}',227);
INSERT INTO countries VALUES('vu','Vanuatu','{"en":"Vanuatu","es":"Vanuatu","fr":"Le Vanuatu","ja":"バヌアツ","zh":"瓦努阿图","zt":"瓦努阿圖"}',228);
INSERT INTO countries VALUES('va','Città del Vaticano','{"en":"Vatican City","es":"Ciudad del Vaticano","fr":"Le Vatican","ja":"バチカン","zh":"梵蒂冈城","zt":"梵蒂岡城"}',229);
INSERT INTO countries VALUES('ve','Venezuela','{"en":"Venezuela","es":"Venezuela","fr":"Le Venezuela","ja":"ベネズエラ","zh":"委内瑞拉","zt":"委內瑞拉"}',230);
INSERT INTO countries VALUES('vn','Việt Nam','{"en":"Vietnam","es":"Vietnam","fr":"Le Vietnam","ja":"ベトナム","zh":"越南","zt":"越南"}',231);
INSERT INTO countries VALUES('vg','Virgin Islands, British','{"en":"Virgin Islands, British","es":"Islas Vírgenes Británicas","fr":"Les îles Vierges britanniques","ja":"イギリス領ヴァージン諸島"}',232);
INSERT INTO countries VALUES('vi','Virgin Islands, U.S.','{"en":"Virgin Islands, U.S.","es":"Islas Vírgenes de los Estados Unidos","fr":"Les îles Vierges des États-Unis","ja":"アメリカ領ヴァージン諸島"}',233);
INSERT INTO countries VALUES('wf','Wallis and Futuna','{"en":"Wallis and Futuna","es":"Wallis y Futuna","fr":"Wallis-et-Futuna","ja":"ウォリス・フツナ","zh":"瓦利斯和富图纳群岛","zt":"瓦利斯和富圖納群島"}',234);
INSERT INTO countries VALUES('eh','الصحراء الغربية','{"en":"Western Sahara","es":"Sáhara Occidental","fr":"Sahara occidental","ja":"西サハラ","zh":"西撒哈拉","zt":"西撒哈拉"}',235);
INSERT INTO countries VALUES('ye','اليمن','{"en":"Yemen","es":"Yemen","fr":"Le Yémen","ja":"イエメン","zh":"也门","zt":"也門"}',236);
INSERT INTO countries VALUES('zm','Zambia','{"en":"Zambia","es":"Zambia","fr":"La Zambie","ja":"ザンビア","zh":"赞比亚","zt":"贊比亞"}',237);
INSERT INTO countries VALUES('zw','Zimbabwe','{"en":"Zimbabwe","es":"Zimbabue","fr":"Le Zimbabwe","ja":"ジンバブエ","zh":"津巴布韦","zt":"津巴布韋"}',238);
INSERT INTO countries VALUES('me','Montenegro','{"en":"Montenegro","es":"Montenegro","fr":"Monténégro","ja":"モンテネグロ","zh":"黑山共和国","zt":"黑山共和國"}',239);
INSERT INTO countries VALUES('xk','Kosovo','{"en":"Kosovo","es":"Kosovo","fr":"Le Kosovo","ja":"コソボ","zh":"科索沃","zt":"科索沃"}',240);
INSERT INTO countries VALUES('zz','Various countries','{"en":"Various countries","es":"Varios países","fr":"Pays divers","ja":"その他の国","zh":"各国","zt":"各國"}',241);
INSERT INTO countries VALUES('ap','United States armed forces Pacific','{"en":"United States Armed Forces Pacific","es":"United States armed forces Pacific","fr":"États-Unis Forces armées du Pacifique","ja":"米国太平洋軍"}',242);
INSERT INTO countries VALUES('ax','Åland Islands','{"en":"Aland Islands","es":"Isla Aland","fr":"Åland","ja":"オーランド諸島"}',243);
INSERT INTO countries VALUES('bq','Bonaire, Sint Eustatius and Saba','{"en":"Bonaire Sint Eustatius and Saba","es":"Bonaire, San Eustaquio","fr":"Bonaire, Saint-Eustache et Saba","ja":"ボネール、シント・ユースタティウスおよびサバ"}',244);
INSERT INTO countries VALUES('cw','Curaçao','{"en":"Curacao","es":"Curazao","fr":"Curaçao","ja":"キュラソー　"}',245);
INSERT INTO countries VALUES('eu','European Union','{"en":"European Union","es":"Unión Europea","fr":"Union européenne","ja":"欧州連合","zh":"欧盟","zt":"歐盟"}',246);
INSERT INTO countries VALUES('gg','Bailiwick of Guernsey','{"en":"Guernsey","es":"Guernsey","fr":"Guernesey","ja":"ガーンジー島"}',247);
INSERT INTO countries VALUES('im','Ellan Vannin','{"en":"Isle of Man","es":"Isla de Man","fr":"Île de Man","ja":"マーン島"}',248);
INSERT INTO countries VALUES('je','Bailiwick of Jersey','{"en":"Jersey","es":"Jesery","fr":"Jersey","ja":"Jersey"}',249);
INSERT INTO countries VALUES('ps','فلسطين','{"en":"Palestinian Territory","es":"Territorios Palestinos","fr":"Territoires palestiniens","ja":"パレスチナ自治政府"}',250);
INSERT INTO countries VALUES('ss','South Sudan','{"en":"South Sudan","es":"Sudán del Sur","fr":"Le Soudan du Sud","ja":"南スーダン共和国"}',251);
INSERT INTO countries VALUES('sx','Sint Maarten','{"en":"Sint Maarten","es":"San Martín","fr":"Saint-Martin","ja":"セント・マーティン諸島"}',252);
INSERT INTO countries VALUES('tl','Timor-Leste','{"en":"Timor-Leste","es":"Timor Oriental","fr":"Le Timor oriental","ja":"東ティモール民主共和国"}',253);