DELETE FROM languageTable;
INSERT INTO languageTable VALUES(1,'ab','{"en":"Abkhazian","es":"Abjasio", "ja":"アブハズ語","fr": "Abkhaze"}','Abkhazian','ltr');
INSERT INTO languageTable VALUES(2,'aa','{"en":"Afar","es":"Afar", "ja":"アファール語","fr": "Afar"}','Afar','ltr');
INSERT INTO languageTable VALUES(3,'af','{"en":"Afrikaans","es":"Afrikaans", "ja":"アフリカーンス語","fr": "Afrikaans"}','Afrikaans','ltr');
INSERT INTO languageTable VALUES(4,'ak','{"en":"Akan","es":"Akan", "ja":"アカン語","fr": "Akan"}','Akana','ltr');
INSERT INTO languageTable VALUES(5,'sq','{"en":"Albanian","es":"Albanés", "ja":"アルバニア語","fr": "Albanais"}','Shqip','ltr');
INSERT INTO languageTable VALUES(6,'al','{"en":"Alemannic","es":"Alemánico", "ja":"アレマン語"}','Alemannisch','ltr');
INSERT INTO languageTable VALUES(7,'am','{"en":"Amharic","es":"Amárico", "ja":"アムハラ語","fr": "Amharique"}','Amharic','ltr');
INSERT INTO languageTable VALUES(8,'ag','{"en":"Anglo-Saxon","es":"Anglosajón", "ja":"アングロサクソン語","fr": "Anglo-Saxon"}','AngloSaxon','ltr');
INSERT INTO languageTable VALUES(9,'ar','{"en":"Arabic","es":"Árabe", "ja":"アラビア語","fr": "Arabe"}','العربية','rtl');
INSERT INTO languageTable VALUES(10,'an','{"en":"Aragonese","es":"Aragonés", "ja":"アラゴン語","fr": "Aragonaise"}','Aragonés','ltr');
INSERT INTO languageTable VALUES(11,'hy','{"en":"Armenian","es":"Armenio", "ja":"アルメニア語","fr": "Arménien"}','Հայերեն','ltr');
INSERT INTO languageTable VALUES(12,'ra','{"en":"Aromanian","es":"Arrumano", "ja":"アルーマニア語","fr": "Aroumain"}','Armãneashce','ltr');
INSERT INTO languageTable VALUES(13,'as','{"en":"Assamese","es":"Asamés", "ja":"アッサム語","fr": "Assamais"}','Assamese','ltr');
INSERT INTO languageTable VALUES(14,'at','{"en":"Asturian","es":"Asturiano", "ja":"アストゥリアス語","fr": "Asturien"}','Asturianu','ltr');
INSERT INTO languageTable VALUES(15,'av','{"en":"Avar","es":"Avar", "ja":"リアス語アストゥリアス語","fr": "Avar"}','Авар','ltr');
INSERT INTO languageTable VALUES(16,'ay','{"en":"Aymara","es":"Aimara", "ja":"アイマラ語","fr": "Aymara"}','Aymar','ltr');
INSERT INTO languageTable VALUES(17,'az','{"en":"Azeri","es":"Azerí", "ja":"アゼルバイジャン語","fr": "Azéri"}','Azərbaycan','ltr');
INSERT INTO languageTable VALUES(18,'bm','{"en":"Bambara","es":"Bambara", "ja":"バンバラ語","fr": "Bambara"}','Bamanankan','ltr');
INSERT INTO languageTable VALUES(19,'ba','{"en":"Bashkir","es":"Bashkir", "ja":"バシキール語","fr": "Bachkir"}','Башҡорт','ltr');
INSERT INTO languageTable VALUES(20,'eu','{"en":"Basque","es":"Vasco", "ja":"バスク語","fr": "Basque"}','Euskara','ltr');
INSERT INTO languageTable VALUES(21,'be','{"en":"Belarusian","es":"Bielorruso", "ja":"ベラルーシ語","fr": "Biélorusse"}','Беларуская','ltr');
INSERT INTO languageTable VALUES(22,'bn','{"en":"Bengali","es":"Bengalí", "ja":"ベンガル語","fr": "Bengali"}','Bengali','ltr');
INSERT INTO languageTable VALUES(23,'bh','{"en":"Bihari","es":"Bihari", "ja":"ビハール語","fr": "Bihari"}','भोजपुरी','ltr');
INSERT INTO languageTable VALUES(24,'bi','{"en":"Bislama","es":"Bislama", "ja":"ビスラマ語","fr": "Bichelamar"}','Bislama','ltr');
INSERT INTO languageTable VALUES(25,'bs','{"en":"Bosnian","es":"Bosnio", "ja":"ボスニア語","fr": "Bosnien"}','Bosanski','ltr');
INSERT INTO languageTable VALUES(26,'br','{"en":"Breton","es":"Bretón", "ja":"ブルトン語","fr": "Breton"}','Brezhoneg','ltr');
INSERT INTO languageTable VALUES(27,'bg','{"en":"Bulgarian","es":"Búlgaro", "ja":"ブルガリア語","fr": "Bulgare"}','Български','ltr');
INSERT INTO languageTable VALUES(28,'my','{"en":"Burmese","es":"Birmano", "ja":"ビルマ語（ミャンマー語）","fr": "Birman"}','Myanmasa','ltr');
INSERT INTO languageTable VALUES(29,'km','{"en":"Khmer","es":"Jemer", "ja":"クメール語","fr": "Khmer"}','Khmer','ltr');
INSERT INTO languageTable VALUES(30,'ca','{"en":"Catalan","es":"Catalán", "ja":"カタルーニャ語","fr": "Catalan"}','Català','ltr');
INSERT INTO languageTable VALUES(31,'ch','{"en":"Chamorro","es":"Chamorro", "ja":"チャモロ語","fr": "Chamorro"}','Chamoru','ltr');
INSERT INTO languageTable VALUES(32,'ce','{"en":"Cherokee","es":"Checheno", "ja":"チェロキー語","fr": "Cherokee"}','Cherokee','ltr');
INSERT INTO languageTable VALUES(33,'zh','{"en":"Chinese(简体)","es":"Chino simplificado", "ja":"中国語（簡体字）","fr": "Chinois(简体)"}','简体中文','ltr');
INSERT INTO languageTable VALUES(34,'kw','{"en":"Cornish","es":"Córnico", "ja":"コーンウォール語","fr": "Cornique"}','Kernewek/Karnuack','ltr');
INSERT INTO languageTable VALUES(35,'co','{"en":"Corsican","es":"Corso", "ja":"コルシカ語","fr": "Corse"}','Corsu','ltr');
INSERT INTO languageTable VALUES(36,'cr','{"en":"Cree","es":"Cree", "ja":"クリー語","fr": "Cri"}','Nehiyaw','ltr');
INSERT INTO languageTable VALUES(37,'hr','{"en":"Croatian","es":"Croata", "ja":"クロアチア語","fr": "Croate"}','Hrvatski','ltr');
INSERT INTO languageTable VALUES(38,'cs','{"en":"Czech","es":"Checo", "ja":"チェコ語","fr": "Tchèque"}','Čeština','ltr');
INSERT INTO languageTable VALUES(39,'da','{"en":"Danish","es":"Danés", "ja":"デンマーク語","fr": "Danois"}','Dansk','ltr');
INSERT INTO languageTable VALUES(40,'dv','{"en":"Divehi","es":"Divehi", "ja":"ディベヒ語","fr": "Divehi"}','Divehi','ltr');
INSERT INTO languageTable VALUES(41,'nl','{"en":"Dutch","es":"Neerlandés", "ja":"オランダ語","fr": "Néerlandais"}','Nederlands','ltr');
INSERT INTO languageTable VALUES(42,'dz','{"en":"Dzongkha","es":"Dzongkha", "ja":"ゾンカ語","fr": "Dzongkha"}','Dzongkha','ltr');
INSERT INTO languageTable VALUES(43,'en','{"en":"English","es":"Inglés", "ja":"英語","fr": "Anglais"}','English','ltr');
INSERT INTO languageTable VALUES(44,'eo','{"en":"Esperanto","es":"Esperanto", "ja":"エスペラント","fr": "Espéranto"}','Esperanto','ltr');
INSERT INTO languageTable VALUES(45,'et','{"en":"Estonian","es":"Estonio", "ja":"エストニア語","fr": "Estonien"}','Eesti','ltr');
INSERT INTO languageTable VALUES(46,'fo','{"en":"Faroese","es":"Feroés", "ja":"フェロー語","fr": "Féroïen"}','Føroyskt','ltr');
INSERT INTO languageTable VALUES(47,'fj','{"en":"Fijian","es":"Fiyiano", "ja":"フィジー語","fr": "Fidjien"}','Na Vosa Vakaviti','ltr');
INSERT INTO languageTable VALUES(48,'fi','{"en":"Finnish","es":"Finés", "ja":"フィンランド語","fr": "Finnois"}','Suomi','ltr');
INSERT INTO languageTable VALUES(49,'fr','{"en":"French","es":"Francés", "ja":"フランス語","fr": "Français"}','Français','ltr');
INSERT INTO languageTable VALUES(50,'gl','{"en":"Galician","es":"Gallego", "ja":"ガリシア語","fr": "Galicien"}','Galego','ltr');
INSERT INTO languageTable VALUES(51,'ka','{"en":"Georgian","es":"Georgiano", "ja":"グルジア語","fr": "Géorgien"}','ქართული','ltr');
INSERT INTO languageTable VALUES(52,'de','{"en":"German","es":"Alemán", "ja":"ドイツ語","fr": "Allemand"}','Deutsch','ltr');
INSERT INTO languageTable VALUES(53,'el','{"en":"Greek","es":"Griego", "ja":"ギリシア語","fr": "Grec"}','Ελληνικά','ltr');
INSERT INTO languageTable VALUES(54,'kl','{"en":"Greenlandic","es":"Groenlandés", "ja":"グリーンランド語","fr": "Groenlandais"}','Kalaallisut','ltr');
INSERT INTO languageTable VALUES(55,'gn','{"en":"Guarani","es":"Guaraní", "ja":"グアラニー語","fr": "Guarani"}','Avañe''ẽ','ltr');
INSERT INTO languageTable VALUES(56,'gu','{"en":"Gujarati","es":"Gujarati", "ja":"グジャラート語","fr": "Gujarati"}','ગુજરાતી','ltr');
INSERT INTO languageTable VALUES(57,'ha','{"en":"Hausa","es":"Hausa", "ja":"ハウサ語","fr": "Haoussa"}','هَوُسَ','rtl');
INSERT INTO languageTable VALUES(58,'he','{"en":"Hebrew","es":"Hebreo", "ja":"ヘブライ語","fr": "Hébreu"}','עברית','rtl');
INSERT INTO languageTable VALUES(59,'hi','{"en":"Hindi","es":"Hindi", "ja":"ヒンディー語","fr": "Hindi"}','हिन्दी','ltr');
INSERT INTO languageTable VALUES(60,'hm','{"en":"Hmong","es":"Hmong", "ja":"ミャオ語","fr": "Hmong"}','Hmong','ltr');
INSERT INTO languageTable VALUES(61,'hu','{"en":"Hungarian","es":"Húngaro", "ja":"ハンガリー語","fr": "Hongrois"}','Magyar','ltr');
INSERT INTO languageTable VALUES(62,'is','{"en":"Icelandic","es":"Islandés", "ja":"アイスランド語","fr": "Islandais"}','Íslenska','ltr');
INSERT INTO languageTable VALUES(63,'io','{"en":"Ido","es":"Ido", "ja":"イド語","fr": "Ido"}','Ido','ltr');
INSERT INTO languageTable VALUES(64,'id','{"en":"Indonesian","es":"Indonesio", "ja":"インドネシア語","fr": "Indonésien"}','BahasaIndonesia','ltr');
INSERT INTO languageTable VALUES(65,'ia','{"en":"Interlingua","es":"Interlingua", "ja":"インターリングア","fr": "Interlingua"}','Interlingua','ltr');
INSERT INTO languageTable VALUES(66,'ie','{"en":"Interlingue","es":"Interlingue", "ja":"インターリング","fr": "Interlingue"}','Interlingue','ltr');
INSERT INTO languageTable VALUES(67,'iu','{"en":"Inuktitut","es":"Inuktitut", "ja":"イヌクティトゥット語","fr": "Inuktitut"}','Inuktitut','ltr');
INSERT INTO languageTable VALUES(68,'ik','{"en":"Inupiak","es":"Inupiaq", "ja":"イヌピアック語","fr": "Inupiak"}','Iñupiak','ltr');
INSERT INTO languageTable VALUES(69,'ga','{"en":"Irish","es":"Irlandés", "ja":"アイルランド語","fr": "Irlandais"}','Gaeilge','ltr');
INSERT INTO languageTable VALUES(70,'it','{"en":"Italian","es":"Italiano", "ja":"イタリア語","fr": "Italien"}','Italiano','ltr');
INSERT INTO languageTable VALUES(71,'ja','{"en":"Japanese","es":"Japonés", "ja":"日本語","fr": "Japonais"}','日本語','ltr');
INSERT INTO languageTable VALUES(72,'jv','{"en":"Javanese","es":"Javanés", "ja":"ジャワ語","fr": "Javanais"}','Basa Jawa','ltr');
INSERT INTO languageTable VALUES(73,'kn','{"en":"Kannada","es":"Canarés", "ja":"カンナダ語","fr": "Kannada"}','ಕನ್ನಡ','ltr');
INSERT INTO languageTable VALUES(74,'ks','{"en":"Kashmiri","es":"Cachemiro", "ja":"カシミール語","fr": "Cachemiri"}','कश्मीरी-(كشميري','ltr');
INSERT INTO languageTable VALUES(75,'cb','{"en":"Kashubian","es":"Casubio", "ja":"カシューブ語","fr": "Cachoube"}','Kaszëbsczi','ltr');
INSERT INTO languageTable VALUES(76,'kk','{"en":"Kazakh","es":"Kazajo", "ja":"カザフ語","fr": "Kazakh"}','қазақша','ltr');
INSERT INTO languageTable VALUES(77,'ky','{"en":"Kirghiz","es":"Kirghiz", "ja":"キルギス語","fr": "Kirghize"}','Kırgızca','ltr');
INSERT INTO languageTable VALUES(78,'rn','{"en":"Kirundi","es":"Kiroundi", "ja":"キルンディ語","fr": "Kirundi"}','Kirundi','ltr');
INSERT INTO languageTable VALUES(79,'tm','{"en":"Klingon","es":"Klingon", "ja":"クリゴン語","fr": "Klingon"}','tlh Ingan-Hol','ltr');
INSERT INTO languageTable VALUES(80,'ko','{"en":"Korean","es":"Coreano", "ja":"韓国語","fr": "Coréen"}','한국어','ltr');
INSERT INTO languageTable VALUES(81,'ku','{"en":"Kurdish","es":"Kurdo", "ja":"クルド語","fr": "Kurde"}','Kurdî/كوردی','ltr');
INSERT INTO languageTable VALUES(82,'lo','{"en":"Lao","es":"Laosiano", "ja":"ラーオ語","fr": "Laotien"}','Lao','ltr');
INSERT INTO languageTable VALUES(83,'la','{"en":"Latin","es":"Latín", "ja":"ラテン語","fr": "Latin"}','Latina','ltr');
INSERT INTO languageTable VALUES(84,'lv','{"en":"Latvian","es":"Letón", "ja":"ラトビア語","fr": "Letton"}','Latviešu','ltr');
INSERT INTO languageTable VALUES(85,'li','{"en":"Limburgian","es":"Limburgués", "ja":"リンブルフ語","fr": "Limbourgeois"}','Limburgs','ltr');
INSERT INTO languageTable VALUES(86,'ln','{"en":"Lingala","es":"Lingala", "ja":"リンガラ語","fr": "Lingala"}','Lingala','ltr');
INSERT INTO languageTable VALUES(87,'lt','{"en":"Lithuanian","es":"Lituano", "ja":"リトアニア語","fr": "Lituanien"}','Lietuvių','ltr');
INSERT INTO languageTable VALUES(88,'jb','{"en":"Lojban","es":"Lojban", "ja":"ロジバン","fr": "Lojban"}','Lojban','ltr');
INSERT INTO languageTable VALUES(89,'nd','{"en":"Low Saxon","es":"Ndebele Septentrional", "ja":"低ザクセン語","fr": "Bas allemand"}','Plattdüütsch','ltr');
INSERT INTO languageTable VALUES(90,'lb','{"en":"Luxembourgish","es":"Luxemburgués", "ja":"ルクセンブルク語","fr": "Luxembourgeois"}','Lëtzebuergesch','ltr');
INSERT INTO languageTable VALUES(91,'mk','{"en":"Macedonian","es":"Macedonio", "ja":"マケドニア語","fr": "Macédonien"}','Македонски','ltr');
INSERT INTO languageTable VALUES(92,'mg','{"en":"Malagasy","es":"Malgache", "ja":"マダガスカル語","fr": "Malgache"}','Malagasy','ltr');
INSERT INTO languageTable VALUES(93,'ms','{"en":"Malay","es":"Malayo", "ja":"マレー語","fr": "Malais"}','Bahasa Melayu','ltr');
INSERT INTO languageTable VALUES(94,'ml','{"en":"Malayalam","es":"Malayalam", "ja":"マラヤーラム語","fr": "Malayalam"}','Malayalam','ltr');
INSERT INTO languageTable VALUES(95,'mt','{"en":"Maltese","es":"Maltés", "ja":"マルタ語","fr": "Maltais"}','bil-Malti','ltr');
INSERT INTO languageTable VALUES(96,'gv','{"en":"Manx","es":"Gaélicomanés", "ja":"マン島語","fr": "Mannois"}','Gaelg','ltr');
INSERT INTO languageTable VALUES(97,'mi','{"en":"Maori","es":"Maorí", "ja":"マオリ語","fr": "Maori"}','Māori','ltr');
INSERT INTO languageTable VALUES(98,'mr','{"en":"Marathi","es":"Marathi", "ja":"マラーティー語","fr": "Marathi"}','मराठी','ltr');
INSERT INTO languageTable VALUES(99,'mh','{"en":"Marshallese","es":"Marshalés", "ja":"マーシャル語","fr": "Marshallais"}','Ebon','ltr');
INSERT INTO languageTable VALUES(100,'zm','{"en":"Min Nan","es":"Min Nan", "ja":"閩南語","fr": "Minnan"}','Bân-lâm-gú','ltr');
INSERT INTO languageTable VALUES(101,'mo','{"en":"Moldovan","es":"Moldavo", "ja":"モルドバ語","fr": "Moldave"}','Moldoveana','ltr');
INSERT INTO languageTable VALUES(102,'mn','{"en":"Mongolian","es":"Mongol", "ja":"モンゴル語","fr": "Mongol"}','Монгол','ltr');
INSERT INTO languageTable VALUES(103,'nh','{"en":"Nahuatl","es":"Náhuatl", "ja":"ナワトル語","fr": "Nahuatl"}','Nahuatl','ltr');
INSERT INTO languageTable VALUES(104,'na','{"en":"Nauruan","es":"Nauruano", "ja":"ナウル語","fr": "Nauruan"}','dorerin Naoero','ltr');
INSERT INTO languageTable VALUES(105,'ne','{"en":"Nepali","es":"Nepalí", "ja":"ネパール語","fr": "Népalais"}','नेपाली','ltr');
INSERT INTO languageTable VALUES(106,'no','{"en":"Norwegian (Bokmål)","es":"Noruego", "ja":"ノルウェー語（ブークモール）","fr": "Norvégien (Bokmål)"}','Norsk(Bokmål)','ltr');
INSERT INTO languageTable VALUES(107,'nn','{"en":"Norwegian (Nynorsk)","es":"Nynorsknoruego", "ja":"ノルウェー語（ニーノシュク）","fr": "Norvégien (Nynorsk)"}','Nynorsk','ltr');
INSERT INTO languageTable VALUES(108,'oc','{"en":"Occitan","es":"Occitano", "ja":"オック語","fr": "Occitan"}','Occitan','ltr');
INSERT INTO languageTable VALUES(109,'or','{"en":"Oriya","es":"Oriya", "ja":"オリヤー語","fr": "Oriya"}','Oriya','ltr');
INSERT INTO languageTable VALUES(110,'om','{"en":"Oromo","es":"Oromo", "ja":"オロモ語","fr": "Oromo"}','Oromoo','ltr');
INSERT INTO languageTable VALUES(111,'pi','{"en":"Pali","es":"Pali", "ja":"パーリ語","fr": "Pali"}','पािऴ','ltr');
INSERT INTO languageTable VALUES(112,'ps','{"en":"Pashto","es":"Pashto", "ja":"パシュトー語","fr": "Pachto"}','پښتو','rtl');
INSERT INTO languageTable VALUES(113,'fa','{"en":"Persian","es":"Persa", "ja":"ペルシア語","fr": "Persan"}','فارسی','rtl');
INSERT INTO languageTable VALUES(114,'pl','{"en":"Polish","es":"Polaco", "ja":"ポーランド語","fr": "Polonais"}','Polski','ltr');
INSERT INTO languageTable VALUES(115,'pt','{"en":"Portuguese","es":"Portugués", "ja":"ポルトガル語","fr": "Portugais"}','Português','ltr');
INSERT INTO languageTable VALUES(116,'pa','{"en":"Punjabi","es":"Punjabí", "ja":"パンジャブ語","fr": "Pendjabi"}','ਪੰਜਾਬੀ','ltr');
INSERT INTO languageTable VALUES(117,'qu','{"en":"Quechua","es":"Quechua", "ja":"ケチュア語","fr": "Quechua"}','Runa Simi','ltr');
INSERT INTO languageTable VALUES(118,'rm','{"en":"Raeto Romance","es":"Retorrománico", "ja":"レトロマン語","fr": "Rhéto-roman"}','Rumantsch','ltr');
INSERT INTO languageTable VALUES(119,'ro','{"en":"Romanian","es":"Rumano", "ja":"ルーマニア語","fr": "Roumain"}','Română','ltr');
INSERT INTO languageTable VALUES(120,'ru','{"en":"Russian","es":"Ruso", "ja":"ロシア語","fr": "Russe"}','Русский','ltr');
INSERT INTO languageTable VALUES(121,'rw','{"en":"Rwandi","es":"Kinyarwanda", "ja":"Rwandi"}','Kinyarwanda','ltr');
INSERT INTO languageTable VALUES(122,'sm','{"en":"Samoan","es":"Samoano", "ja":"サモア語","fr": "Samoan"}','Gagana Samoa','ltr');
INSERT INTO languageTable VALUES(123,'sg','{"en":"Sango","es":"Sango", "ja":"サンゴ語","fr": "Sango"}','Sängö','ltr');
INSERT INTO languageTable VALUES(124,'sa','{"en":"Sanskrit","es":"Sánscrito", "ja":"サンスクリット語","fr": "Sanskrit"}','संस्कृतम्','ltr');
INSERT INTO languageTable VALUES(125,'sc','{"en":"Sardinian","es":"Sardo", "ja":"サルディーニャ語","fr": "Sarde"}','Sardu','ltr');
INSERT INTO languageTable VALUES(126,'gd','{"en":"Scottish Gaelic","es":"Gaélico Escocés", "ja":"スコットランド・ゲール語","fr": "Gaélique écossais"}','Gàidhlig','ltr');
INSERT INTO languageTable VALUES(127,'sr','{"en":"Serbian","es":"Serbio", "ja":"セルビア語","fr": "Serbe"}','Српски/Srpski','ltr');
INSERT INTO languageTable VALUES(128,'sh','{"en":"Serbo-Croatian","es":"Serbocroata", "ja":"セルビア・クロアチア語"}','Srpskohrvatski','ltr');
INSERT INTO languageTable VALUES(129,'tn','{"en":"Setswana","es":"Setchwana", "ja":"ツワナ語","fr": "Tswana"}','Setswana','ltr');
INSERT INTO languageTable VALUES(130,'sn','{"en":"Shona","es":"Shona", "ja":"ショナ語","fr": "Shona"}','chi Shona','ltr');
INSERT INTO languageTable VALUES(131,'sb','{"en":"Sicilian","es":"Siciliano", "ja":"シチリア語","fr": "Sicilien"}','Sicilianu','ltr');
INSERT INTO languageTable VALUES(132,'se','{"en":"Simple English","es":"Inglés simplificado", "ja":"ベーシック英語"}','Simple English','ltr');
INSERT INTO languageTable VALUES(133,'sd','{"en":"Sindhi","es":"Sindhi", "ja":"シンド語","fr": "Sindhi"}','سنڌي','rtl');
INSERT INTO languageTable VALUES(134,'si','{"en":"Sinhalese","es":"Cingalés", "ja":"シンハラ語","fr": "Cingalais"}','Sinhalese','ltr');
INSERT INTO languageTable VALUES(135,'sk','{"en":"Slovak","es":"Eslovaco", "ja":"スロバキア語","fr": "Slovaque"}','Slovenčina','ltr');
INSERT INTO languageTable VALUES(136,'sl','{"en":"Slovenian","es":"Esloveno", "ja":"スロベニア語","fr": "Slovène"}','Slovenščina','ltr');
INSERT INTO languageTable VALUES(137,'so','{"en":"Somali","es":"Somalí", "ja":"ソマリ語","fr": "Somali"}','Soomaaliga','ltr');
INSERT INTO languageTable VALUES(138,'st','{"en":"Southern Sotho","es":"Sesotho", "ja":"Southern Sotho","fr": "Sotho du Sud"}','Sesotho','ltr');
INSERT INTO languageTable VALUES(139,'es','{"en":"Spanish","es":"Español", "ja":"スペイン語","fr": "Espagnol"}','Español','ltr');
INSERT INTO languageTable VALUES(140,'su','{"en":"Sundanese","es":"Sundanés", "ja":"スンダ語","fr": "Soundanais"}','Basa Sunda','ltr');
INSERT INTO languageTable VALUES(141,'sw','{"en":"Swahili","es":"Swahili", "ja":"スワヒリ語","fr": "Swahili"}','Kiswahili','ltr');
INSERT INTO languageTable VALUES(142,'ss','{"en":"Swati","es":"Siswati", "ja":"スワティ語","fr": "Swati"}','Si Swati','ltr');
INSERT INTO languageTable VALUES(143,'sv','{"en":"Swedish","es":"Sueco", "ja":"スウェーデン語","fr": "Suédois"}','Svenska','ltr');
INSERT INTO languageTable VALUES(144,'tl','{"en":"Tagalog","es":"Tagalo", "ja":"タガログ語","fr": "Tagalog"}','Tagalog','ltr');
INSERT INTO languageTable VALUES(145,'tg','{"en":"Tajik","es":"Tayiko", "ja":"タジク語","fr": "Tadjik"}','Тоҷикӣ','ltr');
INSERT INTO languageTable VALUES(146,'ta','{"en":"Tamil","es":"Tamil", "ja":"タミル語","fr": "Tamoul"}','தமிழ்','ltr');
INSERT INTO languageTable VALUES(147,'tt','{"en":"Tatar","es":"Tártaro", "ja":"タタール語","fr": "Tatar"}','Tatarça/Татарча','ltr');
INSERT INTO languageTable VALUES(148,'te','{"en":"Telugu","es":"Telugu", "ja":"テルグ語","fr": "Télougou"}','తెలుగు','ltr');
INSERT INTO languageTable VALUES(149,'th','{"en":"Thai","es":"Tailandés", "ja":"タイ語","fr": "Thaï"}','ไทย','ltr');
INSERT INTO languageTable VALUES(150,'bo','{"en":"Tibetan","es":"Tibetano", "ja":"チベット語","fr": "Tibétain"}','Bodskad','ltr');
INSERT INTO languageTable VALUES(151,'ti','{"en":"Tigrinya","es":"Tegriña", "ja":"ティグリニア語","fr": "Tigrigna"}','Tigrinya','ltr');
INSERT INTO languageTable VALUES(152,'tp','{"en":"Tok Pisin","es":"Tok Pisin", "ja":"トク・ピシン語","fr": "Tok pisin"}','Tok Pisin','ltr');
INSERT INTO languageTable VALUES(153,'tq','{"en":"Tokipona","es":"Tokipona", "ja":"トキポナ","fr": "Toki pona"}','Tokipona','ltr');
INSERT INTO languageTable VALUES(154,'to','{"en":"Tongan","es":"Tonga (islas tonga)", "ja":"トンガ語","fr": "Tongien"}','Faka Tonga','ltr');
INSERT INTO languageTable VALUES(155,'ts','{"en":"Tsonga","es":"Tsonga", "ja":"Tsonga","fr": "Tsonga"}','Xitsonga','ltr');
INSERT INTO languageTable VALUES(156,'tr','{"en":"Turkish","es":"Turco", "ja":"トルコ語","fr": "Turc"}','Türkçe','ltr');
INSERT INTO languageTable VALUES(157,'tk','{"en":"Turkmen","es":"Turcomano", "ja":"トルクメン語","fr": "Turkmène"}','تركمن/Туркмен','ltr');
INSERT INTO languageTable VALUES(158,'tw','{"en":"Twi","es":"Twi", "ja":"トウィ語","fr": "Twi"}','Twi','ltr');
INSERT INTO languageTable VALUES(159,'uk','{"en":"Ukrainian","es":"Ucraniano", "ja":"ウクライナ語","fr": "Ukrainien"}','Українська','ltr');
INSERT INTO languageTable VALUES(160,'ur','{"en":"Urdu","es":"Urdu", "ja":"ウルドゥー語","fr": "Ourdou"}','اڙدو','rtl');
INSERT INTO languageTable VALUES(161,'ug','{"en":"Uyghur","es":"Uigur", "ja":"ウイグル語","fr": "Ouïghour"}','Oyghurque','ltr');
INSERT INTO languageTable VALUES(162,'uz','{"en":"Uzbek","es":"Uzbeko", "ja":"ウズベク語","fr": "Ouzbek"}','O‘zbek','ltr');
INSERT INTO languageTable VALUES(163,'vi','{"en":"Vietnamese","es":"Vietnamita", "ja":"ベトナム語","fr": "Vietnamien"}','TiếngViệt','ltr');
INSERT INTO languageTable VALUES(164,'vo','{"en":"Volapük","es":"Volapük", "ja":"ヴォラピュク","fr": "Volapük"}','Volapük','ltr');
INSERT INTO languageTable VALUES(165,'wa','{"en":"Walloon","es":"Valón", "ja":"ワロン語","fr": "Wallon"}','Walon','ltr');
INSERT INTO languageTable VALUES(166,'cy','{"en":"Welsh","es":"Galés", "ja":"ウェールズ語","fr": "Gallois"}','Cymraeg','ltr');
INSERT INTO languageTable VALUES(167,'fy','{"en":"WestFrisian","es":"Frisón", "ja":"西フリジア語","fr": "Frison occidental"}','Frysk','ltr');
INSERT INTO languageTable VALUES(168,'wo','{"en":"Wolof","es":"Uolof", "ja":"ウォロフ語","fr": "Wolof"}','Wollof','ltr');
INSERT INTO languageTable VALUES(169,'xh','{"en":"Xhosan","es":"Xhosa", "ja":"ホサ語","fr": "Xhosa"}','isiXhosa','ltr');
INSERT INTO languageTable VALUES(170,'yi','{"en":"Yiddish","es":"Yidis", "ja":"イディッシュ語","fr": "Yiddish"}','ייִדיש','rtl');
INSERT INTO languageTable VALUES(171,'yo','{"en":"Yoruba","es":"Yoruba", "ja":"ヨルバ語","fr": "Yoruba"}','Yorùbá','ltr');
INSERT INTO languageTable VALUES(172,'za','{"en":"Zhuang","es":"Zhuang", "ja":"チワン語","fr": "Zhuang"}','Cuengh','ltr');
INSERT INTO languageTable VALUES(173,'zu','{"en":"Zulu","es":"Zulú", "ja":"ズールー語","fr": "Zoulou"}','isiZulu','ltr');
INSERT INTO languageTable VALUES(174,'zt','{"en":"Chinese(繁體)","es":"Chino tradicionál", "ja":"中国語（繁体字）","fr": "Chinois(繁體)"}','繁體中文','ltr');
INSERT INTO languageTable VALUES(175,'mu','{"en":"Karaoke","es":"Karaoke", "ja":"カラオケ","fr": "Karaoké"}','Karaoke','ltr');
INSERT INTO languageTable VALUES(176,'udm','{"en":"Udmurt","es":"Udmurto", "ja":"ウドムルト語","fr": "Oudmourte"}','УдмуртЭлькун','ltr');
INSERT INTO languageTable VALUES(177,'han','{"en":"Xiang","es":"Xiang", "ja":"湘語","fr": "Xiang"}','湖南话','ltr');
INSERT INTO languageTable VALUES(178,'hak','{"en":"Hakka","es":"Hakka", "ja":"客家語","fr": "Hakka"}','客家','ltr');
INSERT INTO languageTable VALUES(179,'bho','{"en":"Bhojpuri","es":"Bhojpuri", "ja":"ポージブリー語","fr": "Bhodjpouri"}','भोजपुरी','ltr');
INSERT INTO languageTable VALUES(180,'mai','{"en":"Maithili","es":"Maithili", "ja":"マイティリー語","fr": "Maïthili"}','मैथिली','ltr');
INSERT INTO languageTable VALUES(181,'ful','{"en":"Fula","es":"Fula", "ja":"フラ語","fr": "Peul"}','Fula','ltr');
INSERT INTO languageTable VALUES(182,'ibo','{"en":"Igbo","es":"Igbo", "ja":"イボ語","fr": "Igbo"}','Igbo','ltr');
INSERT INTO languageTable VALUES(183,'gan','{"en":"Gan","es":"Gan", "ja":"カン語","fr": "Gan"}','贛語','ltr');
INSERT INTO languageTable VALUES(184,'ceb','{"en":"Cebuano/Binisaya","es":"Cebuano/Bisaya", "ja":"セブアノ語","fr": "Cebuano/Binisaya"}','Binisaya','ltr');
INSERT INTO languageTable VALUES(185,'skr','{"en":"Saraiki","es":"Saraiki", "ja":"サライキ語","fr": "Seraiki"}','سرائیکی','ltr');
INSERT INTO languageTable VALUES(186,'ctg','{"en":"Chittagonian","es":"Chittagonian", "ja":"チッタゴン語","fr": "Chittagonien"}','টগাঁইয়াবুলি','ltr');
INSERT INTO languageTable VALUES(187,'mad','{"en":"Madurese","es":"Madurés", "ja":"マドゥラ語","fr": "Madurais"}','بَهاسَمَدورا','ltr');
INSERT INTO languageTable VALUES(188,'bgc','{"en":"Haryanvi","es":"Haryanvi", "ja":"ハリヤーンウィー語","fr": "Haryanvi"}','हरियाणवी','ltr');
INSERT INTO languageTable VALUES(189,'mwr','{"en":"Marwari","es":"Marwari", "ja":"マールワーリー語","fr": "Marwari"}','मारवाड़ी','ltr');
INSERT INTO languageTable VALUES(190,'hne','{"en":"Chhattisgarhi","es":"Chhattisgarhi", "ja":"チャッティースガリー語 ","fr": "Chhattisgarhi"}','छत्तीसगढ़ी','ltr');
INSERT INTO languageTable VALUES(191,'nya','{"en":"Chewa/Nyanja","es":"Chewa/Nyanja", "ja":"チェワ語/ニャンジャ語","fr": "Chichewa/Nyanja"}','Nyanja','ltr');
INSERT INTO languageTable VALUES(192,'dcc','{"en":"Dakhini","es":"Dakani", "ja":"ダーキニー語","fr": "Dakhini"}','دکنی‎','ltr');
INSERT INTO languageTable VALUES(193,'mnp','{"en":"Min Bei","es":"Min Bei", "ja":"閩北語","fr": "Minbei"}','闽北语','ltr');
INSERT INTO languageTable VALUES(194,'cdo','{"en":"Min Dong","es":"Min Dong", "ja":"閩東語","fr": "Mindong"}','閩東語','ltr');
INSERT INTO languageTable VALUES(195,'syl','{"en":"Sylheti","es":"Sylheti", "ja":"シロティ語","fr": "Sylheti"}','ছিলটী','ltr');
INSERT INTO languageTable VALUES(196,'kin','{"en":"Kinyarwanda","es":"Kinyarwanda", "ja":"ルワンダ語","fr": "Kinyarwanda"}','Ikinyarwanda','ltr');
INSERT INTO languageTable VALUES(197,'hat','{"en":"Haitian Creole","es":"Criollo Haitiano", "ja":"ハイチ・クレオール語","fr": "Créole haïtien"}','Kreyòlayisyen','ltr');
INSERT INTO languageTable VALUES(198,'ilo','{"en":"Ilokano","es":"Ilocano", "ja":"イロカノ語","fr": "Ilocano"}','Ilokano','ltr');
INSERT INTO languageTable VALUES(199,'mos','{"en":"Mossi","es":"Moré", "ja":"モシ語","fr": "Moré"}','Mòoré','ltr');
INSERT INTO languageTable VALUES(200,'bal','{"en":"Balochi","es":"Baluchi", "ja":"バルーチー語","fr": "Baloutche"}','بلوچی','ltr');
INSERT INTO languageTable VALUES(201,'kok','{"en":"Konkani","es":"Konkaní", "ja":"コンカニ語","fr": "Konkani"}','कोंकणी','ltr');
INSERT INTO languageTable VALUES(202,'zom','{"en":"Zomi","es":"Zomi", "ja":"ゾミ語","fr": "Zomi"}','Zomi','ltr');
INSERT INTO languageTable VALUES(203,'lol','{"en":"lolspeak","es":"lolspeak", "ja":"lolspeak","fr": "lolspeak"}','lolspeak','ltr');
INSERT INTO languageTable VALUES(204,'foi','{"en":"Foe","ja":"フォイ語","es":"Foe","fr":"Foe"}','Foi','ltr');
INSERT INTO languageTable VALUES(205,'hru','{"en":"Hruso","ja":"フルソ語","es":"Hruso","fr":"Hruso"}','Hruso','ltr');
INSERT INTO languageTable VALUES(206,'huh','{"en":"Huilliche","ja":"ウィリチェ語","es":"Huilliche","fr":"Huilliche"}','Huilliche','ltr');
INSERT INTO languageTable VALUES(207,'xal','{"en":"Kalmyk","ja":"カルムイク語","es":"Kalmyk","fr":"Kalmouk"}','Kalmyk','ltr');
INSERT INTO languageTable VALUES(208,'kim','{"en":"Tofa","ja":"トファ語","es":"Tofa","fr":"Tofalar"}','тоъфá','ltr');
INSERT INTO languageTable VALUES(209,'tzx','{"en":"Yokoim","ja":"ヨコイム語","es":"Yokoim","fr":"Yokoim"}','Yokoim','ltr');
INSERT INTO languageTable VALUES(210,'mkj','{"en":"Mokilese","ja":"モキル語","es":"Mokilese","fr":"Mokil"}','Mokilese','ltr');
INSERT INTO languageTable VALUES(211,'sat','{"en":"Santhali","ja":"サンタル語","es":"Santhali","fr":"Santali"}','Santhali','ltr');
INSERT INTO languageTable VALUES(212,'wnw','{"en":"Winnemem Wintu","ja":"ウィネメム・ウィントゥ語","es":"Winnemem Wintu","fr":"Winnemem Wintu"}','Winnemem Wintu','ltr');
INSERT INTO languageTable VALUES(213,'mne','{"en":"Montenegrin","ja":"モンテネグロ語","es":"Montenegrina","fr":"Monténégrin"}','црногорски','ltr');
