DELETE FROM languageTable;
INSERT INTO languageTable VALUES(1,'ab','{"en":"Abkhazian","es":"Abjasio", "ja":"アブハズ語","fr": "Abkhaze","zh": "阿布哈西亚语","zt": "阿布哈茲語"}','Abkhazian','ltr');
INSERT INTO languageTable VALUES(2,'aa','{"en":"Afar","es":"Afar", "ja":"アファール語","fr": "Afar","zh": "阿法尔语","zt": "阿法爾語"}','Afar','ltr');
INSERT INTO languageTable VALUES(3,'af','{"en":"Afrikaans","es":"Afrikaans", "ja":"アフリカーンス語","fr": "Afrikaans","zh": "南非荷兰语","zt": "南非荷蘭語"}','Afrikaans','ltr');
INSERT INTO languageTable VALUES(4,'ak','{"en":"Akan","es":"Akan", "ja":"アカン語","fr": "Akan","zh": "阿肯语","zt": "阿肯語"}','Akana','ltr');
INSERT INTO languageTable VALUES(5,'sq','{"en":"Albanian","es":"Albanés", "ja":"アルバニア語","fr": "Albanais","zh": "阿尔巴尼亚语","zt": "阿爾巴尼亞語"}','Shqip','ltr');
INSERT INTO languageTable VALUES(6,'al','{"en":"Alemannic","es":"Alemánico", "ja":"アレマン語"}','Alemannisch','ltr');
INSERT INTO languageTable VALUES(7,'am','{"en":"Amharic","es":"Amárico", "ja":"アムハラ語","fr": "Amharique","zh": "阿姆哈拉语","zt": "阿姆哈拉語"}','Amharic','ltr');
INSERT INTO languageTable VALUES(8,'ag','{"en":"Anglo-Saxon","es":"Anglosajón", "ja":"アングロサクソン語","fr": "Anglo-Saxon","zh": "盎格鲁-撒克逊语","zt": "盎格魯 - 撒克遜語"}','AngloSaxon','ltr');
INSERT INTO languageTable VALUES(9,'ar','{"en":"Arabic","es":"Árabe", "ja":"アラビア語","fr": "Arabe","zh": "阿拉伯语","zt": "阿拉伯語"}','العربية','rtl');
INSERT INTO languageTable VALUES(10,'an','{"en":"Aragonese","es":"Aragonés", "ja":"アラゴン語","fr": "Aragonaise","zh": "阿拉贡语","zt": "阿拉貢語"}','Aragonés','ltr');
INSERT INTO languageTable VALUES(11,'hy','{"en":"Armenian","es":"Armenio", "ja":"アルメニア語","fr": "Arménien","zh": "亚美尼亚语","zt": "亞美尼亞語"}','Հայերեն','ltr');
INSERT INTO languageTable VALUES(12,'ra','{"en":"Aromanian","es":"Arrumano", "ja":"アルーマニア語","fr": "Aroumain","zh": "罗马尼亚语","zt": "羅馬尼亞語"}','Armãneashce','ltr');
INSERT INTO languageTable VALUES(13,'as','{"en":"Assamese","es":"Asamés", "ja":"アッサム語","fr": "Assamais","zh": "阿萨姆语","zt": "阿薩姆語"}','Assamese','ltr');
INSERT INTO languageTable VALUES(14,'at','{"en":"Asturian","es":"Asturiano", "ja":"アストゥリアス語","fr": "Asturien","zh": "阿斯图里亚斯语","zt": "阿斯圖里亞斯語"}','Asturianu','ltr');
INSERT INTO languageTable VALUES(15,'av','{"en":"Avar","es":"Avar", "ja":"リアス語アストゥリアス語","fr": "Avar","zh": "阿瓦尔语","zt": "阿瓦爾語"}','Авар','ltr');
INSERT INTO languageTable VALUES(16,'ay','{"en":"Aymara","es":"Aimara", "ja":"アイマラ語","fr": "Aymara","zh": "艾马拉语","zt": "艾馬拉語"}','Aymar','ltr');
INSERT INTO languageTable VALUES(17,'az','{"en":"Azeri","es":"Azerí", "ja":"アゼルバイジャン語","fr": "Azéri","zh": "阿塞拜疆语","zt": "阿澤語"}','Azərbaycan','ltr');
INSERT INTO languageTable VALUES(18,'bm','{"en":"Bambara","es":"Bambara", "ja":"バンバラ語","fr": "Bambara","zh": "班拉族语","zt": "班巴拉語"}','Bamanankan','ltr');
INSERT INTO languageTable VALUES(19,'ba','{"en":"Bashkir","es":"Bashkir", "ja":"バシキール語","fr": "Bachkir","zh": "巴什基尔语","zt": "巴什基爾語"}','Башҡорт','ltr');
INSERT INTO languageTable VALUES(20,'eu','{"en":"Basque","es":"Vasco", "ja":"バスク語","fr": "Basque","zh": "巴斯克语","zt": "巴斯克語"}','Euskara','ltr');
INSERT INTO languageTable VALUES(21,'be','{"en":"Belarusian","es":"Bielorruso", "ja":"ベラルーシ語","fr": "Biélorusse","zh": "白俄罗斯语","zt": "白俄羅斯語"}','Беларуская','ltr');
INSERT INTO languageTable VALUES(22,'bn','{"en":"Bengali","es":"Bengalí", "ja":"ベンガル語","fr": "Bengali","zh": "孟加拉语","zt": "孟加拉語"}','Bengali','ltr');
INSERT INTO languageTable VALUES(23,'bh','{"en":"Bihari","es":"Bihari", "ja":"ビハール語","fr": "Bihari","zh": "比哈尔语","zt": "比哈里語"}','भोजपुरी','ltr');
INSERT INTO languageTable VALUES(24,'bi','{"en":"Bislama","es":"Bislama", "ja":"ビスラマ語","fr": "Bichelamar","zh": "比斯克语","zt": "比斯拉馬語"}','Bislama','ltr');
INSERT INTO languageTable VALUES(25,'bs','{"en":"Bosnian","es":"Bosnio", "ja":"ボスニア語","fr": "Bosnien","zh": "波斯语","zt": "波斯尼亞語"}','Bosanski','ltr');
INSERT INTO languageTable VALUES(26,'br','{"en":"Breton","es":"Bretón", "ja":"ブルトン語","fr": "Breton","zh": "布列塔尼语","zt": "布列塔尼語"}','Brezhoneg','ltr');
INSERT INTO languageTable VALUES(27,'bg','{"en":"Bulgarian","es":"Búlgaro", "ja":"ブルガリア語","fr": "Bulgare","zh": "保加利亚语","zt": "保加利亞語"}','Български','ltr');
INSERT INTO languageTable VALUES(28,'my','{"en":"Burmese","es":"Birmano", "ja":"ビルマ語（ミャンマー語）","fr": "Birman","zh": "缅甸语","zt": "緬甸語"}','Myanmasa','ltr');
INSERT INTO languageTable VALUES(29,'km','{"en":"Khmer","es":"Jemer", "ja":"クメール語","fr": "Khmer","zh": "高棉语","zt": "高棉語"}','Khmer','ltr');
INSERT INTO languageTable VALUES(30,'ca','{"en":"Catalan","es":"Catalán", "ja":"カタルーニャ語","fr": "Catalan","zh": "加泰罗尼亚语","zt": "加泰羅尼亞語"}','Català','ltr');
INSERT INTO languageTable VALUES(31,'ch','{"en":"Chamorro","es":"Chamorro", "ja":"チャモロ語","fr": "Chamorro","zh": "查莫洛语","zt": "查莫羅語"}','Chamoru','ltr');
INSERT INTO languageTable VALUES(32,'ce','{"en":"Cherokee","es":"Checheno", "ja":"チェロキー語","fr": "Cherokee","zh": "爱沙尼亚语","zt": "切諾基語"}','Cherokee','ltr');
INSERT INTO languageTable VALUES(33,'zh','{"en":"Chinese(简体)","es":"Chino simplificado", "ja":"中国語（簡体字）","fr": "Chinois(简体)","zh": "简体中文","zt": "簡體中文"}','简体中文','ltr');
INSERT INTO languageTable VALUES(34,'kw','{"en":"Cornish","es":"Córnico", "ja":"コーンウォール語","fr": "Cornique","zh": "康沃尔语","zt": "康沃爾語"}','Kernewek/Karnuack','ltr');
INSERT INTO languageTable VALUES(35,'co','{"en":"Corsican","es":"Corso", "ja":"コルシカ語","fr": "Corse","zh": "科西嘉语","zt": "科西嘉語"}','Corsu','ltr');
INSERT INTO languageTable VALUES(36,'cr','{"en":"Cree","es":"Cree", "ja":"クリー語","fr": "Cri","zh": "克里语","zt": "克里語"}','Nehiyaw','ltr');
INSERT INTO languageTable VALUES(37,'hr','{"en":"Croatian","es":"Croata", "ja":"クロアチア語","fr": "Croate","zh": "克罗地亚语","zt": "克羅地亞語"}','Hrvatski','ltr');
INSERT INTO languageTable VALUES(38,'cs','{"en":"Czech","es":"Checo", "ja":"チェコ語","fr": "Tchèque","zh": "捷克语","zt": "捷克語"}','Čeština','ltr');
INSERT INTO languageTable VALUES(39,'da','{"en":"Danish","es":"Danés", "ja":"デンマーク語","fr": "Danois","zh": "丹麦语","zt": "丹麥語"}','Dansk','ltr');
INSERT INTO languageTable VALUES(40,'dv','{"en":"Divehi","es":"Divehi", "ja":"ディベヒ語","fr": "Divehi","zh": "迪维希语","zt": "迪維希語"}','Divehi','ltr');
INSERT INTO languageTable VALUES(41,'nl','{"en":"Dutch","es":"Neerlandés", "ja":"オランダ語","fr": "Néerlandais","zh": "荷兰语","zt": "荷蘭語"}','Nederlands','ltr');
INSERT INTO languageTable VALUES(42,'dz','{"en":"Dzongkha","es":"Dzongkha", "ja":"ゾンカ語","fr": "Dzongkha","zh": "不丹语","zt": "不丹語"}','Dzongkha','ltr');
INSERT INTO languageTable VALUES(43,'en','{"en":"English","es":"Inglés", "ja":"英語","fr": "Anglais","zh": "英语","zt": "英語"}','English','ltr');
INSERT INTO languageTable VALUES(44,'eo','{"en":"Esperanto","es":"Esperanto", "ja":"エスペラント","fr": "Espéranto","zh": "世界语","zt": "世界語"}','Esperanto','ltr');
INSERT INTO languageTable VALUES(45,'et','{"en":"Estonian","es":"Estonio", "ja":"エストニア語","fr": "Estonien","zh": "爱沙尼亚语","zt": "愛沙尼亞語"}','Eesti','ltr');
INSERT INTO languageTable VALUES(46,'fo','{"en":"Faroese","es":"Feroés", "ja":"フェロー語","fr": "Féroïen","zh": "法罗群岛语","zt": "法羅群島語"}','Føroyskt','ltr');
INSERT INTO languageTable VALUES(47,'fj','{"en":"Fijian","es":"Fiyiano", "ja":"フィジー語","fr": "Fidjien","zh": "斐济语","zt": "斐濟語"}','Na Vosa Vakaviti','ltr');
INSERT INTO languageTable VALUES(48,'fi','{"en":"Finnish","es":"Finés", "ja":"フィンランド語","fr": "Finnois","zh": "芬兰语","zt": "芬蘭語"}','Suomi','ltr');
INSERT INTO languageTable VALUES(49,'fr','{"en":"French","es":"Francés", "ja":"フランス語","fr": "Français","zh": "法语","zt": "法語"}','Français','ltr');
INSERT INTO languageTable VALUES(50,'gl','{"en":"Galician","es":"Gallego", "ja":"ガリシア語","fr": "Galicien","zh": "加利西亚语","zt": "加利西亞語"}','Galego','ltr');
INSERT INTO languageTable VALUES(51,'ka','{"en":"Georgian","es":"Georgiano", "ja":"グルジア語","fr": "Géorgien","zh": "格鲁吉亚语","zt": "格魯吉亞語"}','ქართული','ltr');
INSERT INTO languageTable VALUES(52,'de','{"en":"German","es":"Alemán", "ja":"ドイツ語","fr": "Allemand","zh": "德语","zt": "德語"}','Deutsch','ltr');
INSERT INTO languageTable VALUES(53,'el','{"en":"Greek","es":"Griego", "ja":"ギリシア語","fr": "Grec","zh": "希腊语","zt": "希臘語"}','Ελληνικά','ltr');
INSERT INTO languageTable VALUES(54,'kl','{"en":"Greenlandic","es":"Groenlandés", "ja":"グリーンランド語","fr": "Groenlandais","zh": "格陵兰语","zt": "格陵蘭語"}','Kalaallisut','ltr');
INSERT INTO languageTable VALUES(55,'gn','{"en":"Guarani","es":"Guaraní", "ja":"グアラニー語","fr": "Guarani","zh": "瓜拉尼语","zt": "瓜拉尼語"}','Avañe''ẽ','ltr');
INSERT INTO languageTable VALUES(56,'gu','{"en":"Gujarati","es":"Gujarati", "ja":"グジャラート語","fr": "Gujarati","zh": "古吉拉特语","zt": "古吉拉特語"}','ગુજરાતી','ltr');
INSERT INTO languageTable VALUES(57,'ha','{"en":"Hausa","es":"Hausa", "ja":"ハウサ語","fr": "Haoussa","zh": "豪萨语","zt": "豪薩語"}','هَوُسَ','rtl');
INSERT INTO languageTable VALUES(58,'he','{"en":"Hebrew","es":"Hebreo", "ja":"ヘブライ語","fr": "Hébreu","zh": "希伯来语","zt": "希伯來語"}','עברית','rtl');
INSERT INTO languageTable VALUES(59,'hi','{"en":"Hindi","es":"Hindi", "ja":"ヒンディー語","fr": "Hindi","zh": "印地语","zt": "印地語"}','हिन्दी','ltr');
INSERT INTO languageTable VALUES(60,'hm','{"en":"Hmong","es":"Hmong", "ja":"ミャオ語","fr": "Hmong","zh": "苗语","zt": "苗語"}','Hmong','ltr');
INSERT INTO languageTable VALUES(61,'hu','{"en":"Hungarian","es":"Húngaro", "ja":"ハンガリー語","fr": "Hongrois","zh": "匈牙利语","zt": "匈牙利語"}','Magyar','ltr');
INSERT INTO languageTable VALUES(62,'is','{"en":"Icelandic","es":"Islandés", "ja":"アイスランド語","fr": "Islandais","zh": "冰岛语","zt": "冰島語"}','Íslenska','ltr');
INSERT INTO languageTable VALUES(63,'io','{"en":"Ido","es":"Ido", "ja":"イド語","fr": "Ido","zh": "伊多语","zt": "伊多語"}','Ido','ltr');
INSERT INTO languageTable VALUES(64,'id','{"en":"Indonesian","es":"Indonesio", "ja":"インドネシア語","fr": "Indonésien","zh": "印尼语","zt": "印度尼西亞語"}','BahasaIndonesia','ltr');
INSERT INTO languageTable VALUES(65,'ia','{"en":"Interlingua","es":"Interlingua", "ja":"インターリングア","fr": "Interlingua","zh": "国际语","zt": "國際語"}','Interlingua','ltr');
INSERT INTO languageTable VALUES(66,'ie','{"en":"Interlingue","es":"Interlingue", "ja":"インターリング","fr": "Interlingue","zh": "国际语","zt": "國際語"}','Interlingue','ltr');
INSERT INTO languageTable VALUES(67,'iu','{"en":"Inuktitut","es":"Inuktitut", "ja":"イヌクティトゥット語","fr": "Inuktitut","zh": "因纽特语","zt": "因紐特語"}','Inuktitut','ltr');
INSERT INTO languageTable VALUES(68,'ik','{"en":"Inupiak","es":"Inupiaq", "ja":"イヌピアック語","fr": "Inupiak","zh": "依奴皮维克语","zt": "依奴皮維克語"}','Iñupiak','ltr');
INSERT INTO languageTable VALUES(69,'ga','{"en":"Irish","es":"Irlandés", "ja":"アイルランド語","fr": "Irlandais","zh": "爱尔兰语","zt": "愛爾蘭語"}','Gaeilge','ltr');
INSERT INTO languageTable VALUES(70,'it','{"en":"Italian","es":"Italiano", "ja":"イタリア語","fr": "Italien","zh": "意大利语","zt": "意大利語"}','Italiano','ltr');
INSERT INTO languageTable VALUES(71,'ja','{"en":"Japanese","es":"Japonés", "ja":"日本語","fr": "Japonais","zh": "日语","zt": "日語"}','日本語','ltr');
INSERT INTO languageTable VALUES(72,'jv','{"en":"Javanese","es":"Javanés", "ja":"ジャワ語","fr": "Javanais","zh": "爪哇语","zt": "爪哇語"}','Basa Jawa','ltr');
INSERT INTO languageTable VALUES(73,'kn','{"en":"Kannada","es":"Canarés", "ja":"カンナダ語","fr": "Kannada","zh": "卡纳达语","zt": "卡納達語"}','ಕನ್ನಡ','ltr');
INSERT INTO languageTable VALUES(74,'ks','{"en":"Kashmiri","es":"Cachemiro", "ja":"カシミール語","fr": "Cachemiri","zh": "克什米尔语","zt": "克什米爾語"}','कश्मीरी-(كشميري','ltr');
INSERT INTO languageTable VALUES(75,'cb','{"en":"Kashubian","es":"Casubio", "ja":"カシューブ語","fr": "Cachoube","zh": "卡舒比语","zt": "卡舒比語"}','Kaszëbsczi','ltr');
INSERT INTO languageTable VALUES(76,'kk','{"en":"Kazakh","es":"Kazajo", "ja":"カザフ語","fr": "Kazakh","zh": "哈萨克斯坦语","zt": "哈薩克語"}','қазақша','ltr');
INSERT INTO languageTable VALUES(77,'ky','{"en":"Kirghiz","es":"Kirghiz", "ja":"キルギス語","fr": "Kirghize","zh": "吉尔吉斯语","zt": "吉爾吉斯語"}','Kırgızca','ltr');
INSERT INTO languageTable VALUES(78,'rn','{"en":"Kirundi","es":"Kiroundi", "ja":"キルンディ語","fr": "Kirundi","zh": "基隆迪语","zt": "基隆迪語"}','Kirundi','ltr');
INSERT INTO languageTable VALUES(79,'tm','{"en":"Klingon","es":"Klingon", "ja":"クリゴン語","fr": "Klingon","zh": "克林贡语","zt": "克林貢語"}','tlh Ingan-Hol','ltr');
INSERT INTO languageTable VALUES(80,'ko','{"en":"Korean","es":"Coreano", "ja":"韓国語","fr": "Coréen", "zh": "韩语", "zt": "朝鮮語"}','한국어','ltr');
INSERT INTO languageTable VALUES(81,'ku','{"en":"Kurdish","es":"Kurdo", "ja":"クルド語","fr": "Kurde","zh": "库尔德语","zt": "庫爾德語"}','Kurdî/كوردی','ltr');
INSERT INTO languageTable VALUES(82,'lo','{"en":"Lao","es":"Laosiano", "ja":"ラーオ語","fr": "Laotien","zh": "老挝语","zt": "老撾語"}','Lao','ltr');
INSERT INTO languageTable VALUES(83,'la','{"en":"Latin","es":"Latín", "ja":"ラテン語","fr": "Latin","zh": "拉丁语","zt": "拉丁語"}','Latina','ltr');
INSERT INTO languageTable VALUES(84,'lv','{"en":"Latvian","es":"Letón", "ja":"ラトビア語","fr": "Letton","zh": "拉托维亚语","zt": "拉脫維亞語"}','Latviešu','ltr');
INSERT INTO languageTable VALUES(85,'li','{"en":"Limburgian","es":"Limburgués", "ja":"リンブルフ語","fr": "Limbourgeois","zh": "林堡语","zt": "林堡語"}','Limburgs','ltr');
INSERT INTO languageTable VALUES(86,'ln','{"en":"Lingala","es":"Lingala", "ja":"リンガラ語","fr": "Lingala","zh": "林加拉语","zt": "林加拉語"}','Lingala','ltr');
INSERT INTO languageTable VALUES(87,'lt','{"en":"Lithuanian","es":"Lituano", "ja":"リトアニア語","fr": "Lituanien","zh": "立陶宛语","zt": "立陶宛語"}','Lietuvių','ltr');
INSERT INTO languageTable VALUES(88,'jb','{"en":"Lojban","es":"Lojban", "ja":"ロジバン","fr": "Lojban","zh": "逻辑语","zt": "邏輯語"}','Lojban','ltr');
INSERT INTO languageTable VALUES(89,'nd','{"en":"Low Saxon","es":"Ndebele Septentrional", "ja":"低ザクセン語","fr": "Bas allemand","zh": "低地撒克逊语","zt": "低撒克遜語"}','Plattdüütsch','ltr');
INSERT INTO languageTable VALUES(90,'lb','{"en":"Luxembourgish","es":"Luxemburgués", "ja":"ルクセンブルク語","fr": "Luxembourgeois","zh": "卢森堡语","zt": "盧森堡語"}','Lëtzebuergesch','ltr');
INSERT INTO languageTable VALUES(91,'mk','{"en":"Macedonian","es":"Macedonio", "ja":"マケドニア語","fr": "Macédonien","zh": "马其顿语","zt": "馬其頓語"}','Македонски','ltr');
INSERT INTO languageTable VALUES(92,'mg','{"en":"Malagasy","es":"Malgache", "ja":"マダガスカル語","fr": "Malgache","zh": "马达加斯加语","zt": "馬爾加什語"}','Malagasy','ltr');
INSERT INTO languageTable VALUES(93,'ms','{"en":"Malay","es":"Malayo", "ja":"マレー語","fr": "Malais","zh": "马来语","zt": "馬來語"}','Bahasa Melayu','ltr');
INSERT INTO languageTable VALUES(94,'ml','{"en":"Malayalam","es":"Malayalam", "ja":"マラヤーラム語","fr": "Malayalam","zh": "马拉雅拉姆语","zt": "馬拉雅拉姆語"}','Malayalam','ltr');
INSERT INTO languageTable VALUES(95,'mt','{"en":"Maltese","es":"Maltés", "ja":"マルタ語","fr": "Maltais","zh": "马尔他语","zt": "馬耳他語"}','bil-Malti','ltr');
INSERT INTO languageTable VALUES(96,'gv','{"en":"Manx","es":"Gaélicomanés", "ja":"マン島語","fr": "Mannois","zh": "马恩岛语","zt": "馬恩島語"}','Gaelg','ltr');
INSERT INTO languageTable VALUES(97,'mi','{"en":"Maori","es":"Maorí", "ja":"マオリ語","fr": "Maori","zh": "毛利语","zt": "毛利語"}','Māori','ltr');
INSERT INTO languageTable VALUES(98,'mr','{"en":"Marathi","es":"Marathi", "ja":"マラーティー語","fr": "Marathi","zh": "马拉地语","zt": "馬拉地語"}','मराठी','ltr');
INSERT INTO languageTable VALUES(99,'mh','{"en":"Marshallese","es":"Marshalés", "ja":"マーシャル語","fr": "Marshallais","zh": "马绍尔语","zt": "馬紹爾語"}','Ebon','ltr');
INSERT INTO languageTable VALUES(100,'zm','{"en":"Min Nan","es":"Min Nan", "ja":"閩南語","fr": "Minnan","zh": "闽南语","zt": "閩南語"}','Bân-lâm-gú','ltr');
INSERT INTO languageTable VALUES(101,'mo','{"en":"Moldovan","es":"Moldavo", "ja":"モルドバ語","fr": "Moldave","zh": "摩尔多瓦语","zt": "摩爾多瓦語"}','Moldoveana','ltr');
INSERT INTO languageTable VALUES(102,'mn','{"en":"Mongolian","es":"Mongol", "ja":"モンゴル語","fr": "Mongol","zh": "蒙古语","zt": "蒙語"}','Монгол','ltr');
INSERT INTO languageTable VALUES(103,'nh','{"en":"Nahuatl","es":"Náhuatl", "ja":"ナワトル語","fr": "Nahuatl","zh": "纳瓦特语","zt": "納瓦特爾語"}','Nahuatl','ltr');
INSERT INTO languageTable VALUES(104,'na','{"en":"Nauruan","es":"Nauruano", "ja":"ナウル語","fr": "Nauruan","zh": "瑙鲁语","zt": "瑙魯語"}','dorerin Naoero','ltr');
INSERT INTO languageTable VALUES(105,'ne','{"en":"Nepali","es":"Nepalí", "ja":"ネパール語","fr": "Népalais","zh": "尼泊尔语","zt": "尼泊爾語"}','नेपाली','ltr');
INSERT INTO languageTable VALUES(106,'no','{"en":"Norwegian (Bokmål)","es":"Noruego", "ja":"ノルウェー語（ブークモール）","fr": "Norvégien (Bokmål)","zh": "挪威（挪威語）","zt": "挪威（挪威語）"}','Norsk(Bokmål)','ltr');
INSERT INTO languageTable VALUES(107,'nn','{"en":"Norwegian (Nynorsk)","es":"Nynorsknoruego", "ja":"ノルウェー語（ニーノシュク）","fr": "Norvégien (Nynorsk)","zh": "挪威（尼诺斯克语）","zt": "挪威（尼諾斯克語）"}','Nynorsk','ltr');
INSERT INTO languageTable VALUES(108,'oc','{"en":"Occitan","es":"Occitano", "ja":"オック語","fr": "Occitan","zh": "奥克语","zt": "奧克語"}','Occitan','ltr');
INSERT INTO languageTable VALUES(109,'or','{"en":"Oriya","es":"Oriya", "ja":"オリヤー語","fr": "Oriya","zh": "奥里亚语","zt": "奧里亞語"}','Oriya','ltr');
INSERT INTO languageTable VALUES(110,'om','{"en":"Oromo","es":"Oromo", "ja":"オロモ語","fr": "Oromo","zh": "奥罗莫语","zt": "奧羅莫語"}','Oromoo','ltr');
INSERT INTO languageTable VALUES(111,'pi','{"en":"Pali","es":"Pali", "ja":"パーリ語","fr": "Pali","zh": "巴利语","zt": "巴利語"}','पािऴ','ltr');
INSERT INTO languageTable VALUES(112,'ps','{"en":"Pashto","es":"Pashto", "ja":"パシュトー語","fr": "Pachto","zh": "普什图语","zt": "普什圖語"}','پښتو','rtl');
INSERT INTO languageTable VALUES(113,'fa','{"en":"Persian","es":"Persa", "ja":"ペルシア語","fr": "Persan","zh": "波斯语","zt": "波斯語"}','فارسی','rtl');
INSERT INTO languageTable VALUES(114,'pl','{"en":"Polish","es":"Polaco", "ja":"ポーランド語","fr": "Polonais","zh": "波兰语","zt": "波蘭語"}','Polski','ltr');
INSERT INTO languageTable VALUES(115,'pt','{"en":"Portuguese","es":"Portugués", "ja":"ポルトガル語","fr": "Portugais","zh": "葡萄牙语","zt": "葡萄牙語"}','Português','ltr');
INSERT INTO languageTable VALUES(116,'pa','{"en":"Punjabi","es":"Punjabí", "ja":"パンジャブ語","fr": "Pendjabi","zh": "旁遮普语","zt": "旁遮普語"}','ਪੰਜਾਬੀ','ltr');
INSERT INTO languageTable VALUES(117,'qu','{"en":"Quechua","es":"Quechua", "ja":"ケチュア語","fr": "Quechua","zh": "盖丘亚语","zt": "克丘亞語"}','Runa Simi','ltr');
INSERT INTO languageTable VALUES(118,'rm','{"en":"Raeto Romance","es":"Retorrománico", "ja":"レトロマン語","fr": "Rhéto-roman","zh": "罗曼斯方言","zt": "羅曼斯方言"}','Rumantsch','ltr');
INSERT INTO languageTable VALUES(119,'ro','{"en":"Romanian","es":"Rumano", "ja":"ルーマニア語","fr": "Roumain","zh": "罗马尼亚语","zt": "羅馬尼亞語"}','Română','ltr');
INSERT INTO languageTable VALUES(120,'ru','{"en":"Russian","es":"Ruso", "ja":"ロシア語","fr": "Russe","zh": "俄语","zt": "俄語"}','Русский','ltr');
INSERT INTO languageTable VALUES(121,'rw','{"en":"Rwandi","es":"Kinyarwanda", "ja":"Rwandi"}','Kinyarwanda','ltr');
INSERT INTO languageTable VALUES(122,'sm','{"en":"Samoan","es":"Samoano", "ja":"サモア語","fr": "Samoan","zh": "萨摩亚语","zt": "薩摩亞語"}','Gagana Samoa','ltr');
INSERT INTO languageTable VALUES(123,'sg','{"en":"Sango","es":"Sango", "ja":"サンゴ語","fr": "Sango","zh": "桑戈语","zt": "桑戈語"}','Sängö','ltr');
INSERT INTO languageTable VALUES(124,'sa','{"en":"Sanskrit","es":"Sánscrito", "ja":"サンスクリット語","fr": "Sanskrit","zh": "梵语","zt": "梵語"}','संस्कृतम्','ltr');
INSERT INTO languageTable VALUES(125,'sc','{"en":"Sardinian","es":"Sardo", "ja":"サルディーニャ語","fr": "Sarde","zh": "萨丁尼亚语","zt": "薩丁尼亞語"}','Sardu','ltr');
INSERT INTO languageTable VALUES(126,'gd','{"en":"Scottish Gaelic","es":"Gaélico Escocés", "ja":"スコットランド・ゲール語","fr": "Gaélique écossais","zh": "苏格兰盖尔语","zt": "蘇格蘭蓋爾語"}','Gàidhlig','ltr');
INSERT INTO languageTable VALUES(127,'sr','{"en":"Serbian","es":"Serbio", "ja":"セルビア語","fr": "Serbe","zh": "塞尔维亚语","zt": "塞爾維亞語"}','Српски/Srpski','ltr');
INSERT INTO languageTable VALUES(128,'sh','{"en":"Serbo-Croatian","es":"Serbocroata", "ja":"セルビア・クロアチア語","zh": "塞尔维亚-克罗地亚语","zt": "塞爾維亞 - 克羅地亞語"}','Srpskohrvatski','ltr');
INSERT INTO languageTable VALUES(129,'tn','{"en":"Setswana","es":"Setchwana", "ja":"ツワナ語","fr": "Tswana","zh": "茨瓦纳语","zt": "茨瓦納語"}','Setswana','ltr');
INSERT INTO languageTable VALUES(130,'sn','{"en":"Shona","es":"Shona", "ja":"ショナ語","fr": "Shona","zh": "修那语","zt": "紹納語"}','chi Shona','ltr');
INSERT INTO languageTable VALUES(131,'sb','{"en":"Sicilian","es":"Siciliano", "ja":"シチリア語","fr": "Sicilien","zh": "西西里语","zt": "西西里島語"}','Sicilianu','ltr');
INSERT INTO languageTable VALUES(132,'se','{"en":"Simple English","es":"Inglés simplificado", "ja":"ベーシック英語"}','Simple English','ltr');
INSERT INTO languageTable VALUES(133,'sd','{"en":"Sindhi","es":"Sindhi", "ja":"シンド語","fr": "Sindhi","zh": "信德语","zt": "信德語"}','سنڌي','rtl');
INSERT INTO languageTable VALUES(134,'si','{"en":"Sinhalese","es":"Cingalés", "ja":"シンハラ語","fr": "Cingalais","zh": "僧伽罗语","zt": "僧伽羅語"}','Sinhalese','ltr');
INSERT INTO languageTable VALUES(135,'sk','{"en":"Slovak","es":"Eslovaco", "ja":"スロバキア語","fr": "Slovaque","zh": "斯洛伐克语","zt": "斯洛伐克語"}','Slovenčina','ltr');
INSERT INTO languageTable VALUES(136,'sl','{"en":"Slovenian","es":"Esloveno", "ja":"スロベニア語","fr": "Slovène","zh": "斯洛法尼亚","zt": "斯洛文尼亞語"}','Slovenščina','ltr');
INSERT INTO languageTable VALUES(137,'so','{"en":"Somali","es":"Somalí", "ja":"ソマリ語","fr": "Somali","zh": "索马里语","zt": "索馬里語"}','Soomaaliga','ltr');
INSERT INTO languageTable VALUES(138,'st','{"en":"Southern Sotho","es":"Sesotho", "ja":"Southern Sotho","fr": "Sotho du Sud","zh": "南索托语","zt": "南索托語"}','Sesotho','ltr');
INSERT INTO languageTable VALUES(139,'es','{"en":"Spanish","es":"Español", "ja":"スペイン語","fr": "Espagnol","zh": "西班牙语","zt": "西班牙語"}','Español','ltr');
INSERT INTO languageTable VALUES(140,'su','{"en":"Sundanese","es":"Sundanés", "ja":"スンダ語","fr": "Soundanais","zh": "苏丹语","zt": "蘇丹語"}','Basa Sunda','ltr');
INSERT INTO languageTable VALUES(141,'sw','{"en":"Swahili","es":"Swahili", "ja":"スワヒリ語","fr": "Swahili","zh": "斯瓦希里语","zt": "斯瓦希裡語"}','Kiswahili','ltr');
INSERT INTO languageTable VALUES(142,'ss','{"en":"Swati","es":"Siswati", "ja":"スワティ語","fr": "Swati","zh": "斯瓦特语","zt": "斯瓦特語"}','Si Swati','ltr');
INSERT INTO languageTable VALUES(143,'sv','{"en":"Swedish","es":"Sueco", "ja":"スウェーデン語","fr": "Suédois","zh": "瑞典语","zt": "瑞典語"}','Svenska','ltr');
INSERT INTO languageTable VALUES(144,'tl','{"en":"Tagalog","es":"Tagalo", "ja":"タガログ語","fr": "Tagalog","zh": "菲律宾语","zt": "菲律賓語"}','Tagalog','ltr');
INSERT INTO languageTable VALUES(145,'tg','{"en":"Tajik","es":"Tayiko", "ja":"タジク語","fr": "Tadjik","zh": "塔吉克语","zt": "塔吉克語"}','Тоҷикӣ','ltr');
INSERT INTO languageTable VALUES(146,'ta','{"en":"Tamil","es":"Tamil", "ja":"タミル語","fr": "Tamoul","zh": "泰米尔语","zt": "泰米爾語"}','தமிழ்','ltr');
INSERT INTO languageTable VALUES(147,'tt','{"en":"Tatar","es":"Tártaro", "ja":"タタール語","fr": "Tatar","zh": "鞑靼语","zt": "韃靼語"}','Tatarça/Татарча','ltr');
INSERT INTO languageTable VALUES(148,'te','{"en":"Telugu","es":"Telugu", "ja":"テルグ語","fr": "Télougou","zh": "泰卢固语","zt": "泰盧固語"}','తెలుగు','ltr');
INSERT INTO languageTable VALUES(149,'th','{"en":"Thai","es":"Tailandés", "ja":"タイ語","fr": "Thaï","zh": "泰语","zt": "泰語"}','ไทย','ltr');
INSERT INTO languageTable VALUES(150,'bo','{"en":"Tibetan","es":"Tibetano", "ja":"チベット語","fr": "Tibétain","zh": "藏语","zt": "藏語"}','Bodskad','ltr');
INSERT INTO languageTable VALUES(151,'ti','{"en":"Tigrinya","es":"Tegriña", "ja":"ティグリニア語","fr": "Tigrigna","zh": "提格里尼亚语","zt": "蒂格里亞語"}','Tigrinya','ltr');
INSERT INTO languageTable VALUES(152,'tp','{"en":"Tok Pisin","es":"Tok Pisin", "ja":"トク・ピシン語","fr": "Tok pisin","zh": "巴布亚皮钦语","zt": "巴布亞皮欽語"}','Tok Pisin','ltr');
INSERT INTO languageTable VALUES(153,'tq','{"en":"Tokipona","es":"Tokipona", "ja":"トキポナ","fr": "Toki pona","zh": "道本语","zt": "道本語"}','Tokipona','ltr');
INSERT INTO languageTable VALUES(154,'to','{"en":"Tongan","es":"Tonga (islas tonga)", "ja":"トンガ語","fr": "Tongien","zh": "汤加语","zt": "湯加語"}','Faka Tonga','ltr');
INSERT INTO languageTable VALUES(155,'ts','{"en":"Tsonga","es":"Tsonga", "ja":"Tsonga","fr": "Tsonga","zh": "特松加语","zt": "特松加語"}','Xitsonga','ltr');
INSERT INTO languageTable VALUES(156,'tr','{"en":"Turkish","es":"Turco", "ja":"トルコ語","fr": "Turc","zh": "土耳其语","zt": "土耳其語"}','Türkçe','ltr');
INSERT INTO languageTable VALUES(157,'tk','{"en":"Turkmen","es":"Turcomano", "ja":"トルクメン語","fr": "Turkmène","zh": "土库曼语","zt": "土庫曼語"}','تركمن/Туркмен','ltr');
INSERT INTO languageTable VALUES(158,'tw','{"en":"Twi","es":"Twi", "ja":"トウィ語","fr": "Twi","zh": "多威语","zt": "多威語"}','Twi','ltr');
INSERT INTO languageTable VALUES(159,'uk','{"en":"Ukrainian","es":"Ucraniano", "ja":"ウクライナ語","fr": "Ukrainien","zh": "乌克兰语","zt": "烏克蘭語"}','Українська','ltr');
INSERT INTO languageTable VALUES(160,'ur','{"en":"Urdu","es":"Urdu", "ja":"ウルドゥー語","fr": "Ourdou","zh": "乌尔都语","zt": "烏爾都語"}','اڙدو','rtl');
INSERT INTO languageTable VALUES(161,'ug','{"en":"Uyghur","es":"Uigur", "ja":"ウイグル語","fr": "Ouïghour","zh": "维吾尔语","zt": "維吾爾語"}','Oyghurque','ltr');
INSERT INTO languageTable VALUES(162,'uz','{"en":"Uzbek","es":"Uzbeko", "ja":"ウズベク語","fr": "Ouzbek","zh": "乌兹别克语","zt": "烏茲別克語"}','O‘zbek','ltr');
INSERT INTO languageTable VALUES(163,'vi','{"en":"Vietnamese","es":"Vietnamita", "ja":"ベトナム語","fr": "Vietnamien","zh": "越南语","zt": "越南語"}','TiếngViệt','ltr');
INSERT INTO languageTable VALUES(164,'vo','{"en":"Volapük","es":"Volapük", "ja":"ヴォラピュク","fr": "Volapük","zh": "沃拉普克语","zt": "沃拉普克語"}','Volapük','ltr');
INSERT INTO languageTable VALUES(165,'wa','{"en":"Walloon","es":"Valón", "ja":"ワロン語","fr": "Wallon","zh": "瓦龙语","zt": "華隆語"}','Walon','ltr');
INSERT INTO languageTable VALUES(166,'cy','{"en":"Welsh","es":"Galés", "ja":"ウェールズ語","fr": "Gallois","zh": "威尔士语","zt": "威爾士語"}','Cymraeg','ltr');
INSERT INTO languageTable VALUES(167,'fy','{"en":"WestFrisian","es":"Frisón", "ja":"西フリジア語","fr": "Frison occidental","zh": "西部弗里西亚语","zt": "西部弗里西亞語"}','Frysk','ltr');
INSERT INTO languageTable VALUES(168,'wo','{"en":"Wolof","es":"Uolof", "ja":"ウォロフ語","fr": "Wolof","zh": "沃洛夫语","zt": "沃洛夫語"}','Wollof','ltr');
INSERT INTO languageTable VALUES(169,'xh','{"en":"Xhosan","es":"Xhosa", "ja":"ホサ語","fr": "Xhosa","zh": "科萨语","zt": "科薩語"}','isiXhosa','ltr');
INSERT INTO languageTable VALUES(170,'yi','{"en":"Yiddish","es":"Yidis", "ja":"イディッシュ語","fr": "Yiddish","zh": "意第绪语","zt": "意第緒語"}','ייִדיש','rtl');
INSERT INTO languageTable VALUES(171,'yo','{"en":"Yoruba","es":"Yoruba", "ja":"ヨルバ語","fr": "Yoruba","zh": "约鲁巴语","zt": "約魯巴語"}','Yorùbá','ltr');
INSERT INTO languageTable VALUES(172,'za','{"en":"Zhuang","es":"Zhuang", "ja":"チワン語","fr": "Zhuang","zh": "壮语","zt": "壯語"}','Cuengh','ltr');
INSERT INTO languageTable VALUES(173,'zu','{"en":"Zulu","es":"Zulú", "ja":"ズールー語","fr": "Zoulou","zh": "祖鲁语","zt": "祖魯語"}','isiZulu','ltr');
INSERT INTO languageTable VALUES(174,'zt','{"en":"Chinese(繁體)","es":"Chino tradicionál", "ja":"中国語（繁体字）","fr": "Chinois(繁體)","zh": "繁体中文","zt": "繁體中文"}','繁體中文','ltr');
INSERT INTO languageTable VALUES(175,'mu','{"en":"Karaoke","es":"Karaoke", "ja":"カラオケ","fr": "Karaoké","zh": "卡拉Ok","zt": "卡拉OK"}','Karaoke','ltr');
INSERT INTO languageTable VALUES(176,'udm','{"en":"Udmurt","es":"Udmurto", "ja":"ウドムルト語","fr": "Oudmourte","zh": "乌德穆尔特语","zt": "烏德穆爾特語"}','УдмуртЭлькун','ltr');
INSERT INTO languageTable VALUES(177,'han','{"en":"Xiang","es":"Xiang", "ja":"湘語","fr": "Xiang","zh": "湘语","zt": "湘語"}','湖南话','ltr');
INSERT INTO languageTable VALUES(178,'hak','{"en":"Hakka","es":"Hakka", "ja":"客家語","fr": "Hakka","zh": "客家语","zt": "客家語"}','客家','ltr');
INSERT INTO languageTable VALUES(179,'bho','{"en":"Bhojpuri","es":"Bhojpuri", "ja":"ポージブリー語","fr": "Bhodjpouri","zh": "博杰普尔语","zt": "博傑普爾語"}','भोजपुरी','ltr');
INSERT INTO languageTable VALUES(180,'mai','{"en":"Maithili","es":"Maithili", "ja":"マイティリー語","fr": "Maïthili","zh": "迈蒂利语","zt": "邁蒂利語"}','मैथिली','ltr');
INSERT INTO languageTable VALUES(181,'ful','{"en":"Fula","es":"Fula", "ja":"フラ語","fr": "Peul","zh": "富拉语","zt": "富拉語"}','Fula','ltr');
INSERT INTO languageTable VALUES(182,'ibo','{"en":"Igbo","es":"Igbo", "ja":"イボ語","fr": "Igbo","zh": "伊博语","zt": "伊博語"}','Igbo','ltr');
INSERT INTO languageTable VALUES(183,'gan','{"en":"Gan","es":"Gan", "ja":"カン語","fr": "Gan","zh": "赣语","zt": "贛語"}','贛語','ltr');
INSERT INTO languageTable VALUES(184,'ceb','{"en":"Cebuano/Binisaya","es":"Cebuano/Bisaya", "ja":"セブアノ語","fr": "Cebuano/Binisaya","zh": "宿霧语","zt": "宿務語"}','Binisaya','ltr');
INSERT INTO languageTable VALUES(185,'skr','{"en":"Saraiki","es":"Saraiki", "ja":"サライキ語","fr": "Seraiki","zh": "西莱基语","zt": "西萊基語"}','سرائیکی','ltr');
INSERT INTO languageTable VALUES(186,'ctg','{"en":"Chittagonian","es":"Chittagonian", "ja":"チッタゴン語","fr": "Chittagonien","zh": "吉大港语","zt": "吉大港語"}','টগাঁইয়াবুলি','ltr');
INSERT INTO languageTable VALUES(187,'mad','{"en":"Madurese","es":"Madurés", "ja":"マドゥラ語","fr": "Madurais","zh": "马都拉语","zt": " 馬都拉語"}','بَهاسَمَدورا','ltr');
INSERT INTO languageTable VALUES(188,'bgc','{"en":"Haryanvi","es":"Haryanvi", "ja":"ハリヤーンウィー語","fr": "Haryanvi","zh": "哈里亚纳语","zt": "哈里亞納語"}','हरियाणवी','ltr');
INSERT INTO languageTable VALUES(189,'mwr','{"en":"Marwari","es":"Marwari", "ja":"マールワーリー語","fr": "Marwari","zh": "马尔尼里语","zt": "馬爾尼里語"}','मारवाड़ी','ltr');
INSERT INTO languageTable VALUES(190,'hne','{"en":"Chhattisgarhi","es":"Chhattisgarhi", "ja":"チャッティースガリー語 ","fr": "Chhattisgarhi","zh": "恰蒂斯加尔语","zt": "恰蒂斯加爾語"}','छत्तीसगढ़ी','ltr');
INSERT INTO languageTable VALUES(191,'nya','{"en":"Chewa/Nyanja","es":"Chewa/Nyanja", "ja":"チェワ語/ニャンジャ語","fr": "Chichewa/Nyanja","zh": "齐切瓦/尼昂加语","zt": "齊切瓦/尼昂加語"}','Nyanja','ltr');
INSERT INTO languageTable VALUES(192,'dcc','{"en":"Dakhini","es":"Dakani", "ja":"ダーキニー語","fr": "Dakhini","zh": "乌尔都语","zt": "烏爾都語"}','دکنی‎','ltr');
INSERT INTO languageTable VALUES(193,'mnp','{"en":"Min Bei","es":"Min Bei", "ja":"閩北語","fr": "Minbei","zh": "闽北语","zt": "閩北語"}','闽北语','ltr');
INSERT INTO languageTable VALUES(194,'cdo','{"en":"Min Dong","es":"Min Dong", "ja":"閩東語","fr": "Mindong","zh": "闽东语","zt": "閩東語"}','閩東語','ltr');
INSERT INTO languageTable VALUES(195,'syl','{"en":"Sylheti","es":"Sylheti", "ja":"シロティ語","fr": "Sylheti","zh": "斯列特语","zt": "斯列特語"}','ছিলটী','ltr');
INSERT INTO languageTable VALUES(196,'kin','{"en":"Kinyarwanda","es":"Kinyarwanda", "ja":"ルワンダ語","fr": "Kinyarwanda","zh": "卢旺达语","zt": "盧旺達語"}','Ikinyarwanda','ltr');
INSERT INTO languageTable VALUES(197,'hat','{"en":"Haitian Creole","es":"Criollo Haitiano", "ja":"ハイチ・クレオール語","fr": "Créole haïtien","zh": "海地克里奥尔语","zt": "海地克里奧爾語"}','Kreyòlayisyen','ltr');
INSERT INTO languageTable VALUES(198,'ilo','{"en":"Ilokano","es":"Ilocano", "ja":"イロカノ語","fr": "Ilocano","zh": "伊洛卡诺语","zt": "伊洛卡諾語"}','Ilokano','ltr');
INSERT INTO languageTable VALUES(199,'mos','{"en":"Mossi","es":"Moré", "ja":"モシ語","fr": "Moré","zh": "莫西语","zt": "莫西語"}','Mòoré','ltr');
INSERT INTO languageTable VALUES(200,'bal','{"en":"Balochi","es":"Baluchi", "ja":"バルーチー語","fr": "Baloutche","zh": "俾路支语","zt": "俾路支語"}','بلوچی','ltr');
INSERT INTO languageTable VALUES(201,'kok','{"en":"Konkani","es":"Konkaní", "ja":"コンカニ語","fr": "Konkani","zh": "孔卡尼语","zt": "孔卡尼語"}','कोंकणी','ltr');
INSERT INTO languageTable VALUES(202,'zom','{"en":"Zomi","es":"Zomi", "ja":"ゾミ語","fr": "Zomi","zh": "梭米语","zt": "梭米語"}','Zomi','ltr');
INSERT INTO languageTable VALUES(203,'lol','{"en":"lolspeak","es":"lolspeak", "ja":"lolspeak","fr": "lolspeak","zh": "lolspeak","zt": "lolspeak"}','lolspeak','ltr');
INSERT INTO languageTable VALUES(204,'foi','{"en":"Foe","ja":"フォイ語","es":"Foe","fr":"Foe","zh": "巴布亚新几内亚语","zt": "巴布亞新幾內亞語"}','Foi','ltr');
INSERT INTO languageTable VALUES(205,'hru','{"en":"Hruso","ja":"フルソ語","es":"Hruso","fr":"Hruso","zh": "赫鲁索-阿卡语","zt": "赫魯索 - 阿卡語"}','Hruso','ltr');
INSERT INTO languageTable VALUES(206,'huh','{"en":"Huilliche","ja":"ウィリチェ語","es":"Huilliche","fr":"Huilliche","zh": "惠里切语","zt": "惠裡切語"}','Huilliche','ltr');
INSERT INTO languageTable VALUES(207,'xal','{"en":"Kalmyk","ja":"カルムイク語","es":"Kalmyk","fr":"Kalmouk","zh": "卡尔梅克语","zt": "卡爾梅克語"}','Kalmyk','ltr');
INSERT INTO languageTable VALUES(208,'kim','{"en":"Tofa","ja":"トファ語","es":"Tofa","fr":"Tofalar","zh": "托法语","zt": "托法語"}','тоъфá','ltr');
INSERT INTO languageTable VALUES(209,'tzx','{"en":"Yokoim","ja":"ヨコイム語","es":"Yokoim","fr":"Yokoim","zh": "优基姆语","zt": "優基姆語"}','Yokoim','ltr');
INSERT INTO languageTable VALUES(210,'mkj','{"en":"Mokilese","ja":"モキル語","es":"Mokilese","fr":"Mokil","zh": "莫基尔语","zt": "莫基爾語"}','Mokilese','ltr');
INSERT INTO languageTable VALUES(211,'sat','{"en":"Santhali","ja":"サンタル語","es":"Santhali","fr":"Santali","zh": "桑萨利语","zt": "桑薩利語"}','Santhali','ltr');
INSERT INTO languageTable VALUES(212,'wnw','{"en":"Winnemem Wintu","ja":"ウィネメム・ウィントゥ語","es":"Winnemem Wintu","fr":"Winnemem Wintu","zh": "温图语","zt": "溫圖語"}','Winnemem Wintu','ltr');
INSERT INTO languageTable VALUES(213,'mne','{"en":"Montenegrin","ja":"モンテネグロ語","es":"Montenegrina","fr":"Monténégrin","zh": "黑山语","zt": "黑山語"}','црногорски','ltr');