.class public Lcom/viki/android/u3/u2;
.super Landroidx/fragment/app/c;
.source "SourceFile"


# instance fields
.field private l:Landroid/widget/EditText;

.field private m:Landroid/view/View;

.field private n:Landroid/view/View;

.field private o:Landroid/view/View;

.field private p:Lcom/google/android/material/textfield/TextInputLayout;

.field private q:Lj/b/z/a;

.field private r:Ljava/lang/String;


# direct methods
.method public constructor <init>()V
    .locals 1

    .line 1
    invoke-direct {p0}, Landroidx/fragment/app/c;-><init>()V

    .line 2
    new-instance v0, Lj/b/z/a;

    invoke-direct {v0}, Lj/b/z/a;-><init>()V

    iput-object v0, p0, Lcom/viki/android/u3/u2;->q:Lj/b/z/a;

    return-void
.end method

.method private L()V
    .locals 3

    .line 1
    new-instance v0, Ljava/util/HashMap;

    invoke-direct {v0}, Ljava/util/HashMap;-><init>()V

    .line 2
    iget-object v1, p0, Lcom/viki/android/u3/u2;->r:Ljava/lang/String;

    const-string v2, "trigger"

    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    const-string v1, "page"

    const-string v2, "vikipass_page"

    .line 3
    invoke-virtual {v0, v1, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    const-string v1, "send_verification_email_popup"

    .line 4
    invoke-static {v0, v1}, Lf/j/i/c;->d(Ljava/util/HashMap;Ljava/lang/String;)V

    return-void
.end method

.method private M()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a0272

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    .line 2
    new-instance v1, Lcom/viki/android/u3/e0;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/e0;-><init>(Lcom/viki/android/u3/u2;)V

    invoke-virtual {v0, v1}, Landroid/view/View;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    return-void
.end method

.method private N()V
    .locals 2

    .line 1
    invoke-static {}, Lf/j/a/i/c0;->v()Lf/j/a/i/c0;

    move-result-object v0

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    if-eqz v0, :cond_0

    .line 2
    invoke-virtual {v0}, Lcom/viki/library/beans/User;->getEmail()Ljava/lang/String;

    move-result-object v1

    invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v1

    if-nez v1, :cond_0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->isEmailAutogenerated()Z

    move-result v0

    if-nez v0, :cond_0

    .line 3
    iget-object v0, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    invoke-static {}, Lf/j/a/i/c0;->v()Lf/j/a/i/c0;

    move-result-object v1

    invoke-virtual {v1}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v1

    invoke-virtual {v1}, Lcom/viki/library/beans/User;->getEmail()Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Landroid/widget/EditText;->setText(Ljava/lang/CharSequence;)V

    :cond_0
    return-void
.end method

.method private O()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a028e

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    check-cast v0, Lcom/google/android/material/textfield/TextInputLayout;

    iput-object v0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    return-void
.end method

.method private P()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a038b

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    iput-object v0, p0, Lcom/viki/android/u3/u2;->o:Landroid/view/View;

    return-void
.end method

.method private Q()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    new-instance v1, Lcom/viki/android/u3/u2$a;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/u2$a;-><init>(Lcom/viki/android/u3/u2;)V

    invoke-virtual {v0, v1}, Landroid/widget/EditText;->addTextChangedListener(Landroid/text/TextWatcher;)V

    return-void
.end method

.method private R()V
    .locals 4

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a04fc

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    check-cast v0, Landroid/widget/TextView;

    .line 2
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getArguments()Landroid/os/Bundle;

    move-result-object v1

    const-string v2, "track_name"

    invoke-virtual {v1, v2}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v1

    const/4 v2, 0x1

    new-array v2, v2, [Ljava/lang/Object;

    const/4 v3, 0x0

    aput-object v1, v2, v3

    const v1, 0x7f110132

    .line 3
    invoke-virtual {p0, v1, v2}, Landroidx/fragment/app/Fragment;->getString(I[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V

    return-void
.end method

.method private S()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a00be

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    iput-object v0, p0, Lcom/viki/android/u3/u2;->m:Landroid/view/View;

    const/4 v1, 0x1

    .line 2
    invoke-virtual {v0, v1}, Landroid/view/View;->setClickable(Z)V

    .line 3
    iget-object v0, p0, Lcom/viki/android/u3/u2;->m:Landroid/view/View;

    new-instance v1, Lcom/viki/android/u3/c0;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/c0;-><init>(Lcom/viki/android/u3/u2;)V

    invoke-virtual {v0, v1}, Landroid/view/View;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    return-void
.end method

.method private T()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    const/4 v1, 0x1

    invoke-virtual {v0, v1}, Lcom/google/android/material/textfield/TextInputLayout;->setErrorEnabled(Z)V

    .line 2
    iget-object v0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    const v1, 0x7f11035c

    invoke-virtual {p0, v1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Lcom/google/android/material/textfield/TextInputLayout;->setError(Ljava/lang/CharSequence;)V

    return-void
.end method

.method private U()V
    .locals 2

    const-string v0, "send_verification_email_btn"

    const-string v1, "vikipass_page"

    .line 1
    invoke-static {v0, v1}, Lf/j/i/c;->a(Ljava/lang/String;Ljava/lang/String;)V

    return-void
.end method

.method private V()V
    .locals 2

    const-string v0, "verification_email_popup_dismiss"

    const-string v1, "vikipass_page"

    .line 1
    invoke-static {v0, v1}, Lf/j/i/c;->a(Ljava/lang/String;Ljava/lang/String;)V

    return-void
.end method

.method static synthetic a(Lcom/viki/android/u3/u2;)Landroid/widget/EditText;
    .locals 0

    .line 1
    iget-object p0, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    return-object p0
.end method

.method public static a(Ljava/lang/String;Ljava/lang/String;)Lcom/viki/android/u3/u2;
    .locals 3

    .line 2
    new-instance v0, Lcom/viki/android/u3/u2;

    invoke-direct {v0}, Lcom/viki/android/u3/u2;-><init>()V

    .line 3
    new-instance v1, Landroid/os/Bundle;

    invoke-direct {v1}, Landroid/os/Bundle;-><init>()V

    const-string v2, "trigger"

    .line 4
    invoke-virtual {v1, v2, p0}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V

    const-string p0, "track_name"

    .line 5
    invoke-virtual {v1, p0, p1}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V

    .line 6
    invoke-virtual {v0, v1}, Landroidx/fragment/app/Fragment;->setArguments(Landroid/os/Bundle;)V

    return-object v0
.end method

.method private a(Ljava/lang/String;)V
    .locals 1

    const-string v0, "change_email_error"

    .line 31
    invoke-static {v0, p1}, Lf/j/i/c;->d(Ljava/lang/String;Ljava/lang/String;)V

    return-void
.end method

.method static synthetic b(Lcom/viki/android/u3/u2;)Landroid/view/View;
    .locals 0

    .line 1
    iget-object p0, p0, Lcom/viki/android/u3/u2;->m:Landroid/view/View;

    return-object p0
.end method

.method private b(Ljava/lang/String;)V
    .locals 2

    .line 7
    iget-object v0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    const/4 v1, 0x1

    invoke-virtual {v0, v1}, Lcom/google/android/material/textfield/TextInputLayout;->setErrorEnabled(Z)V

    .line 8
    iget-object v0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getContext()Landroid/content/Context;

    move-result-object v1

    invoke-static {p1, v1}, Lcom/viki/android/utils/j1;->a(Ljava/lang/String;Landroid/content/Context;)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {v0, p1}, Lcom/google/android/material/textfield/TextInputLayout;->setError(Ljava/lang/CharSequence;)V

    return-void
.end method

.method static synthetic c(Lcom/viki/android/u3/u2;)V
    .locals 0

    .line 1
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->T()V

    return-void
.end method

.method private c(Ljava/lang/String;)V
    .locals 3

    .line 2
    iget-object v0, p0, Lcom/viki/android/u3/u2;->q:Lj/b/z/a;

    .line 3
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object v1

    invoke-static {v1}, Lcom/viki/android/s3/f;->a(Landroid/content/Context;)Lcom/viki/android/s3/a;

    move-result-object v1

    invoke-interface {v1}, Lcom/viki/android/s3/a;->p()Lf/j/f/b/h/e;

    move-result-object v1

    const/4 v2, 0x1

    .line 4
    invoke-virtual {v1, p1, v2}, Lf/j/f/b/h/e;->a(Ljava/lang/String;Z)Lj/b/a;

    move-result-object p1

    .line 5
    invoke-static {}, Lj/b/y/b/a;->a()Lj/b/s;

    move-result-object v1

    invoke-virtual {p1, v1}, Lj/b/a;->a(Lj/b/s;)Lj/b/a;

    move-result-object p1

    new-instance v1, Lcom/viki/android/u3/f0;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/f0;-><init>(Lcom/viki/android/u3/u2;)V

    .line 6
    invoke-virtual {p1, v1}, Lj/b/a;->b(Lj/b/b0/f;)Lj/b/a;

    move-result-object p1

    new-instance v1, Lcom/viki/android/u3/h0;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/h0;-><init>(Lcom/viki/android/u3/u2;)V

    .line 7
    invoke-virtual {p1, v1}, Lj/b/a;->c(Lj/b/b0/a;)Lj/b/a;

    move-result-object p1

    new-instance v1, Lcom/viki/android/u3/d0;

    invoke-direct {v1, p0}, Lcom/viki/android/u3/d0;-><init>(Lcom/viki/android/u3/u2;)V

    new-instance v2, Lcom/viki/android/u3/g0;

    invoke-direct {v2, p0}, Lcom/viki/android/u3/g0;-><init>(Lcom/viki/android/u3/u2;)V

    .line 8
    invoke-virtual {p1, v1, v2}, Lj/b/a;->a(Lj/b/b0/a;Lj/b/b0/f;)Lj/b/z/b;

    move-result-object p1

    .line 9
    invoke-virtual {v0, p1}, Lj/b/z/a;->b(Lj/b/z/b;)Z

    return-void
.end method

.method static synthetic d(Lcom/viki/android/u3/u2;)Lcom/google/android/material/textfield/TextInputLayout;
    .locals 0

    .line 1
    iget-object p0, p0, Lcom/viki/android/u3/u2;->p:Lcom/google/android/material/textfield/TextInputLayout;

    return-object p0
.end method


# virtual methods
.method public synthetic J()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/u3/u2;->o:Landroid/view/View;

    const/16 v1, 0x8

    invoke-virtual {v0, v1}, Landroid/view/View;->setVisibility(I)V

    return-void
.end method

.method public synthetic K()V
    .locals 3

    .line 1
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v0

    iget-object v1, p0, Lcom/viki/android/u3/u2;->r:Ljava/lang/String;

    const-string v2, "EmailVerificationDoneDialogFragment"

    invoke-static {v0, v2, v1}, Lcom/viki/android/utils/i1;->a(Landroidx/fragment/app/d;Ljava/lang/String;Ljava/lang/String;)V

    .line 2
    invoke-virtual {p0}, Landroidx/fragment/app/c;->E()V

    return-void
.end method

.method public a(Landroid/os/Bundle;)Landroid/app/Dialog;
    .locals 3
    .annotation build Landroid/annotation/SuppressLint;
        value = {
            "InflateParams"
        }
    .end annotation

    .line 7
    new-instance p1, Landroid/app/AlertDialog$Builder;

    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v0

    invoke-direct {p1, v0}, Landroid/app/AlertDialog$Builder;-><init>(Landroid/content/Context;)V

    .line 8
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v0

    const-string v1, "layout_inflater"

    invoke-virtual {v0, v1}, Landroid/app/Activity;->getSystemService(Ljava/lang/String;)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Landroid/view/LayoutInflater;

    const v1, 0x7f0d00a3

    const/4 v2, 0x0

    .line 9
    invoke-virtual {v0, v1, v2}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;)Landroid/view/View;

    move-result-object v0

    iput-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    .line 10
    invoke-virtual {p1, v0}, Landroid/app/AlertDialog$Builder;->setView(Landroid/view/View;)Landroid/app/AlertDialog$Builder;

    .line 11
    iget-object v0, p0, Lcom/viki/android/u3/u2;->n:Landroid/view/View;

    const v1, 0x7f0a01e4

    invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;

    move-result-object v0

    check-cast v0, Landroid/widget/EditText;

    iput-object v0, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    .line 12
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getArguments()Landroid/os/Bundle;

    move-result-object v0

    const-string v1, "trigger"

    invoke-virtual {v0, v1}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/viki/android/u3/u2;->r:Ljava/lang/String;

    .line 13
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->Q()V

    .line 14
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->P()V

    .line 15
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->S()V

    .line 16
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->M()V

    .line 17
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->R()V

    .line 18
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->O()V

    .line 19
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->N()V

    .line 20
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->L()V

    .line 21
    invoke-virtual {p1}, Landroid/app/AlertDialog$Builder;->create()Landroid/app/AlertDialog;

    move-result-object p1

    return-object p1
.end method

.method public synthetic a(Landroid/view/View;)V
    .locals 0

    .line 22
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->V()V

    .line 23
    invoke-virtual {p0}, Landroidx/fragment/app/c;->E()V

    return-void
.end method

.method public synthetic a(Lj/b/z/b;)V
    .locals 1

    .line 24
    iget-object p1, p0, Lcom/viki/android/u3/u2;->o:Landroid/view/View;

    const/4 v0, 0x0

    invoke-virtual {p1, v0}, Landroid/view/View;->setVisibility(I)V

    return-void
.end method

.method public synthetic a(Ljava/lang/Throwable;)V
    .locals 1

    .line 25
    instance-of v0, p1, Lf/j/d/d/a;

    if-eqz v0, :cond_0

    .line 26
    check-cast p1, Lf/j/d/d/a;

    invoke-virtual {p1}, Lf/j/d/d/a;->a()Ljava/lang/String;

    move-result-object p1

    .line 27
    invoke-direct {p0, p1}, Lcom/viki/android/u3/u2;->a(Ljava/lang/String;)V

    .line 28
    invoke-direct {p0, p1}, Lcom/viki/android/u3/u2;->b(Ljava/lang/String;)V

    goto :goto_0

    .line 29
    :cond_0
    invoke-virtual {p1}, Ljava/lang/Throwable;->getMessage()Ljava/lang/String;

    move-result-object p1

    invoke-direct {p0, p1}, Lcom/viki/android/u3/u2;->a(Ljava/lang/String;)V

    const-string p1, "7403"

    .line 30
    invoke-direct {p0, p1}, Lcom/viki/android/u3/u2;->b(Ljava/lang/String;)V

    :goto_0
    return-void
.end method

.method public synthetic b(Landroid/view/View;)V
    .locals 1

    .line 2
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->U()V

    .line 3
    iget-object p1, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    invoke-virtual {p1}, Landroid/widget/EditText;->getText()Landroid/text/Editable;

    move-result-object p1

    invoke-virtual {p1}, Ljava/lang/Object;->toString()Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p1}, Ljava/lang/String;->trim()Ljava/lang/String;

    move-result-object p1

    .line 4
    iget-object v0, p0, Lcom/viki/android/u3/u2;->l:Landroid/widget/EditText;

    invoke-static {v0}, Lcom/viki/android/ui/registration/o0;->b(Landroid/widget/EditText;)Z

    move-result v0

    if-nez v0, :cond_0

    .line 5
    invoke-direct {p0}, Lcom/viki/android/u3/u2;->T()V

    return-void

    .line 6
    :cond_0
    invoke-direct {p0, p1}, Lcom/viki/android/u3/u2;->c(Ljava/lang/String;)V

    return-void
.end method

.method public onDestroy()V
    .locals 1

    .line 1
    invoke-super {p0}, Landroidx/fragment/app/Fragment;->onDestroy()V

    .line 2
    iget-object v0, p0, Lcom/viki/android/u3/u2;->q:Lj/b/z/a;

    invoke-virtual {v0}, Lj/b/z/a;->c()V

    return-void
.end method
