.class public Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;
.super Lcom/viki/android/ui/settings/fragment/BasePreferenceFragment;
.source "SourceFile"


# instance fields
.field private final j:Lp/b/a/w/b;

.field k:Landroidx/preference/Preference;

.field l:Landroidx/preference/Preference;

.field m:Landroidx/preference/ListPreference;

.field n:Landroidx/preference/SwitchPreference;

.field private o:Lf/j/a/i/c0;

.field private p:Lf/j/f/b/h/g;

.field private q:Lf/j/f/b/h/c;

.field private r:Lj/b/z/a;


# direct methods
.method public constructor <init>()V
    .locals 2

    .line 1
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/BasePreferenceFragment;-><init>()V

    .line 2
    sget-object v0, Ljava/util/Locale;->US:Ljava/util/Locale;

    const-string v1, "dd/MM/yyyy"

    .line 3
    invoke-static {v1, v0}, Lp/b/a/w/b;->a(Ljava/lang/String;Ljava/util/Locale;)Lp/b/a/w/b;

    move-result-object v0

    iput-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->j:Lp/b/a/w/b;

    .line 4
    new-instance v0, Lj/b/z/a;

    invoke-direct {v0}, Lj/b/z/a;-><init>()V

    iput-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->r:Lj/b/z/a;

    return-void
.end method

.method private M()Ljava/lang/String;
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->isEmailAutogenerated()Z

    move-result v0

    if-nez v0, :cond_0

    .line 2
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->getEmail()Ljava/lang/String;

    move-result-object v0

    return-object v0

    :cond_0
    const/4 v0, 0x0

    return-object v0
.end method

.method private N()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    if-eqz v0, :cond_1

    .line 2
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    const/4 v1, 0x0

    if-nez v0, :cond_0

    .line 3
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->g(Z)V

    goto :goto_0

    .line 4
    :cond_0
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->f(Z)V

    .line 5
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    iget-object v1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->q:Lf/j/f/b/h/c;

    invoke-virtual {v1}, Lf/j/f/b/h/c;->a()Z

    move-result v1

    invoke-virtual {v0, v1}, Landroidx/preference/TwoStatePreference;->h(Z)V

    .line 6
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    new-instance v1, Lcom/viki/android/ui/settings/fragment/o;

    invoke-direct {v1, p0}, Lcom/viki/android/ui/settings/fragment/o;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->a(Landroidx/preference/Preference$d;)V

    :cond_1
    :goto_0
    return-void
.end method

.method private O()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    if-eqz v0, :cond_0

    .line 2
    new-instance v1, Lcom/viki/android/ui/settings/fragment/j;

    invoke-direct {v1, p0}, Lcom/viki/android/ui/settings/fragment/j;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->a(Landroidx/preference/Preference$e;)V

    :cond_0
    return-void
.end method

.method private P()V
    .locals 2

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    if-eqz v0, :cond_2

    .line 2
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    if-eqz v0, :cond_1

    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->p:Lf/j/f/b/h/g;

    invoke-virtual {v0}, Lf/j/f/b/h/g;->a()Lp/b/a/g;

    move-result-object v0

    if-nez v0, :cond_0

    goto :goto_0

    .line 3
    :cond_0
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->T()V

    .line 4
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    new-instance v1, Lcom/viki/android/ui/settings/fragment/q;

    invoke-direct {v1, p0}, Lcom/viki/android/ui/settings/fragment/q;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->a(Landroidx/preference/Preference$e;)V

    goto :goto_1

    .line 5
    :cond_1
    :goto_0
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    const/4 v1, 0x0

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->g(Z)V

    :cond_2
    :goto_1
    return-void
.end method

.method static synthetic Q()V
    .locals 0

    return-void
.end method

.method static synthetic R()V
    .locals 0

    return-void
.end method

.method private S()V
    .locals 5

    .line 1
    invoke-static {}, Lf/j/a/c/d/c;->c()Ljava/util/ArrayList;

    move-result-object v0

    .line 2
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    .line 3
    new-instance v2, Ljava/util/ArrayList;

    invoke-direct {v2}, Ljava/util/ArrayList;-><init>()V

    .line 4
    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :goto_0
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v3

    if-eqz v3, :cond_0

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v3

    check-cast v3, Lcom/viki/library/beans/Language;

    .line 5
    invoke-virtual {v3}, Lcom/viki/library/beans/Language;->getNativeName()Ljava/lang/String;

    move-result-object v4

    invoke-interface {v1, v4}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 6
    invoke-virtual {v3}, Lcom/viki/library/beans/Language;->getCode()Ljava/lang/String;

    move-result-object v3

    invoke-interface {v2, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    goto :goto_0

    .line 7
    :cond_0
    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v0

    new-array v0, v0, [Ljava/lang/CharSequence;

    .line 8
    invoke-interface {v1, v0}, Ljava/util/List;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;

    .line 9
    invoke-interface {v2}, Ljava/util/List;->size()I

    move-result v1

    new-array v1, v1, [Ljava/lang/CharSequence;

    .line 10
    invoke-interface {v2, v1}, Ljava/util/List;->toArray([Ljava/lang/Object;)[Ljava/lang/Object;

    .line 11
    iget-object v2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    invoke-virtual {v2, v0}, Landroidx/preference/ListPreference;->a([Ljava/lang/CharSequence;)V

    .line 12
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    invoke-virtual {v0, v1}, Landroidx/preference/ListPreference;->b([Ljava/lang/CharSequence;)V

    return-void
.end method

.method private T()V
    .locals 3

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->p:Lf/j/f/b/h/g;

    invoke-virtual {v0}, Lf/j/f/b/h/g;->a()Lp/b/a/g;

    move-result-object v0

    if-nez v0, :cond_0

    .line 2
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    const-string v1, ""

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->a(Ljava/lang/CharSequence;)V

    goto :goto_0

    .line 3
    :cond_0
    iget-object v1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    iget-object v2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->j:Lp/b/a/w/b;

    invoke-virtual {v2, v0}, Lp/b/a/w/b;->a(Lp/b/a/y/e;)Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v1, v0}, Landroidx/preference/Preference;->a(Ljava/lang/CharSequence;)V

    :goto_0
    return-void
.end method

.method private a(Ljava/lang/String;)V
    .locals 2

    .line 31
    new-instance v0, Ljava/util/HashMap;

    invoke-direct {v0}, Ljava/util/HashMap;-><init>()V

    const-string v1, "language_code"

    .line 32
    invoke-virtual {v0, v1, p1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    const-string p1, "update_preferred_subtitle_language"

    const-string v1, "account_settings_page"

    .line 33
    invoke-static {p1, v1, v0}, Lf/j/i/c;->a(Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;)V

    return-void
.end method

.method static synthetic a(Ljava/lang/Throwable;)V
    .locals 0

    return-void
.end method

.method static synthetic b(Landroid/content/DialogInterface;I)V
    .locals 0

    .line 8
    invoke-interface {p0}, Landroid/content/DialogInterface;->dismiss()V

    return-void
.end method


# virtual methods
.method public L()V
    .locals 5

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    const/4 v1, 0x0

    if-eqz v0, :cond_1

    invoke-virtual {v0}, Lf/j/a/i/c0;->m()Z

    move-result v0

    if-eqz v0, :cond_1

    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    if-eqz v0, :cond_1

    .line 2
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->getUsername()Ljava/lang/String;

    move-result-object v0

    .line 3
    invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v2

    if-eqz v2, :cond_0

    .line 4
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->getName()Ljava/lang/String;

    move-result-object v0

    .line 5
    :cond_0
    iget-object v2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    const v3, 0x7f110206

    const/4 v4, 0x1

    new-array v4, v4, [Ljava/lang/Object;

    aput-object v0, v4, v1

    invoke-virtual {p0, v3, v4}, Landroidx/fragment/app/Fragment;->getString(I[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v2, v0}, Landroidx/preference/Preference;->b(Ljava/lang/CharSequence;)V

    .line 6
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object v0

    invoke-virtual {v0}, Lcom/viki/library/beans/User;->getSubtitleLanguage()Ljava/lang/String;

    move-result-object v0

    .line 7
    iget-object v1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    invoke-virtual {v1, v0}, Landroidx/preference/ListPreference;->f(Ljava/lang/String;)V

    goto :goto_0

    .line 8
    :cond_1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    const v2, 0x7f110207

    invoke-virtual {v0, v2}, Landroidx/preference/Preference;->g(I)V

    .line 9
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    invoke-virtual {v0, v1}, Landroidx/preference/Preference;->g(Z)V

    :goto_0
    return-void
.end method

.method public synthetic a(Landroid/content/DialogInterface;I)V
    .locals 0

    .line 28
    invoke-interface {p1}, Landroid/content/DialogInterface;->dismiss()V

    .line 29
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object p1

    instance-of p1, p1, Lcom/viki/android/ui/settings/SettingsActivity;

    if-eqz p1, :cond_0

    .line 30
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object p1

    check-cast p1, Lcom/viki/android/ui/settings/SettingsActivity;

    invoke-virtual {p1}, Lcom/viki/android/ui/settings/SettingsActivity;->f()V

    :cond_0
    return-void
.end method

.method public a(Landroid/os/Bundle;Ljava/lang/String;)V
    .locals 0

    .line 1
    invoke-super {p0, p1, p2}, Lcom/viki/android/ui/settings/fragment/BasePreferenceFragment;->a(Landroid/os/Bundle;Ljava/lang/String;)V

    const p1, 0x7f140005

    .line 2
    invoke-virtual {p0, p1, p2}, Landroidx/preference/g;->a(ILjava/lang/String;)V

    const p1, 0x7f1102b3

    .line 3
    invoke-virtual {p0, p1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p0, p1}, Landroidx/preference/g;->a(Ljava/lang/CharSequence;)Landroidx/preference/Preference;

    move-result-object p1

    check-cast p1, Landroidx/preference/PreferenceCategory;

    return-void
.end method

.method public synthetic a(Ljava/lang/Boolean;Lj/b/z/b;)V
    .locals 0

    .line 23
    iget-object p2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    invoke-virtual {p1}, Ljava/lang/Boolean;->booleanValue()Z

    move-result p1

    invoke-virtual {p2, p1}, Landroidx/preference/TwoStatePreference;->h(Z)V

    return-void
.end method

.method public synthetic a(Ljava/lang/Boolean;Ljava/lang/Throwable;)V
    .locals 2

    .line 24
    instance-of p2, p2, Lf/a/c/t;

    const/4 v0, 0x1

    if-eqz p2, :cond_0

    .line 25
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object p2

    const v1, 0x7f1100fc

    invoke-virtual {p0, v1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object v1

    invoke-static {p2, v1, v0}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;

    move-result-object p2

    invoke-virtual {p2}, Landroid/widget/Toast;->show()V

    goto :goto_0

    .line 26
    :cond_0
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object p2

    const v1, 0x7f1101ea

    invoke-virtual {p0, v1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object v1

    invoke-static {p2, v1, v0}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;

    move-result-object p2

    invoke-virtual {p2}, Landroid/widget/Toast;->show()V

    .line 27
    :goto_0
    iget-object p2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    invoke-virtual {p1}, Ljava/lang/Boolean;->booleanValue()Z

    move-result p1

    xor-int/2addr p1, v0

    invoke-virtual {p2, p1}, Landroidx/preference/TwoStatePreference;->h(Z)V

    return-void
.end method

.method public synthetic a(Ljava/util/List;)V
    .locals 3

    .line 4
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0}, Lf/j/a/i/c0;->q()Z

    move-result v0

    if-eqz v0, :cond_0

    .line 5
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    const-string v0, ""

    invoke-virtual {p1, v0}, Landroidx/preference/Preference;->a(Ljava/lang/CharSequence;)V

    return-void

    .line 6
    :cond_0
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    .line 7
    invoke-static {p1}, Lf/j/a/j/h0;->h(Ljava/util/List;)Ljava/lang/String;

    move-result-object p1

    .line 8
    invoke-static {p1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v1

    if-nez v1, :cond_1

    .line 9
    invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 10
    :cond_1
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->M()Ljava/lang/String;

    move-result-object v1

    .line 11
    invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result v2

    if-nez v2, :cond_3

    .line 12
    invoke-static {p1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result p1

    if-nez p1, :cond_2

    const-string p1, "\n"

    .line 13
    invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 14
    :cond_2
    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 15
    :cond_3
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    invoke-virtual {p1, v0}, Landroidx/preference/Preference;->a(Ljava/lang/CharSequence;)V

    .line 16
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->T()V

    return-void
.end method

.method public synthetic a(Landroidx/preference/Preference;Ljava/lang/Object;)Z
    .locals 3

    .line 17
    check-cast p2, Ljava/lang/Boolean;

    .line 18
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->r:Lj/b/z/a;

    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->q:Lf/j/f/b/h/c;

    invoke-virtual {p2}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v1

    invoke-virtual {v0, v1}, Lf/j/f/b/h/c;->a(Z)Lj/b/a;

    move-result-object v0

    .line 19
    invoke-static {}, Lj/b/y/b/a;->a()Lj/b/s;

    move-result-object v1

    invoke-virtual {v0, v1}, Lj/b/a;->a(Lj/b/s;)Lj/b/a;

    move-result-object v0

    new-instance v1, Lcom/viki/android/ui/settings/fragment/f;

    invoke-direct {v1, p0, p2}, Lcom/viki/android/ui/settings/fragment/f;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;Ljava/lang/Boolean;)V

    .line 20
    invoke-virtual {v0, v1}, Lj/b/a;->b(Lj/b/b0/f;)Lj/b/a;

    move-result-object v0

    sget-object v1, Lcom/viki/android/ui/settings/fragment/i;->a:Lcom/viki/android/ui/settings/fragment/i;

    new-instance v2, Lcom/viki/android/ui/settings/fragment/h;

    invoke-direct {v2, p0, p2}, Lcom/viki/android/ui/settings/fragment/h;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;Ljava/lang/Boolean;)V

    .line 21
    invoke-virtual {v0, v1, v2}, Lj/b/a;->a(Lj/b/b0/a;Lj/b/b0/f;)Lj/b/z/b;

    move-result-object p2

    .line 22
    invoke-virtual {p1, p2}, Lj/b/z/a;->b(Lj/b/z/b;)Z

    const/4 p1, 0x0

    return p1
.end method

.method public synthetic b(Landroidx/preference/Preference;Ljava/lang/Object;)Z
    .locals 3

    .line 1
    check-cast p2, Ljava/lang/String;

    .line 2
    invoke-static {p2}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z

    move-result p1

    if-nez p1, :cond_0

    .line 3
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->r:Lj/b/z/a;

    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {v0, p2}, Lf/j/a/i/c0;->g(Ljava/lang/String;)Lj/b/a;

    move-result-object v0

    sget-object v1, Lcom/viki/android/ui/settings/fragment/l;->a:Lcom/viki/android/ui/settings/fragment/l;

    sget-object v2, Lcom/viki/android/ui/settings/fragment/k;->a:Lcom/viki/android/ui/settings/fragment/k;

    .line 4
    invoke-virtual {v0, v1, v2}, Lj/b/a;->a(Lj/b/b0/a;Lj/b/b0/f;)Lj/b/z/b;

    move-result-object v0

    .line 5
    invoke-virtual {p1, v0}, Lj/b/z/a;->b(Lj/b/z/b;)Z

    .line 6
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {p1}, Lf/j/a/i/c0;->h()Lcom/viki/library/beans/User;

    move-result-object p1

    invoke-virtual {p1, p2}, Lcom/viki/library/beans/User;->setSubtitleLanguage(Ljava/lang/String;)V

    .line 7
    invoke-direct {p0, p2}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->a(Ljava/lang/String;)V

    :cond_0
    const/4 p1, 0x1

    return p1
.end method

.method public synthetic c(Landroidx/preference/Preference;)Z
    .locals 8

    .line 1
    invoke-static {}, Lf/j/a/i/c0;->y()Z

    move-result p1

    const/4 v0, 0x1

    if-eqz p1, :cond_0

    const-string p1, "settings_login_button_tapped"

    .line 2
    invoke-static {p1}, Lf/j/a/a/a;->a(Ljava/lang/String;)Lf/j/a/a/a;

    move-result-object p1

    invoke-static {p1}, Lf/j/a/a/b;->a(Lf/j/a/a/a;)V

    .line 3
    new-instance p1, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;

    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v1

    invoke-direct {p1, v1}, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;-><init>(Landroid/app/Activity;)V

    .line 4
    invoke-virtual {p1, v0}, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;->a(I)Lcom/viki/android/ui/registration/GeneralSignInActivity$a;

    const-string v1, "account_settings"

    .line 5
    invoke-virtual {p1, v1}, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;->b(Ljava/lang/String;)Lcom/viki/android/ui/registration/GeneralSignInActivity$a;

    const-string v1, "account_settings_page"

    .line 6
    invoke-virtual {p1, v1}, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;->a(Ljava/lang/String;)Lcom/viki/android/ui/registration/GeneralSignInActivity$a;

    .line 7
    invoke-virtual {p1}, Lcom/viki/android/ui/registration/GeneralSignInActivity$a;->b()V

    goto :goto_0

    .line 8
    :cond_0
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v2

    const v3, 0x7f110205

    const v4, 0x7f110204

    const v5, 0x7f11006f

    new-instance v6, Lcom/viki/android/ui/settings/fragment/m;

    invoke-direct {v6, p0}, Lcom/viki/android/ui/settings/fragment/m;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    sget-object v7, Lcom/viki/android/ui/settings/fragment/g;->a:Lcom/viki/android/ui/settings/fragment/g;

    invoke-static/range {v2 .. v7}, Lcom/viki/android/utils/i1;->a(Landroid/app/Activity;IIILandroid/content/DialogInterface$OnClickListener;Landroid/content/DialogInterface$OnClickListener;)V

    :goto_0
    return v0
.end method

.method public synthetic d(Landroidx/preference/Preference;)Z
    .locals 2

    .line 1
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object p1

    sget-object v0, Lcom/viki/android/BirthdayUpdateActivity$b;->b:Lcom/viki/android/BirthdayUpdateActivity$b;

    const/4 v1, 0x0

    invoke-static {p1, v0, v1}, Lcom/viki/android/BirthdayUpdateActivity;->a(Landroid/content/Context;Lcom/viki/android/BirthdayUpdateActivity$b;Z)Landroid/content/Intent;

    move-result-object p1

    .line 2
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->getActivity()Landroidx/fragment/app/d;

    move-result-object v0

    const/16 v1, 0x101

    invoke-virtual {v0, p1, v1}, Landroidx/fragment/app/d;->startActivityForResult(Landroid/content/Intent;I)V

    const/4 p1, 0x1

    return p1
.end method

.method public onActivityResult(IILandroid/content/Intent;)V
    .locals 1

    const/16 v0, 0x101

    if-ne p1, v0, :cond_0

    .line 1
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->T()V

    goto :goto_0

    .line 2
    :cond_0
    invoke-super {p0, p1, p2, p3}, Landroidx/fragment/app/Fragment;->onActivityResult(IILandroid/content/Intent;)V

    :goto_0
    return-void
.end method

.method public onCreate(Landroid/os/Bundle;)V
    .locals 0

    .line 1
    invoke-super {p0, p1}, Landroidx/preference/g;->onCreate(Landroid/os/Bundle;)V

    .line 2
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object p1

    invoke-static {p1}, Lcom/viki/android/s3/f;->a(Landroid/content/Context;)Lcom/viki/android/s3/a;

    move-result-object p1

    invoke-interface {p1}, Lcom/viki/android/s3/a;->I()Lf/j/a/i/c0;

    move-result-object p1

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    .line 3
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object p1

    invoke-static {p1}, Lcom/viki/android/s3/f;->a(Landroid/content/Context;)Lcom/viki/android/s3/a;

    move-result-object p1

    invoke-interface {p1}, Lcom/viki/android/s3/a;->z()Lf/j/f/b/h/g;

    move-result-object p1

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->p:Lf/j/f/b/h/g;

    .line 4
    invoke-virtual {p0}, Landroidx/fragment/app/Fragment;->requireContext()Landroid/content/Context;

    move-result-object p1

    invoke-static {p1}, Lcom/viki/android/s3/f;->a(Landroid/content/Context;)Lcom/viki/android/s3/a;

    move-result-object p1

    invoke-interface {p1}, Lcom/viki/android/s3/a;->n()Lf/j/f/b/h/c;

    move-result-object p1

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->q:Lf/j/f/b/h/c;

    return-void
.end method

.method public onDestroyView()V
    .locals 1

    .line 1
    iget-object v0, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->r:Lj/b/z/a;

    invoke-virtual {v0}, Lj/b/z/a;->a()V

    .line 2
    invoke-super {p0}, Landroidx/preference/g;->onDestroyView()V

    return-void
.end method

.method public onResume()V
    .locals 0

    .line 1
    invoke-super {p0}, Landroidx/fragment/app/Fragment;->onResume()V

    .line 2
    invoke-virtual {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->L()V

    return-void
.end method

.method public onViewCreated(Landroid/view/View;Landroid/os/Bundle;)V
    .locals 1

    .line 1
    invoke-super {p0, p1, p2}, Lcom/sa90/onepreference/fragment/BaseOnePreferenceFragment;->onViewCreated(Landroid/view/View;Landroid/os/Bundle;)V

    const p1, 0x7f1101bc

    .line 2
    invoke-virtual {p0, p1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p0, p1}, Landroidx/preference/g;->a(Ljava/lang/CharSequence;)Landroidx/preference/Preference;

    move-result-object p1

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->k:Landroidx/preference/Preference;

    const p1, 0x7f1101bf

    .line 3
    invoke-virtual {p0, p1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p0, p1}, Landroidx/preference/g;->a(Ljava/lang/CharSequence;)Landroidx/preference/Preference;

    move-result-object p1

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->l:Landroidx/preference/Preference;

    const p1, 0x7f1101bd

    .line 4
    invoke-virtual {p0, p1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p0, p1}, Landroidx/preference/g;->a(Ljava/lang/CharSequence;)Landroidx/preference/Preference;

    move-result-object p1

    check-cast p1, Landroidx/preference/ListPreference;

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    const p1, 0x7f11012d

    .line 5
    invoke-virtual {p0, p1}, Landroidx/fragment/app/Fragment;->getString(I)Ljava/lang/String;

    move-result-object p1

    invoke-virtual {p0, p1}, Landroidx/preference/g;->a(Ljava/lang/CharSequence;)Landroidx/preference/Preference;

    move-result-object p1

    check-cast p1, Landroidx/preference/SwitchPreference;

    iput-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->n:Landroidx/preference/SwitchPreference;

    .line 6
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->S()V

    .line 7
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->m:Landroidx/preference/ListPreference;

    new-instance p2, Lcom/viki/android/ui/settings/fragment/n;

    invoke-direct {p2, p0}, Lcom/viki/android/ui/settings/fragment/n;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    invoke-virtual {p1, p2}, Landroidx/preference/Preference;->a(Landroidx/preference/Preference$d;)V

    .line 8
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->N()V

    .line 9
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->O()V

    .line 10
    invoke-direct {p0}, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->P()V

    .line 11
    iget-object p1, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->r:Lj/b/z/a;

    iget-object p2, p0, Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;->o:Lf/j/a/i/c0;

    invoke-virtual {p2}, Lf/j/a/i/c0;->s()Lj/b/n;

    move-result-object p2

    new-instance v0, Lcom/viki/android/ui/settings/fragment/p;

    invoke-direct {v0, p0}, Lcom/viki/android/ui/settings/fragment/p;-><init>(Lcom/viki/android/ui/settings/fragment/GeneralPreferenceFragment;)V

    invoke-virtual {p2, v0}, Lj/b/n;->d(Lj/b/b0/f;)Lj/b/z/b;

    move-result-object p2

    invoke-virtual {p1, p2}, Lj/b/z/a;->b(Lj/b/z/b;)Z

    return-void
.end method
